// AUTO-GENERATED — Catalogue de matériel roulant (essai série BB 7200)
// Source dessins : MLG Traffic (CC BY-NC-SA 3.0). Specs : fr.wikipedia.org/wiki/BB_7200 (recoupé).
// Ne pas éditer à la main — régénéré par le pipeline d'enrichissement.
export const CATALOG = [
  {
    "id": "cat-BB7200_GC_Bou_R",
    "name": "BB 7200 réversible (réversibilité) — grandes cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_GC_Bou_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_GC_CP2I_R",
    "name": "BB 7200 livrée Corail Plus claire (Carmillon) — grandes cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_GC_CP2I_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_GC_CP2_R",
    "name": "BB 7200 livrée Corail Plus (claire) — grandes cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_GC_CP2_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_GC_CPI_R",
    "name": "BB 7200 livrée Corail Plus (Carmillon) — grandes cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_GC_CPI_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_GC_CP_R",
    "name": "BB 7200 livrée Corail Plus — grandes cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_GC_CP_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_GC_EVIBou_R",
    "name": "BB 7200 livrée En Voyage réversible — grandes cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_GC_EVIBou_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_GC_EVI_R",
    "name": "BB 7200 livrée En Voyage (Carmillon) — grandes cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_GC_EVI_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_GC_EV_R",
    "name": "BB 7200 livrée En Voyage — grandes cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_GC_EV_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_GC_FI_R",
    "name": "BB 7200 livrée Fret (Carmillon) — grandes cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_GC_FI_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_GC_F_R",
    "name": "BB 7200 livrée Fret — grandes cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_GC_F_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_GC_Fant_R",
    "name": "BB 7200 livrée fantôme (2010) — grandes cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_GC_Fant_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_GC_GB1_R",
    "name": "BB 7200 livrée béton (origine) — grandes cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_GC_GB1_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_GC_GBC_R",
    "name": "BB 7200 livrée béton (logo casquette) — grandes cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_GC_GBC_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_GC_GBI_R",
    "name": "BB 7200 livrée béton (logo Carmillon) — grandes cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_GC_GBI_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_GC_GBN_R",
    "name": "BB 7200 livrée béton (logo nouille) — grandes cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_GC_GBN_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_PC_CPI_R",
    "name": "BB 7200 livrée Corail Plus (Carmillon) — petites cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_PC_CPI_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_PC_CP_R",
    "name": "BB 7200 livrée Corail Plus — petites cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_PC_CP_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_PC_EV_R",
    "name": "BB 7200 livrée En Voyage — petites cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_PC_EV_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_PC_FI_R",
    "name": "BB 7200 livrée Fret (Carmillon) — petites cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_PC_FI_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_PC_F_R",
    "name": "BB 7200 livrée Fret — petites cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_PC_F_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_PC_Fant_R",
    "name": "BB 7200 livrée fantôme (2010) — petites cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_PC_Fant_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_PC_GB1_R",
    "name": "BB 7200 livrée béton (origine) — petites cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_PC_GB1_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_PC_GBC_R",
    "name": "BB 7200 livrée béton (logo casquette) — petites cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_PC_GBC_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_PC_GBI_R",
    "name": "BB 7200 livrée béton (logo Carmillon) — petites cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_PC_GBI_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  },
  {
    "id": "cat-BB7200_PC_GBN_R",
    "name": "BB 7200 livrée béton (logo nouille) — petites cabines",
    "category": "locomotive",
    "traction": "electrique",
    "maxSpeed": 160,
    "power": 4040,
    "mass": 84,
    "tonnage": 84,
    "passengerCapacity": 0,
    "freightCapacity": 0,
    "length": 17.6,
    "imageData": "img/catalog/SNCF/LE/BB7200_PC_GBN_R.gif",
    "seriesName": "BB 7200",
    "numberStart": 7201,
    "purchasePrice": 4040000,
    "cargoTypes": [],
    "_source": "MLG Traffic (CC BY-NC-SA) + fr.wikipedia.org/wiki/BB_7200"
  }
];
