import { ChronologicalClock } from './chronological-clock.js';
type ParisTime = {
    hours: number;
    minutes: number;
    seconds: number;
    dayOfWeek: number;
    date: Date;
};
type MinuteTick = (timeOfDay: number, dateStr: string, parisTime: ParisTime) => void;
type MoveTick = (dtSeconds: number, timeOfDay: number) => void;
export declare class SimulationEngine {
    chronologicalClock: ChronologicalClock | null;
    private _replayTimeSecond;
    private _replayTime;
    enableChronologicalReplay(raw?: unknown, fallbackMs?: number, nowMs?: number): void;
    getSimulationEpochMs(): number;
    getReplayDebtSeconds(): number;
    toClockSave(): import("./chronological-clock.js").ChronologicalSnapshot | null;
    private _timeAtEpoch;
    private _updateChronological;
    paused: boolean;
    lastMinute: number;
    onTick: MinuteTick | null;
    onMoveTick: MoveTick | null;
    onSecondTick: MinuteTick | null;
    lastSecondKey: string;
    currentDate: string | null;
    lastMoveTime: number;
    moveInterval: number;
    _ptCache: ParisTime | null;
    _ptCacheTime: number;
    _lastFrameTime: number;
    _accumulator: number;
    _maxFrameDt: number;
    discardedPhysicsSeconds: number;
    _hiddenFrameDt: number;
    _maxMoveStepsPerUpdate: number;
    _timeOffset: number | null;
    _baseDate: Date | null;
    _baseTimeOfDay: number;
    _parisFormatter: Intl.DateTimeFormat | null;
    constructor();
    _getRealParisTime(now?: Date): ParisTime;
    _realMinute(): number;
    setGameTime(timeOfDay: number | null, dateStr: string | null): void;
    _computeGameTime(): ParisTime;
    getParisTime(): ParisTime;
    _formatDateISO(d: Date): string;
    getParisDate(): string;
    update(): void;
    getFormattedTime(): string;
    getFormattedDate(): string;
}
export {};
