import type { BaseMapSource, TileAccessState } from './tile-access-policy.js';
type __KPStruct126 = string;
type TileRecord = {
    loaded: boolean;
    error: boolean;
    img: HTMLImageElement | null;
    errorTime: number;
    retryAt?: number;
    cacheKey?: string;
    inspectStatus?: boolean;
};
type TileQueueItem = {
    tile: TileRecord;
    url: string;
    z: number;
    viewZ?: number;
    isWeather?: boolean;
    key: string;
};
export declare class TileMap {
    readonly tileAccess: import("./tile-access-policy.js").TileAccessPolicy;
    private _unsubscribeAccess;
    private _renderCanvas;
    private _baseTilesDrawn;
    private _mapCredit;
    private _baseSource;
    private _loads;
    private _sourceIds;
    private _nextSourceId;
    private _collectingTiles;
    private _visibleTileKeys;
    private _networkEnabled;
    private _draining;
    private _retryTimer;
    private _retryDeadline;
    private _frameCacheWidth;
    private _frameCacheHeight;
    private readonly _unavailableTile;
    readonly networkStats: {
        started: number;
        loaded: number;
        failed: number;
        cancelled: number;
        discardedQueued: number;
        peakActive: number;
    };
    tileSize: number;
    tileCache: Map<string, TileRecord>;
    centerLat: number;
    centerLon: number;
    zoomLevel: number;
    minZoom: number;
    maxZoom: number;
    viewportWidth: number;
    viewportHeight: number;
    _baseLoading: number;
    _railLoading: number;
    _defaultMaxBaseConn: number;
    _defaultMaxRailConn: number;
    _maxBaseConn: number;
    _maxRailConn: number;
    _gpsLowMemoryMode: boolean;
    _tileCacheLimit: number;
    _baseQueue: TileQueueItem[];
    _railQueue: TileQueueItem[];
    _lastQueueZoom: number;
    _generation: number;
    _zoomDebounceTimer: ReturnType<typeof setTimeout> | null;
    _zoomSettled: boolean;
    _lastRoundedZoom: number;
    _dirty: boolean;
    _lastCenterLat: number;
    _lastCenterLon: number;
    _lastZoom: number;
    _tileCanvas: HTMLCanvasElement | null;
    _tileCtx: CanvasRenderingContext2D | null;
    _tileBufferValid: boolean;
    _tileBufferW: number;
    _tileBufferH: number;
    _pendingTiles: number;
    _lastPendingTiles: number;
    sourceZoomBias: number;
    bufferScale: number;
    _tileBufferScale: number;
    _osmBaseTileUrls: string[];
    _darkBaseTileUrls: string[];
    _lightBaseTileUrls: string[];
    baseTileUrls: string[];
    satelliteTileUrls: string[];
    labelTileUrls: string[];
    weatherEnabled: boolean;
    satelliteEnabled: boolean;
    nightMapEnabled: boolean;
    nightSatelliteTileUrls: string[];
    _nightSatelliteMaxZoom: number;
    _baseMaxZoom: number;
    _satelliteMaxZoom: number;
    _railMaxZoom: number;
    _labelMaxZoom: number;
    railTileUrls: string[];
    railEnabled: boolean;
    basicMode: boolean;
    _basicWasRail: boolean;
    radarEnabled: boolean;
    _radarTileUrl: string | null;
    _radarMaxZoom: number;
    cloudEnabled: boolean;
    _cloudTileUrl: string | null;
    _cloudMaxZoom: number;
    _frameCacheZoom: number | undefined;
    _frameCacheLat: number | undefined;
    _frameCacheLon: number | undefined;
    _frameScale: number;
    _frameCx: number;
    _frameCy: number;
    _frameHalfW: number;
    _frameHalfH: number;
    constructor();
    private _protocol;
    getBaseMapSource(): BaseMapSource;
    /** Count is used only to distinguish real pixels from an empty/loading canvas. */
    hasVisibleBaseTiles(): boolean;
    /** Explicit user choice. Does NOT reset a refusal, cache or retry deadline. */
    selectOSMStandard(): void;
    setBasicMode(enabled: boolean): void;
    private _updateMapCredit;
    getNightLightsOpacity(): number;
    getMapAppearanceLabel(): string;
    getMapCreditText(): string;
    getBaseMapAccess(): TileAccessState;
    getRailMapAccess(): TileAccessState;
    pauseRailMap(): void;
    resumeRailMap(): boolean;
    setBaseMapSource(source: BaseMapSource): void;
    pauseBaseMap(): void;
    resumeBaseMap(): boolean;
    setNetworkEnabled(enabled: boolean): void;
    onDocumentVisibilityChange(): void;
    private _networkCanRun;
    private _scheduleWake;
    private _tileSuffix;
    private _tileKey;
    private _stopSourceLoads;
    private _pruneViewportRequests;
    dispose(): void;
    markDirty(): void;
    _restartTileLoadPipelines(): void;
    _releaseTileBuffer(): void;
    setGPSLowMemoryMode(enabled: boolean): boolean;
    _effectiveTileZoom(): number;
    setRenderQuality(sourceZoomBias?: unknown, bufferScale?: unknown): void;
    _checkDirty(): void;
    get isDirty(): boolean;
    clearDirty(): void;
    latLonToGlobalPixel(lat: number, lon: number, zoom: number): {
        x: number;
        y: number;
    };
    globalPixelToLatLon(px: number, py: number, zoom: number): {
        lat: number;
        lon: number;
    };
    _updateFrameCache(): void;
    worldToScreenFast(lat: number, lon: number): {
        x: number;
        y: number;
    };
    worldToScreen(lat: number, lon: number, canvasW: number, canvasH: number): {
        x: number;
        y: number;
    };
    screenToWorld(sx: number, sy: number, canvasW: number, canvasH: number): {
        lat: number;
        lon: number;
    };
    pan(dx: number, dy: number): void;
    applyZoom(delta: number, sx: unknown, sy: unknown): void;
    _processQueue(): void;
    _drainPool(queue: TileQueueItem[], curZ: number, isRail: boolean): void;
    _fetchTile(tile: TileRecord, url: string, isRail: boolean, releasePermit?: () => void): void;
    getTile(tx: number, ty: number, z: number, urlTemplate: __KPStruct126): TileRecord;
    renderTiles(ctx: CanvasRenderingContext2D, canvasW: number, canvasH: number): void;
    latLonToPixel(lat: number, lon: number): {
        x: number;
        y: number;
    };
    getPixelsPerKm(): number;
    setRadarTileUrl(url: string): void;
    toggleRadar(): boolean;
    setCloudTileUrl(url: string): void;
    toggleCloud(): boolean;
    toggleBasic(): boolean;
    toggleSatellite(): boolean;
    setWeatherEnabled(enabled: boolean): void;
    setNightMapEnabled(enabled: boolean): boolean;
    setSatelliteEnabled(enabled: boolean): void;
}
export {};
