import type { RailEmpire } from './main.js';
type Audience = 'Tous' | 'Pendulaires' | 'Affaires' | 'Loisirs' | 'Familles' | 'Premium' | 'Jeunes' | 'Seniors' | 'Groupes';
type OfferType = 'tarif' | 'abonnement' | 'fidélité' | 'service' | 'confort' | 'promotion';
type ReviewTone = 'positive' | 'mixed' | 'negative';
type FeedbackStatus = 'new' | 'replied' | 'closed';
type CustomerOffer = {
    id: string;
    name: string;
    type: OfferType;
    target: Audience;
    description: string;
    priceDeltaPct: number;
    demandBoost: number;
    satisfactionBoost: number;
    active: boolean;
    featured: boolean;
};
type CateringItem = {
    id: string;
    name: string;
    category: string;
    price: number;
    cost: number;
    quality: number;
    local: boolean;
    vegetarian: boolean;
    active: boolean;
    bestseller: boolean;
    salesToday: number;
};
type ServiceFeature = {
    id: string;
    name: string;
    category: string;
    description: string;
    costPerPassenger: number;
    satisfactionBoost: number;
    demandBoost: number;
    active: boolean;
};
type Campaign = {
    id: string;
    name: string;
    channel: string;
    target: Audience;
    objective: string;
    budgetPerDay: number;
    durationDays: number;
    daysRemaining: number;
    awarenessGain: number;
    demandGain: number;
    satisfactionGain: number;
    active: boolean;
    createdAt: string;
};
type AdSlot = {
    id: string;
    name: string;
    placement: string;
    format: string;
    advertiser: string;
    category: string;
    dailyPrice: number;
    contractDays: number;
    daysRemaining: number;
    active: boolean;
};
type CustomerFeedback = {
    id: string;
    date: string;
    author: string;
    rating: number;
    category: string;
    title: string;
    message: string;
    sentiment: ReviewTone;
    status: FeedbackStatus;
    responded: boolean;
    responseText: string;
    serviceName: string;
};
type PressReview = {
    id: string;
    date: string;
    media: string;
    title: string;
    excerpt: string;
    score: number;
    tone: ReviewTone;
};
type MarketingSettings = {
    farePolicy: 'éco' | 'équilibrée' | 'premium';
    compensationPolicy: 'minimale' | 'équilibrée' | 'généreuse';
    loyaltyProgram: 'aucun' | 'simple' | 'premium';
    brandPositioning: 'accessible' | 'généraliste' | 'premium' | 'écologique';
    customerCare: 'standard' | 'renforcé' | 'excellence';
    greenCommunication: boolean;
};
type MarketingHistory = {
    date: string;
    passengers: number;
    satisfaction: number;
    awareness: number;
    loyalty: number;
    punctuality: number;
    cateringRevenue: number;
    adRevenue: number;
    spend: number;
    net: number;
};
type MarketingStats = {
    satisfaction: number;
    awareness: number;
    loyalty: number;
    pressScore: number;
    averageFeedback: number;
    replyRate: number;
    activeCampaigns: number;
    activeOffers: number;
    activeMenuItems: number;
    activeFeatures: number;
    onboardRevenueToday: number;
    onboardCostToday: number;
    adRevenueToday: number;
    marketingSpendToday: number;
    netMarketingToday: number;
    dailyPassengers: number;
    demandMultiplier: number;
    fareMultiplier: number;
    lastDay: string;
};
type MarketingSave = {
    schemaVersion?: unknown;
    offers?: unknown;
    catering?: unknown;
    features?: unknown;
    campaigns?: unknown;
    adSlots?: unknown;
    feedbacks?: unknown;
    pressReviews?: unknown;
    settings?: unknown;
    stats?: unknown;
    history?: unknown;
    lastDailyDate?: unknown;
    lastPassengerCount?: unknown;
    tab?: unknown;
};
export declare class MarketingManager {
    offers: CustomerOffer[];
    catering: CateringItem[];
    features: ServiceFeature[];
    campaigns: Campaign[];
    adSlots: AdSlot[];
    feedbacks: CustomerFeedback[];
    pressReviews: PressReview[];
    history: MarketingHistory[];
    settings: MarketingSettings;
    stats: MarketingStats;
    private _lastDailyDate;
    private _lastPassengerCount;
    private _tab;
    private _liveSnapshot;
    private _dimensions;
    constructor();
    private _mergeCatalogs;
    toSave(): MarketingSave;
    loadFromSave(data: unknown): void;
    getPassengerDemandMultiplier(): number;
    getPassengerFareMultiplier(): number;
    syncFromGame(game: RailEmpire): void;
    dailyUpdate(game: RailEmpire, dateStr: string): void;
    render(container: HTMLElement | null, game: RailEmpire): void;
    private _collectGameStats;
    private _computeDimensions;
    private _recomputeDerived;
    private _dayHash;
    private _pick;
    private _generateFeedback;
    private _reviewService;
    private _reviewTitle;
    private _reviewText;
    private _dimensionLabel;
    private _generatePress;
    private _tone;
    private _renderPage;
    private _renderTabs;
    private _renderTab;
    private _renderOverview;
    private _renderOnboard;
    private _isDefaultOfferId;
    private _isDefaultFoodId;
    private _renderOffers;
    private _renderCampaigns;
    private _renderAds;
    private _renderSatisfaction;
    private _renderFeedback;
    private _renderPress;
    private _kpi;
    private _stat;
    private _select;
    private _bind;
    private _addCampaign;
    private _companyReply;
    private _normOffer;
    private _normFood;
    private _normFeature;
    private _normCampaign;
    private _normAd;
    private _normFeedback;
    private _normPress;
    private _normHistory;
}
export {};
