type AnyRecord = Record<string, any>;
type ScheduleStateValue = typeof ScheduleState[keyof typeof ScheduleState];
type TrainCategoryValue = typeof TrainCategory[keyof typeof TrainCategory];
type StopCodeValue = typeof StopCode[keyof typeof StopCode];
type LocationKindValue = typeof LocationKind[keyof typeof LocationKind];
type PathDirectionValue = typeof PathDirection[keyof typeof PathDirection];
type PerformanceModeValue = typeof PerformanceMode[keyof typeof PerformanceMode];
type GeoPoint = {
    lat: number;
    lon: number;
};
type ElectricalSystem = {
    voltage: number;
    frequency: number;
};
type RoutePointLike = AnyRecord & {
    lat?: number | string | null;
    lon?: number | string | null;
    wayId?: string | number | null;
    segmentIndex?: number | null;
    maxSpeed?: number | string | null;
    maxSpeedSource?: string;
    maxSpeedForward?: number | string | null;
    maxSpeedBackward?: number | string | null;
    electrified?: boolean | string | null;
    electrifiedMode?: string;
    voltage?: unknown[];
    frequency?: unknown[];
    gauge?: unknown[];
    loadingGauge?: string;
    axleLoad?: number | string | null;
    metreLoad?: number | string | null;
    tracks?: number | string;
    trafficMode?: string;
    trainProtection?: AnyRecord;
    usage?: string;
    service?: string;
    railway?: string;
    railwayLifecycle?: string;
    railwayBaseType?: string;
    preferredDirection?: string;
    bidirectional?: string;
    oneway?: string;
    trackRef?: string;
    name?: string;
    ref?: string;
    tags?: AnyRecord;
    fallback?: boolean;
    _againstPreferredDirection?: boolean;
};
type ScheduleLeg = {
    id: string;
    fromLocationId: string;
    toLocationId: string;
    constraintIds: string[];
    routeInputKey: string;
    physicsRouteKey: string;
    physicalTravelSec: number | null;
    physicalTravelSignature: string;
    routePoints: RoutePointLike[];
    segments: RouteSegmentSnapshot[];
    distanceKm: number;
};
type PackedScheduleRoute = {
    format: 'SC8P1';
    scale: number;
    count: number;
    coords: number[];
    wayDict: string[];
    wayIndex: number[];
    segmentIndex: number[];
    metaDict: AnyRecord[];
    metaIndex: number[];
};
type ValidationIssueLike = {
    id?: string;
    level: string;
    code: string;
    message: string;
    data?: unknown;
};
type ScheduleReference = {
    scheduleId: string;
    versionId?: string;
    locationId?: string;
};
type RotationManagerBridge = {
    findScheduleReferences?: (id: string) => ScheduleReference[];
    removeScheduleReferences?: (id: string) => unknown;
    removeDirectAssignment?: (id: string) => unknown;
    addOccurrence?: (rotationId: string, data: AnyRecord) => unknown;
    recalculateRotation?: (rotationId: string) => unknown;
    toSave?: () => unknown;
    loadFromSave?: (data: unknown) => unknown;
};
type OperatingCalendarInput = AnyRecord & {
    id?: string;
    name?: string;
    startDate?: string;
    endDate?: string;
    weekdays?: unknown[];
    excludedDates?: unknown[];
    enabled?: boolean;
};
type TrackBindingInput = AnyRecord & {
    voiePointId?: unknown;
    wayId?: string | number | null;
    trackRef?: string;
    displayName?: string;
    lat?: unknown;
    lon?: unknown;
    snapLat?: unknown;
    snapLon?: unknown;
    segmentIndex?: unknown;
    osmSnapshot?: AnyRecord | null;
};
type RouteConstraintInput = TrackBindingInput & {
    id?: string;
    order?: unknown;
    legIndex?: unknown;
};
type RouteSegmentInput = AnyRecord & {
    from?: AnyRecord | null;
    to?: AnyRecord | null;
    distanceKm?: unknown;
    trainProtection?: AnyRecord;
    tags?: AnyRecord;
};
type ScheduleLegInput = AnyRecord & {
    id?: string;
    fromLocationId?: string;
    toLocationId?: string;
    constraintIds?: unknown[];
    routeInputKey?: string;
    physicsRouteKey?: string;
    physicalTravelSec?: unknown;
    physicalTravelSignature?: string;
    routePoints?: RoutePointLike[];
    routePacked?: AnyRecord | PackedScheduleRoute | null;
    segments?: RouteSegmentInput[];
    distanceKm?: unknown;
};
type SchedulePathInput = AnyRecord & {
    id?: string;
    direction?: PathDirectionValue;
    constraints?: RouteConstraintInput[];
    legs?: ScheduleLegInput[];
    routePoints?: RoutePointLike[];
    segments?: RouteSegmentInput[];
    distanceKm?: unknown;
    validatedAt?: string;
    ormRevision?: string;
    topologyRevision?: unknown;
    resolvedRevision?: unknown;
    offlineUsable?: boolean;
    error?: string;
};
type ScheduledLocationInput = AnyRecord & {
    id?: string;
    kind?: LocationKindValue;
    order?: unknown;
    stationId?: string;
    technicalLocationId?: string;
    name?: string;
    track?: TrackBindingInput;
    computedArrivalSec?: unknown;
    computedDepartureSec?: unknown;
    arrivalSec?: unknown;
    departureSec?: unknown;
    arrivalOverride?: boolean;
    departureOverride?: boolean;
    dwellSec?: unknown;
    stopCode?: StopCodeValue;
    turnBack?: boolean;
    notes?: string;
};
type TechnicalLocationInput = AnyRecord & {
    id?: string;
    name?: string;
    track?: TrackBindingInput;
    createdAt?: string;
};
type PerformanceProfileInput = AnyRecord & {
    id?: string;
    mode?: PerformanceModeValue;
    name?: string;
    referenceRameId?: string;
    referenceComposition?: AnyRecord[];
    category?: TrainCategoryValue;
    maxSpeed?: unknown;
    massKg?: unknown;
    powerW?: unknown;
    electricPowerW?: unknown;
    dieselPowerW?: unknown;
    lengthM?: unknown;
    adhesionMassKg?: unknown;
    brakeServiceMs2?: unknown;
    brakeBuildSec?: unknown;
    traction?: string;
    electricSystems?: AnyRecord[];
    gauges?: unknown[];
    loadingGauge?: string;
    axleLoad?: unknown;
    metreLoad?: unknown;
    source?: string;
};
type ValidationReportInput = AnyRecord & {
    timestamp?: string;
    ormRevision?: string;
    issues?: ValidationIssueLike[];
    deferred?: boolean;
};
type ScheduleVersionInput = AnyRecord & {
    id?: string;
    version?: unknown;
    createdAt?: string;
    state?: ScheduleStateValue;
    calendarIds?: unknown[];
    category?: TrainCategoryValue;
    performanceProfile?: PerformanceProfileInput;
    locations?: ScheduledLocationInput[];
    outboundPath?: SchedulePathInput;
    returnPath?: SchedulePathInput | null;
    validationReport?: ValidationReportInput | null;
    notes?: string;
    lastRecalculatedAt?: string;
    allowShorterThanPhysicalTiming?: boolean;
};
type ScheduleRecordInput = AnyRecord & {
    id?: string;
    number?: string;
    name?: string;
    createdAt?: string;
    versions?: ScheduleVersionInput[];
    currentVersionId?: string;
};
type RoundTripGroupInput = AnyRecord & {
    id?: string;
    outboundScheduleId?: string;
    returnScheduleId?: string;
    terminalLayoverSec?: unknown;
};
export declare const SCHEDULE_V2_SCHEMA = 2;
export declare const SCHEDULE_V2_MIN_SCHEMA = 1;
export declare const ScheduleState: Readonly<{
    DRAFT: "DRAFT";
    VALID: "VALID";
    NEEDS_REPAIR: "NEEDS_REPAIR";
}>;
export declare const TrainCategory: Readonly<{
    PASSENGER: "PASSENGER";
    FREIGHT: "FREIGHT";
    W: "W";
    HLP: "HLP";
    TM: "TM";
    INFRA: "INFRA";
    TTX: "TTX";
}>;
export declare const StopCode: Readonly<{
    NONE: "NONE";
    C: "C";
    S: "S";
    OPTIONAL_C: "OPTIONAL_C";
    OPTIONAL_S: "OPTIONAL_S";
}>;
export declare const LocationKind: Readonly<{
    STATION: "STATION";
    TECHNICAL: "TECHNICAL";
}>;
export declare const PathDirection: Readonly<{
    OUTBOUND: "OUTBOUND";
    RETURN: "RETURN";
}>;
export declare const PerformanceMode: Readonly<{
    REFERENCE_COMPOSITION: "REFERENCE_COMPOSITION";
    LINE_MAX_SPEED: "LINE_MAX_SPEED";
}>;
export declare function makeV2Id(prefix?: string): string;
export declare function isPassengerCategory(category: unknown): boolean;
export declare function isOptionalStopCode(code: unknown): boolean;
export declare function formatScheduleClock(totalSec: unknown): string;
export declare function parseScheduleClock(text: unknown, previousSec?: number, options?: AnyRecord): number | null;
export declare class OperatingCalendar {
    id: string;
    name: string;
    startDate: string;
    endDate: string;
    weekdays: number[];
    excludedDates: string[];
    enabled: boolean;
    constructor(data?: OperatingCalendarInput);
    matchesDate(dateStr: string): boolean;
    toJSON(): this;
}
export declare class TrackBinding {
    voiePointId: string;
    wayId: string;
    trackRef: string;
    displayName: string;
    lat: number | null;
    lon: number | null;
    snapLat: number | null;
    snapLon: number | null;
    segmentIndex: number | null;
    osmSnapshot: AnyRecord | null;
    constructor(data?: TrackBindingInput);
    get complete(): boolean;
    toJSON(): this;
}
export declare class RouteConstraint {
    id: string;
    order: number;
    lat: number | null;
    lon: number | null;
    wayId: string;
    snapLat: number | null;
    snapLon: number | null;
    trackRef: string;
    segmentIndex: number | null;
    osmSnapshot: AnyRecord | null;
    legIndex: number;
    constructor(data?: RouteConstraintInput);
    toJSON(): this;
}
export declare class RouteSegmentSnapshot {
    wayId: string;
    from: GeoPoint | null;
    to: GeoPoint | null;
    distanceKm: number;
    maxSpeed: number;
    maxSpeedSource: string;
    maxSpeedForward: number | null;
    maxSpeedBackward: number | null;
    electrified: boolean | string | null;
    electrifiedMode: string;
    voltage: number[];
    frequency: number[];
    gauge: number[];
    loadingGauge: string;
    axleLoad: number | null;
    metreLoad: number | null;
    tracks: number;
    trafficMode: string;
    trainProtection: AnyRecord;
    usage: string;
    service: string;
    railway: string;
    railwayLifecycle: string;
    railwayBaseType: string;
    preferredDirection: string;
    bidirectional: string;
    oneway: string;
    _againstPreferredDirection: boolean;
    trackRef: string;
    name: string;
    ref: string;
    tags: AnyRecord;
    fallback: boolean;
    constructor(data?: RouteSegmentInput);
    toJSON(): this;
}
export declare function assignResolvedLegsToPath(path: SchedulePath, legs: ScheduleLeg[], { validatedAt, resolvedRevision, error }?: AnyRecord): SchedulePath;
export declare class SchedulePath {
    id: string;
    direction: PathDirectionValue;
    constraints: RouteConstraint[];
    legs: ScheduleLeg[];
    globalGeometryShared: boolean;
    routePoints: RoutePointLike[];
    segments: Array<RouteSegmentSnapshot | AnyRecord>;
    distanceKm: number;
    validatedAt: string;
    ormRevision: string;
    topologyRevision: number;
    resolvedRevision: number;
    offlineUsable: boolean;
    error: string;
    constructor(data?: SchedulePathInput);
    clearResolvedRoute(): void;
    toJSON(): {
        id: string;
        direction: PathDirectionValue;
        constraints: RouteConstraint[];
        routePoints: RoutePointLike[];
        segments: AnyRecord[];
        legs: {
            id: string;
            fromLocationId: string;
            toLocationId: string;
            constraintIds: string[];
            routeInputKey: string;
            physicsRouteKey: string;
            physicalTravelSec: number | null;
            physicalTravelSignature: string;
            routePoints: RoutePointLike[];
            routePacked: PackedScheduleRoute | null;
            routePointStorage: string;
            segments: never[];
            distanceKm: number;
            segmentStorage: string;
        }[];
        distanceKm: number;
        validatedAt: string;
        ormRevision: string;
        topologyRevision: number;
        resolvedRevision: number;
        offlineUsable: boolean;
        error: string;
        geometryStorage: string;
        globalGeometryShared: boolean;
    };
}
export declare class ScheduledLocation {
    id: string;
    kind: LocationKindValue;
    order: number;
    stationId: string;
    technicalLocationId: string;
    name: string;
    track: TrackBinding;
    computedArrivalSec: number | null;
    computedDepartureSec: number | null;
    arrivalSec: number | null;
    departureSec: number | null;
    arrivalOverride: boolean;
    departureOverride: boolean;
    dwellSec: number;
    stopCode: StopCodeValue;
    turnBack: boolean;
    notes: string;
    constructor(data?: ScheduledLocationInput);
    setComputedTimes(arrivalSec: unknown, departureSec: unknown): void;
    applyManualArrival(sec: unknown): void;
    applyManualDeparture(sec: unknown): void;
    clearManualArrival(): void;
    clearManualDeparture(): void;
    toJSON(): this;
}
export declare class TechnicalLocation {
    id: string;
    name: string;
    track: TrackBinding;
    createdAt: string;
    constructor(data?: TechnicalLocationInput);
    toJSON(): this;
}
export declare class PerformanceProfile {
    id: string;
    mode: PerformanceModeValue;
    name: string;
    referenceRameId: string;
    referenceComposition: AnyRecord[];
    category: TrainCategoryValue;
    maxSpeed: number;
    massKg: number;
    powerW: number;
    electricPowerW: number;
    dieselPowerW: number;
    lengthM: number;
    adhesionMassKg: number;
    brakeServiceMs2: number;
    brakeBuildSec: number;
    traction: string;
    electricSystems: ElectricalSystem[];
    gauges: number[];
    loadingGauge: string;
    axleLoad: number | null;
    metreLoad: number | null;
    source: string;
    constructor(data?: PerformanceProfileInput);
    static fromLegacyRame(rame: AnyRecord, category?: TrainCategoryValue): PerformanceProfile;
    static genericForCategory(category: TrainCategoryValue, maxSpeed?: number): PerformanceProfile;
    toPhysicsParams(): AnyRecord;
    toJSON(): this;
}
export declare class ValidationIssue {
    id: string;
    level: string;
    code: string;
    message: string;
    data: unknown;
    constructor(level: string, code: string, message: string, data?: unknown);
}
export declare class ValidationReport {
    timestamp: string;
    ormRevision: string;
    issues: ValidationIssueLike[];
    deferred: boolean;
    constructor(data?: ValidationReportInput);
    get errors(): ValidationIssueLike[];
    get warnings(): ValidationIssueLike[];
    get unknowns(): ValidationIssueLike[];
    get information(): ValidationIssueLike[];
    get canValidate(): boolean;
    toJSON(): this;
}
export declare class ScheduleVersion {
    id: string;
    version: number;
    createdAt: string;
    state: ScheduleStateValue;
    calendarIds: string[];
    category: TrainCategoryValue;
    performanceProfile: PerformanceProfile;
    locations: ScheduledLocation[];
    outboundPath: SchedulePath;
    returnPath: SchedulePath | null;
    validationReport: ValidationReport | null;
    notes: string;
    automaticMarginSec: number;
    lastRecalculatedAt: string;
    allowShorterThanPhysicalTiming: boolean;
    constructor(data?: ScheduleVersionInput);
    normalize(): this;
    get firstDepartureSec(): number;
    get lastArrivalSec(): number;
    toJSON(): {
        id: string;
        version: number;
        createdAt: string;
        state: ScheduleStateValue;
        calendarIds: string[];
        category: TrainCategoryValue;
        performanceProfile: PerformanceProfile;
        locations: ScheduledLocation[];
        outboundPath: {
            id: string;
            direction: PathDirectionValue;
            constraints: RouteConstraint[];
            routePoints: RoutePointLike[];
            segments: AnyRecord[];
            legs: {
                id: string;
                fromLocationId: string;
                toLocationId: string;
                constraintIds: string[];
                routeInputKey: string;
                physicsRouteKey: string;
                physicalTravelSec: number | null;
                physicalTravelSignature: string;
                routePoints: RoutePointLike[];
                routePacked: PackedScheduleRoute | null;
                routePointStorage: string;
                segments: never[];
                distanceKm: number;
                segmentStorage: string;
            }[];
            distanceKm: number;
            validatedAt: string;
            ormRevision: string;
            topologyRevision: number;
            resolvedRevision: number;
            offlineUsable: boolean;
            error: string;
            geometryStorage: string;
            globalGeometryShared: boolean;
        };
        returnPath: {
            id: string;
            direction: PathDirectionValue;
            constraints: RouteConstraint[];
            routePoints: RoutePointLike[];
            segments: AnyRecord[];
            legs: {
                id: string;
                fromLocationId: string;
                toLocationId: string;
                constraintIds: string[];
                routeInputKey: string;
                physicsRouteKey: string;
                physicalTravelSec: number | null;
                physicalTravelSignature: string;
                routePoints: RoutePointLike[];
                routePacked: PackedScheduleRoute | null;
                routePointStorage: string;
                segments: never[];
                distanceKm: number;
                segmentStorage: string;
            }[];
            distanceKm: number;
            validatedAt: string;
            ormRevision: string;
            topologyRevision: number;
            resolvedRevision: number;
            offlineUsable: boolean;
            error: string;
            geometryStorage: string;
            globalGeometryShared: boolean;
        } | null;
        validationReport: ValidationReport | null;
        notes: string;
        automaticMarginSec: number;
        lastRecalculatedAt: string;
        allowShorterThanPhysicalTiming: boolean;
    };
}
export declare class ScheduleRecord {
    id: string;
    number: string;
    name: string;
    createdAt: string;
    versions: ScheduleVersion[];
    currentVersionId: string;
    constructor(data?: ScheduleRecordInput);
    get currentVersion(): ScheduleVersion;
    createVersion(options?: AnyRecord): ScheduleVersion;
    toJSON(): {
        id: string;
        number: string;
        name: string;
        createdAt: string;
        currentVersionId: string;
        versions: {
            id: string;
            version: number;
            createdAt: string;
            state: ScheduleStateValue;
            calendarIds: string[];
            category: TrainCategoryValue;
            performanceProfile: PerformanceProfile;
            locations: ScheduledLocation[];
            outboundPath: {
                id: string;
                direction: PathDirectionValue;
                constraints: RouteConstraint[];
                routePoints: RoutePointLike[];
                segments: AnyRecord[];
                legs: {
                    id: string;
                    fromLocationId: string;
                    toLocationId: string;
                    constraintIds: string[];
                    routeInputKey: string;
                    physicsRouteKey: string;
                    physicalTravelSec: number | null;
                    physicalTravelSignature: string;
                    routePoints: RoutePointLike[];
                    routePacked: PackedScheduleRoute | null;
                    routePointStorage: string;
                    segments: never[];
                    distanceKm: number;
                    segmentStorage: string;
                }[];
                distanceKm: number;
                validatedAt: string;
                ormRevision: string;
                topologyRevision: number;
                resolvedRevision: number;
                offlineUsable: boolean;
                error: string;
                geometryStorage: string;
                globalGeometryShared: boolean;
            };
            returnPath: {
                id: string;
                direction: PathDirectionValue;
                constraints: RouteConstraint[];
                routePoints: RoutePointLike[];
                segments: AnyRecord[];
                legs: {
                    id: string;
                    fromLocationId: string;
                    toLocationId: string;
                    constraintIds: string[];
                    routeInputKey: string;
                    physicsRouteKey: string;
                    physicalTravelSec: number | null;
                    physicalTravelSignature: string;
                    routePoints: RoutePointLike[];
                    routePacked: PackedScheduleRoute | null;
                    routePointStorage: string;
                    segments: never[];
                    distanceKm: number;
                    segmentStorage: string;
                }[];
                distanceKm: number;
                validatedAt: string;
                ormRevision: string;
                topologyRevision: number;
                resolvedRevision: number;
                offlineUsable: boolean;
                error: string;
                geometryStorage: string;
                globalGeometryShared: boolean;
            } | null;
            validationReport: ValidationReport | null;
            notes: string;
            automaticMarginSec: number;
            lastRecalculatedAt: string;
            allowShorterThanPhysicalTiming: boolean;
        }[];
    };
}
export declare function validateRoundTripPair(outVersion: ScheduleVersion | null | undefined, returnVersion: ScheduleVersion | null | undefined, { terminalLayoverSec }?: AnyRecord): ValidationIssue[];
export declare class RoundTripGroup {
    id: string;
    outboundScheduleId: string;
    returnScheduleId: string;
    terminalLayoverSec: number;
    constructor(data?: RoundTripGroupInput);
    toJSON(): this;
}
export declare class ScheduleV2Manager {
    private _batchClones;
    private _batchNumbers;
    private _batchNames;
    schemaVersion: number;
    schedules: ScheduleRecord[];
    calendars: OperatingCalendar[];
    roundTrips: RoundTripGroup[];
    technicalLocations: TechnicalLocation[];
    constructor();
    createDraft(data?: AnyRecord): ScheduleRecord;
    getSchedule(id: string): ScheduleRecord | null;
    getVersion(scheduleId: string, versionId?: string | null): ScheduleVersion | null;
    addCalendar(data?: AnyRecord): OperatingCalendar;
    addRoundTrip(data?: AnyRecord): RoundTripGroup;
    moveCalendar(id: string, targetIndex: number): boolean;
    removeCalendar(id: string, { rotationManager }?: AnyRecord): {
        ok: boolean;
        references: never[];
        affectedScheduleIds?: undefined;
        affectedRotationIds?: undefined;
    } | {
        ok: boolean;
        references: ({
            kind: string;
            scheduleId: string;
            versionId: string;
            rotationId?: undefined;
        } | {
            kind: string;
            rotationId: any;
            scheduleId?: undefined;
            versionId?: undefined;
        })[];
        affectedScheduleIds: unknown[];
        affectedRotationIds: unknown[];
    };
    resolveVersion(scheduleId: string, dateStr: string): ScheduleVersion | null;
    isTrainNumberAvailable(number: unknown, exceptScheduleId?: string): boolean;
    uniqueTrainNumber(preferred: unknown, exceptScheduleId?: string, step?: number): string;
    duplicateSchedule(id: string, options?: AnyRecord): ScheduleRecord | null;
    duplicateScheduleFrequency(id: string, options?: AnyRecord): Array<ScheduleRecord | null>;
    duplicateRoundTrip(groupId: string, options?: AnyRecord, rotationManager?: RotationManagerBridge | null): {
        group: RoundTripGroup;
        outbound: ScheduleRecord;
        return: ScheduleRecord;
        shiftSec: number;
    }[];
    addTechnicalLocation(data?: AnyRecord): TechnicalLocation;
    removeSchedule(id: string, { cascade, rotationManager }?: AnyRecord): {
        ok: boolean;
        references: any;
    };
    removeTechnicalLocation(id: string, { cascade }?: AnyRecord): {
        ok: boolean;
        references: ScheduleReference[];
    };
    toSave(): {
        schemaVersion: number;
        schedules: {
            id: string;
            number: string;
            name: string;
            createdAt: string;
            currentVersionId: string;
            versions: {
                id: string;
                version: number;
                createdAt: string;
                state: ScheduleStateValue;
                calendarIds: string[];
                category: TrainCategoryValue;
                performanceProfile: PerformanceProfile;
                locations: ScheduledLocation[];
                outboundPath: {
                    id: string;
                    direction: PathDirectionValue;
                    constraints: RouteConstraint[];
                    routePoints: RoutePointLike[];
                    segments: AnyRecord[];
                    legs: {
                        id: string;
                        fromLocationId: string;
                        toLocationId: string;
                        constraintIds: string[];
                        routeInputKey: string;
                        physicsRouteKey: string;
                        physicalTravelSec: number | null;
                        physicalTravelSignature: string;
                        routePoints: RoutePointLike[];
                        routePacked: PackedScheduleRoute | null;
                        routePointStorage: string;
                        segments: never[];
                        distanceKm: number;
                        segmentStorage: string;
                    }[];
                    distanceKm: number;
                    validatedAt: string;
                    ormRevision: string;
                    topologyRevision: number;
                    resolvedRevision: number;
                    offlineUsable: boolean;
                    error: string;
                    geometryStorage: string;
                    globalGeometryShared: boolean;
                };
                returnPath: {
                    id: string;
                    direction: PathDirectionValue;
                    constraints: RouteConstraint[];
                    routePoints: RoutePointLike[];
                    segments: AnyRecord[];
                    legs: {
                        id: string;
                        fromLocationId: string;
                        toLocationId: string;
                        constraintIds: string[];
                        routeInputKey: string;
                        physicsRouteKey: string;
                        physicalTravelSec: number | null;
                        physicalTravelSignature: string;
                        routePoints: RoutePointLike[];
                        routePacked: PackedScheduleRoute | null;
                        routePointStorage: string;
                        segments: never[];
                        distanceKm: number;
                        segmentStorage: string;
                    }[];
                    distanceKm: number;
                    validatedAt: string;
                    ormRevision: string;
                    topologyRevision: number;
                    resolvedRevision: number;
                    offlineUsable: boolean;
                    error: string;
                    geometryStorage: string;
                    globalGeometryShared: boolean;
                } | null;
                validationReport: ValidationReport | null;
                notes: string;
                automaticMarginSec: number;
                lastRecalculatedAt: string;
                allowShorterThanPhysicalTiming: boolean;
            }[];
        }[];
        calendars: OperatingCalendar[];
        roundTrips: RoundTripGroup[];
        technicalLocations: TechnicalLocation[];
    };
    loadFromSave(data: AnyRecord): boolean;
}
export {};
