type __KPM380 = {
    "state": unknown;
    "id": unknown;
};
import type { RailEmpire } from './main.js';
import { TileMap } from './map.js';
import { LocationKind, PathDirection, TrackBinding, RouteConstraint, ScheduledLocation, RoundTripGroup } from './schedule-v2-model.js';
import { ScheduleV2Router } from './schedule-v2-routing.js';
import type { RotationV2Manager } from './rotation-v2-model.js';
import type { ValidationReport, ScheduleVersion, SchedulePath, ScheduleRecord } from './schedule-v2-model.js';
type RailGeometryPoint = {
    lat?: unknown;
    lon?: unknown;
};
type RailWayLike = {
    geometry?: RailGeometryPoint[];
    nodeIds?: unknown[];
};
type TrackCandidateLike = {
    wayId?: unknown;
    trackRef?: unknown;
    name?: unknown;
    ref?: unknown;
    lat?: unknown;
    lon?: unknown;
    snapLat?: unknown;
    snapLon?: unknown;
    segmentIndex?: unknown;
    distanceM?: unknown;
    geometry?: RailGeometryPoint[];
    maxSpeed?: unknown;
    maxSpeedSource?: unknown;
    electrified?: unknown;
    electrifiedMode?: unknown;
    voltage?: unknown[];
    frequency?: unknown[];
    gauge?: unknown;
    loadingGauge?: unknown;
    axleLoad?: unknown;
    metreLoad?: unknown;
    trainProtection?: unknown;
    [key: string]: unknown;
};
type TrackChoiceLike = {
    candidate: TrackCandidateLike;
    displayName: string;
};
type TrackPickerOptions = {
    title?: string;
    requireName?: boolean;
    defaultName?: string;
};
type TrackAnchorLike = {
    wayId?: unknown;
    lat?: unknown;
    lon?: unknown;
    snapLat?: unknown;
    snapLon?: unknown;
    segmentIndex?: unknown;
    osmSnapshot?: Record<string, unknown> | null;
    trackRef?: unknown;
    displayName?: unknown;
};
type TimingLocationSnapshot = {
    id: unknown;
    computedArrivalSec: unknown;
    computedDepartureSec: unknown;
    arrivalSec: unknown;
    departureSec: unknown;
    arrivalOverride: boolean;
    departureOverride: boolean;
    dwellSec: number;
    stopCode: unknown;
    turnBack: boolean;
};
type TimingSnapshot = {
    kind: 'TIMING';
    recordId: string;
    versionId: string;
    mode: EditorPathDirection;
    state: ScheduleVersion['state'];
    validationReport: ScheduleVersion['validationReport'];
    lastRecalculatedAt: string;
    locations: TimingLocationSnapshot[];
};
type EditorSnapshotLike = {
    kind?: unknown;
    recordId?: unknown;
    versionId?: unknown;
    state?: unknown;
    validationReport?: unknown;
    lastRecalculatedAt?: unknown;
    locations?: TimingLocationSnapshot[];
    schedule?: ScheduleRecordSnapshot | null;
    returnSchedule?: ScheduleRecordSnapshot | null;
    roundTrip?: RoundTripSnapshot | null;
    technicalLocations?: unknown[];
    mode?: EditorPathDirection;
    preview?: EditorRoute;
    returnPreview?: EditorRoute;
};
type PanelFocusState = {
    key: string;
    start?: number;
    end?: number;
    direction?: 'forward' | 'backward' | 'none';
};
type PanelUiState = {
    details?: Array<{
        key: unknown;
        open: unknown;
    }>;
    scrollTop?: unknown;
    focus?: PanelFocusState | null;
};
type EditorPathDirection = typeof PathDirection[keyof typeof PathDirection];
type ScheduleRecordSnapshot = ReturnType<ScheduleRecord['toJSON']>;
type RoundTripSnapshot = ReturnType<RoundTripGroup['toJSON']>;
type EditorRoute = Awaited<ReturnType<ScheduleV2Router['routeBetweenBindings']>>;
type PendingStationLike = {
    action: 'ADD' | 'REPLACE' | 'CHANGE_TRACK';
    station: {
        id?: string;
        name?: string;
        lat?: number;
        lon?: number;
    };
    locationId?: string;
    defaultName?: string;
    kind?: typeof LocationKind[keyof typeof LocationKind];
    insertIndex?: number;
};
type EngineOsmWayLike = RailWayLike & {
    service?: unknown;
    tags?: {
        service?: unknown;
    };
};
type EngineOsmSwitchLike = {
    lat?: unknown;
    lon?: unknown;
};
type ConstraintEditLike = {
    mode: unknown;
    targetId: string;
};
type ScheduleEditorUiBridge = {
    renderSchedulesList?: () => unknown;
    rotationV2Editor?: {
        render?: () => unknown;
    };
};
export declare const SC_STATION_LABEL_MIN_ZOOM = 10.5;
export declare const SC_STATION_LABEL_ALL_ZOOM = 13.5;
export declare function inferRailJunctions(ways: unknown): {
    id: string;
    lat: number;
    lon: number;
    degree: number;
}[];
export declare function applyLineMaxSpeedToVersion(version: ScheduleVersion | null | undefined, rawValue: unknown): number | null;
export declare class ScheduleV2Editor {
    game: RailEmpire;
    ui: ScheduleEditorUiBridge | null;
    router: ScheduleV2Router;
    tileMap: TileMap;
    record: ScheduleRecord;
    version: ScheduleVersion;
    returnRecord: ScheduleRecord | null;
    returnVersion: ScheduleVersion | null;
    roundTripGroup: RoundTripGroup | null;
    mode: EditorPathDirection;
    previewRoute: EditorRoute;
    returnPreviewRoute: EditorRoute;
    busy: boolean;
    _routeGeneration: number;
    _routeAbortController: AbortController | null;
    _createdNewRecordId: string;
    dragging: boolean;
    panning: boolean;
    dragStartX: number;
    dragStartY: number;
    dragX: number;
    dragY: number;
    panThresholdPx: number;
    history: Array<EditorSnapshotLike | null>;
    future: Array<EditorSnapshotLike | null>;
    selectedConstraintId: string | null;
    insertConstraint: null;
    trackCandidates: TrackCandidateLike[];
    trackCandidateResolve: ((value: unknown) => void) | null;
    pendingStation: PendingStationLike | null;
    _replaceLocationId: unknown | null;
    _forcedConstraintLegIndex: number | null;
    _viaNext: boolean;
    _manualTraceMode: boolean;
    _manualTraceLegIndex: number | null;
    _onScheduleKeyDown: (e: KeyboardEvent) => void;
    _raf: number;
    _lastRenderAt: number;
    _autosaveTimer: number;
    _pendingRotationScheduleIds: Set<string>;
    _stationStreamTimer: number;
    _stationStreamPromise: Promise<number> | null;
    _stationStreamKey: string;
    _stationStreamLastAttempt: number;
    _engineOsmVisible: boolean;
    _engineOsmStreamTimer: number;
    _engineOsmStreamPromise: null;
    _engineOsmStreamKey: string;
    _engineOsmRenderCache: {
        key: string;
        ways: EngineOsmWayLike[];
        switches: EngineOsmSwitchLike[];
    };
    overlay: HTMLDivElement;
    canvas: HTMLCanvasElement;
    ctx: CanvasRenderingContext2D;
    panel: HTMLElement;
    panelContent: HTMLElement;
    picker: HTMLElement;
    pickerList: HTMLElement;
    trackNameInput: HTMLElement;
    _technicalNext: boolean;
    _constraintEdit: ConstraintEditLike | null;
    _hoverCandidate: TrackCandidateLike | null;
    constructor(game: RailEmpire, ui: ScheduleEditorUiBridge | null);
    _ensureOverlay(): void;
    _bindDomEvents(): void;
    _beginMapPointer(e: MouseEvent): boolean;
    _moveMapPointer(e: MouseEvent): boolean;
    _endMapPointer(e: MouseEvent): false | "click" | "pan";
    _cancelMapPointer(): boolean;
    _zoomMap(direction: number): void;
    isOpen(): boolean;
    _resetTransientModes({ cancelRouteJobs }?: Record<string, unknown>): void;
    _debugTrackSummary(track: TrackAnchorLike | null | undefined): {
        wayId: string;
        segmentIndex: number | null;
        lat: number;
        lon: number;
        snapLat: number;
        snapLon: number;
        trackRef: string;
        displayName: string;
        snapshot: {
            wayId: string;
            segmentIndex: number | null;
            distanceM: number | null;
            geometryPoints: number;
            nodeCount: number;
            geometry: any[];
            nodeIds: any[];
            tags: {};
            preferredDirection: {};
            bidirectional: {};
            oneway: {};
        };
    } | null;
    _diag(event: unknown, data?: unknown): void;
    _startScheduleDiagnosticSession(reason?: unknown): any;
    exportScheduleDiagnostic(): boolean;
    _routingOptions(ver?: ScheduleVersion | null, extra?: Record<string, unknown>): Record<string, unknown>;
    _cursorDistancePxToCandidate(lat: unknown, lon: unknown, candidate: TrackCandidateLike): number;
    _exactTrackBinding(lat: unknown, lon: unknown, displayName?: unknown): Promise<TrackBinding>;
    open(scheduleId?: unknown): void;
    close(): void;
    _adoptMainViewport(): boolean;
    _queueVisibleStationStream(force?: unknown): void;
    _streamVisibleNativeStations(force?: unknown): Promise<number>;
    _activeRecord(): ScheduleRecord;
    _activeVersion(): ScheduleVersion;
    _activePath(): SchedulePath;
    _activePreview(): import("./schedule-v2-routing.js").RoutePointLike[] & {
        _longRangeWindowed?: boolean;
    };
    _setActivePreview(route: EditorRoute): void;
    _operationalReadiness(record: {
        id: unknown;
    }, version: __KPM380, materialConflicts?: ReturnType<RotationV2Manager['validateMaterialConflicts']>): {
        code: string;
        label: string;
        cls: string;
        message?: undefined;
    } | {
        code: string;
        label: string;
        cls: string;
        message: string;
    };
    _directAssignmentDialog(scheduleId: unknown): void;
    _markRecordChanged(record?: ScheduleRecord, version?: ScheduleVersion, { needsValidation }?: Record<string, unknown>): void;
    _queueRotationRecalc(scheduleId: unknown): void;
    _flushRotationRecalc(): void;
    _makeTimingSnapshot(record?: ScheduleRecord, version?: ScheduleVersion): TimingSnapshot | null;
    _snapshotTiming(): void;
    _restoreTimingSnapshot(s: TimingSnapshot): boolean;
    _snapshot(): void;
    _restoreSnapshot(s: EditorSnapshotLike | null): boolean;
    _currentUndoSnapshot(kind?: string): EditorSnapshotLike | null;
    undo(): boolean;
    redo(): boolean;
    _resizeCanvas(): void;
    _scheduleDrawLoop(): void;
    draw(): void;
    _engineOsmViewportBounds(w: number, h: number, padRatio?: number): {
        south: number;
        west: number;
        north: number;
        east: number;
    } | null;
    _drawEngineOsm(ctx: CanvasRenderingContext2D, w: number, h: number): void;
    showWorldOsmStatus(): void;
    reloadWorldOsmVisible(): Promise<void>;
    _updateEngineOsmButton(): void;
    toggleEngineOsm(): void;
    _queueVisibleEngineOsm(force?: unknown): void;
    _streamVisibleEngineOsm(force?: unknown): Promise<number>;
    _drawStations(ctx: CanvasRenderingContext2D, w: number, h: number): void;
    _drawRoute(ctx: CanvasRenderingContext2D, route: unknown, color: string | CanvasGradient | CanvasPattern, alpha?: number): void;
    _drawPath(ctx: CanvasRenderingContext2D, path: SchedulePath | null | undefined, color: string | CanvasGradient | CanvasPattern, ver?: ScheduleVersion | null): void;
    _drawConstraints(ctx: CanvasRenderingContext2D, path: SchedulePath | null | undefined, color: string | CanvasGradient | CanvasPattern): void;
    _drawLocations(ctx: CanvasRenderingContext2D, ver: ScheduleVersion | null, color: string | CanvasGradient | CanvasPattern): void;
    _drawCandidateHighlight(ctx: CanvasRenderingContext2D): void;
    _centerOnContent(): void;
    _nearestStation(lat: number, lon: number, maxPixels?: number): any;
    _nearestConstraint(lat: number, lon: number, maxPx?: number): RouteConstraint | null;
    _handleMapClick(e: MouseEvent): Promise<void>;
    _loadCandidates(lat: unknown, lon: unknown): Promise<import("./schedule-v2-routing.js").RoutePointLike[]>;
    _candidateDetails(c: TrackCandidateLike): string;
    _pickTrack(candidates: TrackCandidateLike[], { title, requireName, defaultName }?: TrackPickerOptions): Promise<unknown>;
    _resolveTrackPicker(value: unknown): void;
    _trackBindingFromChoice(choice: TrackChoiceLike): TrackBinding;
    _cursorTrackBinding(lat: unknown, lon: unknown, displayName?: unknown): TrackBinding;
    _askTrackDisplayName(defaultName?: string | undefined): string;
    _finishPendingStationAnchor(lat: unknown, lon: unknown): Promise<void>;
    _addStationStop(st: __S3Struct277): Promise<void>;
    _changeLocationTrack(locationId: unknown): Promise<void>;
    _renameTrackDisplay(locationId: unknown): boolean;
    prepareStationReplacement(locationId: unknown): void;
    _replaceStationLocation(locationId: unknown, station: __S3Struct278): Promise<void>;
    _activeManualLegIndex(): number | null;
    _updateManualTraceButton(): void;
    toggleManualTrace(): void;
    resetActiveLegToAutomatic(): Promise<void>;
    armVia(): void;
    prepareViaForLeg(legIndex: unknown): void;
    _addConstraint(lat: unknown, lon: unknown, forcedOrder?: number | null, forcedLegIndex?: unknown): Promise<void>;
    _addTechnicalStop(lat: unknown, lon: unknown): Promise<void>;
    createTechnicalAtNextClick(): void;
    _physicalAnchorKey(track: TrackAnchorLike | null | undefined): string;
    _legRouteInputKey(ver: ScheduleVersion, path: SchedulePath, legIndex: number): string;
    _suggestStopInsertIndex(st: {
        lat: unknown;
        lon: unknown;
    }): number;
    _remapConstraintsForInsertedStop(path: SchedulePath, verBefore: ScheduledLocation[], insertIndex: number, newLoc: ScheduledLocation): void;
    _constraintsForLeg(path: SchedulePath | null | undefined, legIndex: number): RouteConstraint[];
    _resolveLeg(ver: ScheduleVersion, path: SchedulePath, fromIndex: number, toIndex: number, resolvedStart?: TrackAnchorLike | null, routeOptions?: Record<string, unknown>): Promise<{
        leg: {
            id: string;
            fromLocationId: string;
            toLocationId: string;
            constraintIds: string[];
            routeInputKey: string;
            physicsRouteKey: string;
            physicalTravelSec: number | null;
            physicalTravelSignature: string;
            routePoints: ({
                [x: string]: any;
            } & {
                lat?: number | string | null;
                lon?: number | string | null;
                wayId?: string | number | null;
                segmentIndex?: number | null;
                maxSpeed?: number | string | null;
                maxSpeedSource?: string;
                maxSpeedForward?: number | string | null;
                maxSpeedBackward?: number | string | null;
                electrified?: boolean | string | null;
                electrifiedMode?: string;
                voltage?: unknown[];
                frequency?: unknown[];
                gauge?: unknown[];
                loadingGauge?: string;
                axleLoad?: number | string | null;
                metreLoad?: number | string | null;
                tracks?: number | string;
                trafficMode?: string;
                trainProtection?: {
                    [x: string]: any;
                };
                usage?: string;
                service?: string;
                railway?: string;
                railwayLifecycle?: string;
                railwayBaseType?: string;
                preferredDirection?: string;
                bidirectional?: string;
                oneway?: string;
                trackRef?: string;
                name?: string;
                ref?: string;
                tags?: {
                    [x: string]: any;
                };
                fallback?: boolean;
                _againstPreferredDirection?: boolean;
            })[];
            segments: import("./schedule-v2-model.js").RouteSegmentSnapshot[];
            distanceKm: number;
        };
        anchorUpdates: {
            target: TrackBinding | RouteConstraint;
            r: any;
        }[];
    } | null>;
    _recomputeActivePath({ topologyChanged, forceFreshRoute }?: Record<string, unknown>): Promise<boolean>;
    _routeCompatibilityErrors(report: ValidationReport): boolean;
    _pathStructurallyCurrent(ver: ScheduleVersion, path: SchedulePath): boolean;
    _retimeCurrentPath(ver: ScheduleVersion): ValidationReport | null;
    _ensureActivePathReady(): Promise<boolean>;
    _recomputeBoth(): Promise<boolean>;
    prepareConstraintEdit(mode: unknown): void;
    _applyConstraintEditAt(lat: unknown, lon: unknown): Promise<void>;
    deleteLastPoint(): void;
    deleteSelectedConstraint(): void;
    beginReturn(): Promise<void>;
    _applyCoreFields(): void;
    _applySillonMaxSpeed(rawValue: unknown): boolean;
    _bindPanelEvents(): void;
    _setReturnName(value: unknown): boolean;
    _setReferenceRame(rameId: unknown): boolean;
    _deleteTechnicalLocation(technicalLocationId: unknown): void;
    _addExistingTechnical(technicalLocationId: unknown): Promise<void>;
    _duplicateRoundTripDialog(): void;
    _handleStopField(e: Event): void;
    removeStop(id: unknown): Promise<void>;
    _syncReturnStart(): void;
    showCalendarManager(): void;
    _createVersion(): void;
    _switchVersion(versionId: unknown): void;
    _setCalendarChecked(id: string, checked: boolean): void;
    _activeMetrics(): {
        distanceKm: number;
        departure: number | null;
        arrival: number | null;
        durationSec: number | null;
        preview: boolean;
    };
    _durationText(sec: number | null): string;
    _panelControlKey(el: Element | null): string;
    _capturePanelUiState(): {
        details: {
            key: any;
            open: any;
        }[];
        scrollTop: number;
        focus: PanelFocusState | null;
    } | null;
    _restorePanelUiState(state: PanelUiState | null): void;
    searchStationFromInput(): void;
    searchPlaceFromInput(): void;
    renderPanel(): void;
    _updateHeader(): void;
    _setHint(text: string, busy?: boolean): void;
    cancelRouteCalculation(): boolean;
    _error(err: unknown): void;
    _showTransientAlert(level: unknown, text: unknown): void;
    _shortTimingErrors(report: ValidationReport | null | undefined): {
        id?: string;
        level: string;
        code: string;
        message: string;
        data?: unknown;
    }[];
    _reportCanProceedToValidation(report: ValidationReport | null | undefined): boolean;
    _clearUnusedShortTimingOverride(ver: ScheduleVersion): void;
    _confirmForceShortTiming(issues: ValidationReport['issues']): Promise<unknown>;
    validateAndSave(): Promise<boolean>;
    _confirmValidationSummary(issues: ValidationReport['issues']): Promise<unknown>;
    _renderValidationSummary(issues: ValidationReport['issues']): void;
    _autosaveSoon(): void;
    _autosave(): void;
    renderList(): void;
    _duplicateScheduleDialog(id: unknown): void;
    _deleteScheduleFromList(id: unknown): void;
}
export default ScheduleV2Editor;
type __S3Struct277 = {
    "lat": number;
    "lon": number;
    "name": string;
};
type __S3Struct278 = {
    "name": string;
};
