type AnyRecord = Record<string, any>;
import type { RailWeatherState } from './weather-thresholds.js';
import { WeatherMapView } from './weather-map-view.js';
type WeatherEffect = {
    speedMult: number;
    icon: string;
    label: string;
    color: string;
};
type WmoWeather = {
    type: string;
    desc: string;
};
type WeatherPointState = RailWeatherState & {
    label?: string;
    live?: boolean;
    apparentTemp?: number;
    windDirection?: number;
    pressure?: number;
    cloudCover?: number;
    dewpoint?: number;
    risk?: unknown;
    lat?: number;
    lon?: number;
};
type PointQueueItem = {
    key: string;
    lat: number;
    lon: number;
    ts: number;
};
type PointCacheEntry = {
    state: WeatherPointState;
    expiresAt: number;
};
type ForecastRow = Record<string, unknown>;
type ForecastCacheEntry = {
    rows: ForecastRow[];
    expiresAt: number;
};
type GridCacheEntry = {
    points: WeatherPointState[];
    expiresAt: number;
};
export declare class Weather {
    current: string;
    temperature: number;
    windSpeed: number;
    windGust: number;
    humidity: number;
    precipitation: number;
    rain: number;
    showers: number;
    snowfall: number;
    cloudCover: number;
    cloudLow: number;
    cloudMid: number;
    cloudHigh: number;
    pressure: number;
    apparentTemp: number;
    windDirection: number;
    visibility: number;
    uvIndex: number;
    dewpoint: number;
    season: string;
    locationName: string;
    _lastFetchTime: number;
    _fetchCooldown: number;
    _lastLat: number;
    _lastLon: number;
    _fetchInProgress: boolean;
    _liveDataAvailable: boolean;
    _wmoDescription: string;
    weatherCode: number;
    _mapView: WeatherMapView | null;
    _forecastCache: Map<string, ForecastCacheEntry>;
    _gridCache: Map<string, GridCacheEntry>;
    radarTimestamps: string[];
    radarHost: string;
    cloudTimestamps: string[];
    _lastRadarFetch: number;
    _radarFetchCooldown: number;
    _pointCache: Map<string, PointCacheEntry>;
    _pointFetchQueue: PointQueueItem[];
    _maxPointCache: number;
    _pointCooldown: number;
    _pointFetchTimer: number | null;
    _effects: Record<string, WeatherEffect>;
    _wmoMapping: Record<number, WmoWeather>;
    _lastForecast: ForecastRow[];
    private _observationGeneration;
    private _historicalReplay;
    constructor();
    /**
     * Update weather — fetches live data from Open-Meteo API.
     */
    update(timeOfDay: unknown, dateStr: string, lat: number, lon: number): void;
    _fetchLiveWeather(lat: number, lon: number): Promise<void>;
    _fetchRadarTimestamps(): Promise<void>;
    getLatestRadarPath(): string | null;
    getLatestCloudPath(): string | null;
    getRadarTileUrl(path: unknown): string | null;
    getCloudTileUrl(path: unknown): string;
    _fallbackWeather(): void;
    getSpeedMultiplier(): number;
    _pointKey(lat: number, lon: number): string;
    _globalPointState(): {
        type: string;
        temperature: number;
        apparentTemp: number;
        humidity: number;
        windSpeed: number;
        windGust: number;
        windDirection: number;
        precipitation: number;
        rain: number;
        showers: number;
        snowfall: number;
        pressure: number;
        visibility: number;
        visibilityM: number;
        cloudCover: number;
        dewpoint: number;
        weatherCode: number;
        label: string;
        live: boolean;
    };
    getAt(lat: number, lon: number): {
        type: string;
        temperature: number;
        apparentTemp: number;
        humidity: number;
        windSpeed: number;
        windGust: number;
        windDirection: number;
        precipitation: number;
        rain: number;
        showers: number;
        snowfall: number;
        pressure: number;
        visibility: number;
        visibilityM: number;
        cloudCover: number;
        dewpoint: number;
        weatherCode: number;
        label: string;
        live: boolean;
    } | WeatherPointState;
    _queuePointFetch(lat: number, lon: number): void;
    _processPointFetchQueue(): Promise<void>;
    _fetchLiveWeatherFor(lat: number, lon: number): Promise<{
        type: string;
        temperature: number;
        apparentTemp: number;
        humidity: number;
        windSpeed: number;
        windGust: number;
        windDirection: number;
        precipitation: number;
        rain: number;
        showers: number;
        snowfall: number;
        rain6hMm: number;
        rain24hMm: number;
        snowDepthCm: number;
        pressure: number;
        cloudCover: number;
        visibility: number;
        visibilityM: number;
        dewpoint: number;
        weatherCode: number;
        label: string;
        live: boolean;
    }>;
    /** Returns the local weather effects at a lat/lon for a train:
     *  - speedCap: an absolute km/h cap to subtract for snow (MET-06)
     *  - brakeFactor: multiplier on deceleration (lower = brake earlier)
     *  - speedMult: multiplier on top speed (kept for display)
     *  - type: weather type
     */
    getSpeedEffectsAt(lat: number, lon: number, trainSpeedKmh?: number): {
        type: string;
        speedCap: number;
        brakeFactor: number;
        speedMult: number;
        label: string;
        risk: import("./weather-thresholds.js").RailWeatherEvaluation;
    };
    getRailRiskAt(lat: number, lon: number, trainSpeedKmh?: number): import("./weather-thresholds.js").RailWeatherEvaluation;
    _normalizeHourlyForecast(hourly?: Record<string, unknown>): AnyRecord[];
    getForecast(): ForecastRow[];
    fetchForecastAt(lat: number, lon: number): Promise<AnyRecord[]>;
    searchLocation(query: unknown): Promise<any>;
    fetchGrid(bounds: Record<string, unknown>, layer?: string, cols?: number, rows?: number): Promise<AnyRecord[]>;
    getThresholdCatalog(): Record<string, import("./weather-thresholds.js").WeatherThreshold>;
    getRailLevels(): import("./weather-thresholds.js").WeatherRailLevel[];
    getDisplay(): {
        icon: string;
        label: string;
        color: string;
        speedPct: number;
        temperature: number;
        apparentTemp: number;
        season: any;
        humidity: number;
        windSpeed: number;
        windGust: number;
        windDirection: number;
        precipitation: number;
        rain: number;
        showers: number;
        snowfall: number;
        cloudCover: number;
        cloudLow: number;
        cloudMid: number;
        cloudHigh: number;
        pressure: number;
        visibility: number;
        uvIndex: number;
        dewpoint: number;
        weatherCode: number;
        railRisk: import("./weather-thresholds.js").RailWeatherEvaluation;
        live: boolean;
    };
    _windDirLabel(deg: unknown): string;
    _seasonLabel(): any;
    renderWidget(): string;
    render(container: unknown, game?: unknown): void;
    toSave(): {
        current: string;
        temperature: number;
        season: string;
        humidity: number;
        windSpeed: number;
        windGust: number;
        windDirection: number;
        precipitation: number;
        rain: number;
        showers: number;
        snowfall: number;
        cloudCover: number;
        pressure: number;
        apparentTemp: number;
        visibility: number;
        uvIndex: number;
        dewpoint: number;
        cloudLow: number;
        cloudMid: number;
        cloudHigh: number;
        locationName: string;
        wmoDescription: string;
        weatherCode: number;
        liveDataAvailable: boolean;
        _lastLat: number;
        _lastLon: number;
        pointObservations: {
            key: string;
            state: {
                [key: string]: unknown;
                precipitation?: number;
                rain?: number;
                snowfall?: number;
                rain6hMm?: number;
                precipitation6h?: number;
                rain24hMm?: number;
                precipitation24h?: number;
                snowDepthCm?: number;
                windSpeed?: number;
                windGust?: number;
                visibilityM?: number;
                visibility?: number;
                temperature?: number;
                weatherCode?: number;
                humidity?: number;
                type?: string;
                label?: string;
                live?: boolean;
                apparentTemp?: number;
                windDirection?: number;
                pressure?: number;
                cloudCover?: number;
                dewpoint?: number;
                risk?: unknown;
                lat?: number;
                lon?: number;
            };
            expiresAt: number;
        }[];
    };
    loadFromSave(s: Record<string, unknown>): void;
}
export {};
