import { type RailSectionDirection } from './rail-section-geometry.js';
type LatLon = {
    lat: number;
    lon: number;
};
type StationLike = Partial<LatLon> & {
    id?: string | number;
    stationId?: string | number;
    name?: string;
    label?: string;
};
type StationSnapshot = LatLon & {
    id: string;
    name: string;
    snapLat?: number;
    snapLon?: number;
};
type GeometryPoint = LatLon & {
    segmentIndex?: number | null;
};
type OsmSnapshot = Record<string, unknown> & {
    geometry?: GeometryPoint[];
    ref?: string;
    name?: string;
    maxSpeed?: number | null;
    maxSpeedSource?: string;
    maxSpeedForward?: number | null;
    maxSpeedBackward?: number | null;
    electrified?: boolean | null;
    electrifiedMode?: string;
    voltage?: unknown[];
    frequency?: unknown[];
    gauge?: unknown[];
    loadingGauge?: string;
    axleLoad?: number | null;
    metreLoad?: number | null;
    tracks?: number;
    trafficMode?: string;
    usage?: string;
    service?: string;
    railway?: string;
    preferredDirection?: string;
    bidirectional?: string | boolean;
    oneway?: string | boolean;
    trackRef?: string;
    tags?: Record<string, unknown>;
};
type TrackBinding = Partial<LatLon> & {
    snapLat?: number;
    snapLon?: number;
    wayId?: string | number;
    trackRef?: string;
    displayName?: string;
    segmentIndex?: number | null;
    osmSnapshot?: OsmSnapshot;
};
type RailRoutePoint = LatLon & Record<string, unknown>;
type WorksZone = {
    id: string;
    name: string;
    autoName: boolean;
    startStation: StationSnapshot | null;
    endStation: StationSnapshot | null;
    startBinding: TrackBinding | null;
    endBinding: TrackBinding | null;
    constraints: TrackBinding[];
    route: RailRoutePoint[];
    segments: unknown[];
    distanceKm: number;
    impact: string;
    speedLimit: number;
    direction: RailSectionDirection;
    manual: boolean;
    error: string;
};
type WorksForm = {
    name: string;
    startDate: string;
    endDate: string;
    startTime: string;
    endTime: string;
    recurrence: string;
    daysOfWeek: number[];
    scope: string;
    station: StationSnapshot | null;
    affectsTraffic: boolean;
    stationImpact: string;
    stationSpeedLimit: number;
};
type TileMapLike = {
    setNetworkEnabled?(enabled: boolean): void;
    satelliteEnabled: boolean;
    railEnabled: boolean;
    zoomLevel: number;
    centerLat: number;
    centerLon: number;
    viewportWidth: number;
    viewportHeight: number;
    minZoom?: number;
    maxZoom?: number;
    isDirty?: boolean;
    applyZoom(delta: number, x: number, y: number): void;
    pan(dx: number, dy: number): void;
    markDirty?(): void;
    clearDirty?(): void;
    _updateFrameCache?(): void;
    screenToWorld(x: number, y: number, w: number, h: number): LatLon;
    latLonToPixel(lat: number | undefined, lon: number | undefined): {
        x: number;
        y: number;
    };
    renderTiles(ctx: CanvasRenderingContext2D, w: number, h: number): void;
} & Record<string, unknown>;
type WorldLike = Record<string, unknown> & {
    stations?: StationLike[] | Record<string, StationLike>;
    stationsById?: Record<string, StationLike>;
    prefetchRailNetworkNearStation?(st: StationLike, radiusKm: number): Promise<unknown>;
};
type WorksManagerLike = {
    add(data: Record<string, unknown>): unknown;
    getAll(): unknown[];
    getZones(work: unknown): Array<{
        route: RailRoutePoint[];
    }>;
};
type GameLike = Record<string, unknown> & {
    orm: unknown;
    world: WorldLike;
    renderer?: {
        tileMap?: TileMapLike;
    };
    worksManager: WorksManagerLike;
    scheduleV2?: Record<string, unknown>;
    _currentDate?: string;
    saveState(): void;
};
type UiLike = {
    renderIncidentsPage(): void;
};
type RouterSnapshot = {
    routePoints: RailRoutePoint[];
    segments: unknown[];
    distanceKm: number;
};
type RouteLike = RailRoutePoint[] & {
    _resolvedAnchors?: TrackBinding[];
};
type RouterLike = {
    routeBetweenBindings(start: TrackBinding, end: TrackBinding, constraints: TrackBinding[], options: Record<string, unknown>): Promise<RouteLike>;
    snapshotRoute(route: unknown): RouterSnapshot;
};
type EngineOsmCache = {
    key: string;
    ways: unknown[];
    switches: unknown[];
};
export declare class WorksV2Editor {
    game: GameLike;
    ui: UiLike;
    router: RouterLike;
    tileMap: TileMapLike;
    zones: WorksZone[];
    activeZoneId: string;
    mode: string;
    busy: boolean;
    dragging: boolean;
    panning: boolean;
    panThresholdPx: number;
    dragStartX: number;
    dragStartY: number;
    dragX: number;
    dragY: number;
    _routeGeneration: number;
    _routeAbortController: AbortController | null;
    _raf: number;
    _lastRenderAt: number;
    _engineOsmVisible: boolean;
    _engineOsmStreamTimer: number;
    _engineOsmRenderCache: EngineOsmCache;
    _stationStreamTimer: number;
    _stationStreamPromise: Promise<unknown> | null;
    _stationStreamKey: string;
    _stationStreamLastAttempt: number;
    _onWorksKeyDown: (e: KeyboardEvent) => void;
    overlay: HTMLElement;
    canvas: HTMLCanvasElement;
    ctx: CanvasRenderingContext2D;
    panelWrap: HTMLElement;
    panel: HTMLElement;
    form: WorksForm;
    constructor(game: GameLike, ui: UiLike);
    _cursorDistancePxToCandidate(...args: unknown[]): unknown;
    _exactTrackBinding(...args: unknown[]): Promise<TrackBinding | null>;
    _engineOsmViewportBounds(...args: unknown[]): unknown;
    _drawEngineOsm(...args: unknown[]): unknown;
    _drawStations(...args: unknown[]): unknown;
    _nearestStation(...args: unknown[]): StationLike | null;
    _queueVisibleEngineOsm(...args: unknown[]): unknown;
    _streamVisibleEngineOsm(...args: unknown[]): unknown;
    showWorldOsmStatus(...args: unknown[]): unknown;
    reloadWorldOsmVisible(...args: unknown[]): unknown;
    _setHint(t: unknown, busy?: boolean): void;
    _routingOptions(extra?: Record<string, unknown>): any;
    _ensureOverlay(): void;
    _bind(): void;
    _beginMapPointer(e: MouseEvent): boolean;
    _moveMapPointer(e: MouseEvent): boolean;
    _endMapPointer(e: MouseEvent): false | "click" | "pan";
    _cancelMapPointer(): boolean;
    isOpen(): boolean;
    _adoptMainViewport(): boolean;
    open(): void;
    close(): void;
    _zoom(d: number): void;
    _resize(): void;
    _scheduleDrawLoop(): void;
    _setStatus(t: unknown, busy?: boolean): void;
    _active(): WorksZone | null;
    _newZone(): WorksZone;
    addZone(): void;
    armStationOnly(): void;
    deleteZone(): void;
    armVia(): void;
    toggleManual(): void;
    resetAuto(): Promise<void>;
    removeLastVia(): Promise<void>;
    _prefetchStation(st: StationLike | null): Promise<boolean>;
    _selectEndpointStation(st: StationLike | null, side: 'start' | 'end'): Promise<boolean>;
    _autoZoneName(z: WorksZone | null): void;
    _sameWayMicroRoute(z: WorksZone | null): RouteLike | null;
    _handleMapClick(e: MouseEvent): Promise<void>;
    _chooseBinding(lat: number, lon: number, title: string): Promise<TrackBinding | null>;
    _recompute(z: WorksZone): Promise<boolean>;
    searchStationFromInput(): Promise<void>;
    searchPlaceFromInput(): void;
    _updateEngineOsmButton(): void;
    toggleEngineOsm(): void;
    renderPanel(): void;
    _readPanel(): void;
    _bindPanel(): void;
    save(): Promise<void>;
    _drawRoute(route: RailRoutePoint[], color: string, width?: number, alpha?: number): void;
    _drawAnchor(b: TrackBinding | StationSnapshot | null | undefined, color: string, r?: number): void;
    draw(): void;
    _error(err: unknown): void;
}
export {};
