type ProgressCallback = ((progress: {
    indexed: number;
    total: number;
    count?: number;
    added?: number;
    enriched?: number;
}) => void) | null;
type BuiltInBaseline = {
    name: string;
    lat: number;
    lon: number;
    platforms: number;
    type: string;
    country: string;
    facilities: string[];
    lineIds: string[];
    platformNames: string[];
    closed: boolean;
    uicRef: string;
    ref: string;
    operator: string;
    network: string;
    wikidata: string;
    wheelchair: string;
    source: string;
    siteKind: string;
    cargoTags: string[];
    official: boolean;
};
type ReferenceStationInput = {
    id?: string;
    name?: string;
    lat?: number;
    lon?: number;
    country?: string;
    uicRef?: string;
    ref?: string;
    operator?: string;
    network?: string;
    wikidata?: string;
    wheelchair?: string;
    osmType?: string;
    osmId?: string;
    type?: string;
    platforms?: number;
    facilities?: string[];
    source?: string;
    siteKind?: string;
    cargoTags?: string[];
    official?: boolean;
};
type StationOverrides = Partial<{
    name: string;
    lat: number;
    lon: number;
    platforms: number;
    type: string;
    platformNames: string[];
    closed: boolean;
}>;
type SavedWorldNativeRef = {
    id?: string;
    n?: string;
    la?: number;
    lo?: number;
    u?: string;
    r?: string;
    o?: string;
    nw?: string;
    t?: string;
    c?: string;
    f?: string[];
    sk?: string;
    src?: string;
    ct?: string[];
    of?: boolean;
};
type SavedWorldData = {
    _v?: unknown;
    builtInRemoved?: string[];
    nativeRefs?: SavedWorldNativeRef[];
    stations?: __KPStruct10[];
    tracks?: unknown[];
};
type __KPStruct10 = {
    id: string;
    n?: string;
    la: number;
    lo: number;
    p?: number;
    t?: string;
    c?: string;
    f?: string[];
    li?: string[];
    pn?: string[];
    cl?: boolean;
    rs?: string;
    bi?: boolean;
    name?: string;
    lat?: number;
    lon?: number;
    platforms?: number;
    type?: string;
    country?: string;
    facilities?: string[];
    lineIds?: string[];
    platformNames?: string[];
    closed?: boolean;
    referenceSourceId?: string;
};
type ReferenceStation = ReferenceStationInput & {
    id: string;
    lat: number;
    lon: number;
    type?: string;
    _count?: number;
    _playableView?: Station;
    _reMercLat?: number;
    _reMercLon?: number;
    _reMercX?: number;
    _reMercY?: number;
};
type RailRoutePoint = {
    lat: number;
    lon: number;
    [key: string]: unknown;
};
type RailNetworkLike = {
    ready?: () => unknown | Promise<unknown>;
    stats?: () => Record<string, unknown>;
    prepared?: boolean;
    ensureNear?: (lat: number, lon: number, radiusKm: number) => unknown[] | Promise<unknown[]>;
};
export declare class Station {
    id: string;
    name: string;
    lat: number;
    lon: number;
    platforms: number;
    type: string;
    platformNames: string[];
    cargo: unknown[];
    facilities: string[];
    country: string;
    lineIds: string[];
    closed: boolean;
    referenceSourceId?: string;
    osmNativeId?: string;
    osmType?: string;
    osmId?: string;
    uicRef?: string;
    ref?: string;
    operator?: string;
    network?: string;
    wikidata?: string;
    wheelchair?: string;
    source?: string;
    siteKind?: string;
    cargoTags?: string[];
    official?: boolean;
    _builtInRailNet?: boolean;
    _nativeOSM?: boolean;
    _fromWorldReference?: boolean;
    _reMercLat?: number;
    _reMercLon?: number;
    _reMercX?: number;
    _reMercY?: number;
    constructor(data: unknown, name?: string, lat?: number, lon?: number, platforms?: unknown, type?: string);
}
export declare class Track {
    id: string;
    stationA: string;
    stationB: string;
    distance: number;
    maxSpeed: number;
    electrified: boolean;
    name: string;
    route: RailRoutePoint[];
    worksActive: boolean;
    worksImpact: string | null;
    worksSpeedLimit: number | null;
    tracks: number;
    _incidentIds?: string[];
    incidentActive?: boolean;
    incidentEffect?: string | null;
    incidentSpeedLimit?: number | null;
    incidentName?: string | null;
    _bbox?: [number, number, number, number];
    constructor(input: unknown);
}
export { haversineDistance as haversine } from './simulation.js?v=1784250033';
export declare class World {
    stations: Station[];
    tracks: Track[];
    _stationMap: Map<string, Station>;
    _trackPairMap: Map<string, Track>;
    _stationSpatial: Map<string, Station[]>;
    _stationSpatialDirty: boolean;
    _stationSpatialCell: number;
    referenceStations: ReferenceStation[];
    _referenceStationMap: Map<string, ReferenceStation>;
    _referenceStationSpatial: Map<string, ReferenceStation[]>;
    _referenceStationSpatialCell: number;
    _referenceStationLod5: ReferenceStation[];
    _referenceStationLod1: ReferenceStation[];
    _builtInStationBaseline: Map<string, BuiltInBaseline>;
    _removedBuiltInStations: Set<string>;
    _builtInStationCount: number;
    railNetwork: RailNetworkLike | null;
    _railNetworkReadyPromise: Promise<RailNetworkLike | null> | null;
    constructor();
    setRailNetwork(network: unknown): RailNetworkLike | null;
    railNetworkReady(): Promise<RailNetworkLike | null>;
    getRailNetworkStats(): {
        [x: string]: unknown;
        prepared?: undefined;
        source?: undefined;
        loadedShards?: undefined;
        loadedWays?: undefined;
        totalShards?: undefined;
        coarseNodes?: undefined;
    } | {
        prepared: boolean;
        source: string;
        loadedShards: number;
        loadedWays: number;
        totalShards: number;
        coarseNodes: number;
    };
    getNativeRailWaysNear(lat: number, lon: number, radiusKm?: number): Promise<unknown[]>;
    prefetchRailNetworkNearStation(stationOrId: string, radiusKm?: number): Promise<unknown[]>;
    _rebuildStationMap(): void;
    _ensureStationSpatial(): void;
    getStationsNear(lat: number, lon: number, radiusKm?: number): Station[];
    getStationsInBounds(south: number, west: number, north: number, east: number): Station[];
    _referenceCellKey(lat: number, lon: number): string;
    clearReferenceStations(): void;
    _rebuildReferenceStationLod(): void;
    setReferenceStations(stations: unknown): number;
    setReferenceStationsAsync(stations: unknown, onProgress?: ProgressCallback, chunkSize?: number): Promise<number>;
    getReferenceStationById(id: string): ReferenceStation | null;
    getReferenceStationsInBounds(south: number, west: number, north: number, east: number): ReferenceStation[];
    getReferenceStationRenderCandidates(south: number, west: number, north: number, east: number, zoom?: number): ReferenceStation[];
    getReferenceStationsNear(lat: number, lon: number, radiusKm?: number): ReferenceStation[];
    _builtInBaselineFor(ref: ReferenceStationInput): BuiltInBaseline;
    _applyBuiltInBaseline(st: Station, id: string, b: BuiltInBaseline): Station;
    _createBuiltInFromBaseline(id: string, b: BuiltInBaseline): Station;
    _stationMatchesBuiltInBaseline(station: Station): boolean;
    setBuiltInGameplayStationsAsync(stations: unknown, onProgress?: ProgressCallback, chunkSize?: number): Promise<number>;
    _nativeStationNameKey(name: string): string;
    mergeNativeOSMGameplayStationsAsync(stations: unknown, onProgress?: ProgressCallback, chunkSize?: number): Promise<{
        added: number;
        enriched: number;
        total: number;
    }>;
    _trackPairKey(a: string, b: string): string;
    _rebuildTrackPairMap(): void;
    addStation(data: unknown): Station;
    removeStation(id: string): void;
    addTrack(data: unknown): Track;
    removeTrack(id: string): void;
    getStationById(id: string): Station | undefined;
    isReferenceStationActivated(id: string): boolean;
    activateReferenceStation(id: string, overrides?: StationOverrides): Station | null;
    getTrackBetween(stationAId: string, stationBId: string): Track | undefined;
    toSave(options?: {
        pinNativeStationIds?: Set<string> | string[];
    } | null): {
        builtInRemoved: string[];
        tracks: Record<string, unknown>[];
        _v: number;
        nativeRefs?: Record<string, unknown>[] | undefined;
        stations: Record<string, unknown>[];
    };
    loadFromSave(data: SavedWorldData): void;
}
export declare function createDefaultWorld(): World;
