import {ScheduleCreator} from './js/schedule-creator.js';
import {ScheduleV2Manager,ScheduleState,ScheduledLocation,TrackBinding,TrainCategory,StopCode} from './js/schedule-v2-model.js';
import {RotationV2Manager,FormationRole,RotationActionType} from './js/rotation-v2-model.js';
import {ScheduleV2Runtime} from './js/schedule-v2-runtime.js';
function game(){const scheduleV2=new ScheduleV2Manager(),rotationV2=new RotationV2Manager(scheduleV2);const world={stations:[{id:'A',name:'A',lat:48,lon:2},{id:'B',name:'B',lat:48.1,lon:2.1},{id:'C',name:'C',lat:48.2,lon:2.2}],getStationById(id){return this.stations.find(s=>s.id===id)||null;}};const g={scheduleV2,rotationV2,world,scheduleCreator:new ScheduleCreator(),realismSettings:{physics:1}};g.scheduleV2Runtime=new ScheduleV2Runtime(g);return g;}
function L(id,s,arr,dep){return new ScheduledLocation({id,stationId:s,name:s,track:new TrackBinding({wayId:id,displayName:'1',lat:s==='A'?48:s==='B'?48.1:48.2,lon:s==='A'?2:s==='B'?2.1:2.2,snapLat:s==='A'?48:s==='B'?48.1:48.2,snapLon:s==='A'?2:s==='B'?2.1:2.2}),arrivalSec:arr,departureSec:dep,dwellSec:arr!=null&&dep!=null?600:0,stopCode:StopCode.C,arrivalOverride:arr!=null,departureOverride:dep!=null});}
const g=game(),rec=g.scheduleV2.createDraft({number:'LC',category:TrainCategory.PASSENGER}),v=rec.currentVersion;v.locations=[L('a','A',null,3600),L('b','B',4200,4800),L('c','C',5400,null)];v.outboundPath.legs=[['a','b',48,2,48.1,2.1],['b','c',48.1,2.1,48.2,2.2]].map(([a,b,la,lo,lb,lob],i)=>({id:'l'+i,fromLocationId:a,toLocationId:b,constraintIds:[],routePoints:[{lat:la,lon:lo,wayId:a,maxSpeed:120,electrified:false},{lat:lb,lon:lob,wayId:b,maxSpeed:120,electrified:false}],segments:[],distanceKm:20}));v.outboundPath.routePoints=[...v.outboundPath.legs[0].routePoints,v.outboundPath.legs[1].routePoints[1]];v.state=ScheduleState.VALID;
const old=g.rotationV2.addVehicle({number:'OLD',category:'locomotive',traction:'diesel',powerW:2e6,massKg:80000,location:{kind:'STATION',id:'B',lat:48.1,lon:2.1}}),neu=g.rotationV2.addVehicle({number:'NEW',category:'locomotive',traction:'diesel',powerW:2e6,massKg:80000,location:{kind:'STATION',id:'B',lat:48.1,lon:2.1}}),coach=g.rotationV2.addVehicle({number:'C1',category:'voiture',massKg:40000,location:{kind:'STATION',id:'B',lat:48.1,lon:2.1}});const r=g.rotationV2.addRotation({name:'R'}),o=g.rotationV2.addOccurrence(r.id,{scheduleId:rec.id,versionId:v.id,formation:{members:[{vehicleId:old.id,role:FormationRole.LEAD},{vehicleId:coach.id,role:FormationRole.COACH}]}});g.rotationV2.addAction(r.id,{type:RotationActionType.CHANGE_LOCOMOTIVE,occurrenceId:o.id,locationOccurrenceId:'b',vehicleIds:[neu.id],durationSec:300});g.rotationV2.recalculateRotation(r.id);
const sid=`v2:${r.id}:${o.id}:2026-08-31`;const now=Math.floor(Date.now()/1000);g.scheduleV2Runtime.loadFromSave({schemaVersion:3,capturedAtUnixSec:now,busyVehicles:[],services:[{id:sid,rotationId:r.id,occurrenceId:o.id,baseDate:'2026-08-31',state:'moving',currentStopIndex:2,position:{lat:48.15,lon:2.15},speed:80,delay:0,stateIndex:1,stateProgress:.5,vehicleIds:[neu.id,coach.id],formationMembers:[{vehicleId:neu.id,role:FormationRole.LEAD},{vehicleId:coach.id,role:FormationRole.COACH}],train:{speed:80,delay:0,state:'moving'}}]});
// 01:25 = 5100 sec, between B and C. old loco intentionally not at origin A.
g.scheduleV2Runtime.sync(85,'2026-08-31');console.log('services',g.scheduleCreator.services.length,'ids',g.scheduleCreator.services[0]?._v2VehicleIds,'alerts',g.scheduleV2Runtime.alerts.map(a=>a.code));
