import {ScheduleV2Manager,ScheduleState,ScheduledLocation,TrackBinding,TrainCategory,StopCode} from './js/schedule-v2-model.js';
import {RotationV2Manager,FormationRole,RotationActionType} from './js/rotation-v2-model.js';
import {ScheduleCreator} from './js/schedule-creator.js';import {ScheduleV2Runtime} from './js/schedule-v2-runtime.js';
const sm=new ScheduleV2Manager(),rm=new RotationV2Manager(sm);const world={stations:[{id:'A',name:'A',lat:48,lon:2},{id:'B',name:'B',lat:48.1,lon:2.1},{id:'C',name:'C',lat:48.2,lon:2.2}],getStationById(id){return this.stations.find(s=>s.id===id)}};const game={scheduleV2:sm,rotationV2:rm,world,scheduleCreator:new ScheduleCreator(),realismSettings:{physics:1}};game.scheduleV2Runtime=new ScheduleV2Runtime(game);globalThis.window={game};
const rec=sm.createDraft({number:'T1',name:'T',category:TrainCategory.FREIGHT,maxSpeed:100});const v=rec.currentVersion;v.locations=[
 new ScheduledLocation({id:'a',order:0,stationId:'A',name:'A',track:new TrackBinding({displayName:'1',lat:48,lon:2,snapLat:48,snapLon:2}),departureSec:3600,stopCode:StopCode.C}),
 new ScheduledLocation({id:'b',order:1,stationId:'B',name:'B',track:new TrackBinding({displayName:'1',lat:48.1,lon:2.1,snapLat:48.1,snapLon:2.1}),arrivalSec:4200,departureSec:4800,dwellSec:600,stopCode:StopCode.S,arrivalOverride:true,departureOverride:true}),
 new ScheduledLocation({id:'c',order:2,stationId:'C',name:'C',track:new TrackBinding({displayName:'1',lat:48.2,lon:2.2,snapLat:48.2,snapLon:2.2}),arrivalSec:5400,stopCode:StopCode.C,arrivalOverride:true})];
const mkpts=(x,y)=>[{lat:x.lat,lon:x.lon,wayId:'w',maxSpeed:100},{lat:y.lat,lon:y.lon,wayId:'w',maxSpeed:100}];const p1=mkpts(world.stations[0],world.stations[1]),p2=mkpts(world.stations[1],world.stations[2]);v.outboundPath.routePoints=[...p1,...p2.slice(1)];v.outboundPath.legs=[{id:'l1',fromLocationId:'a',toLocationId:'b',constraintIds:[],routePoints:p1,segments:[{wayId:'w',maxSpeed:100}],distanceKm:10},{id:'l2',fromLocationId:'b',toLocationId:'c',constraintIds:[],routePoints:p2,segments:[{wayId:'w',maxSpeed:100}],distanceKm:10}];v.outboundPath.segments=v.outboundPath.legs.flatMap(l=>l.segments);v.state=ScheduleState.VALID;
const loco=rm.addVehicle({number:'L',category:'locomotive',traction:'diesel',massKg:80000,powerW:2e6,maxSpeed:120,lengthM:20,location:{kind:'STATION',id:'A',lat:48,lon:2}});const coach=rm.addVehicle({number:'C',category:'coach',traction:'none',massKg:40000,maxSpeed:160,lengthM:26,location:{kind:'STATION',id:'A',lat:48,lon:2}});const rot=rm.addRotation({name:'R'});const occ=rm.addOccurrence(rot.id,{scheduleId:rec.id,versionId:v.id,formation:{members:[{vehicleId:loco.id,role:FormationRole.LEAD},{vehicleId:coach.id,role:FormationRole.COACH}]}});rm.addAction(rot.id,{type:RotationActionType.DETACH,occurrenceId:occ.id,locationOccurrenceId:'b',vehicleIds:[coach.id],durationSec:300});
const plan=game.scheduleV2Runtime.planRotationForDate(rot,'2026-08-31')[0];plan._relNow=3600;game.scheduleV2Runtime._compile(plan);const svc=game.scheduleCreator.services[0];console.log('compiled',!!svc,svc?._v2FormationMembers.map(x=>x.vehicleId));
const stop=svc.stops[1];game.scheduleV2Runtime._beginActionsAtStop(svc,plan,stop,4200,false);console.log('at arrival',svc._v2FormationMembers.map(x=>x.vehicleId),svc._v2OperationState);game.scheduleV2Runtime._tickOperationState(svc,plan,4499);console.log('before end',svc._v2FormationMembers.map(x=>x.vehicleId),coach.available);game.scheduleV2Runtime._tickOperationState(svc,plan,4500);console.log('after end',svc._v2FormationMembers.map(x=>x.vehicleId),coach.available,coach.location);
