import test from 'node:test';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
const root=process.env.RE_BASE||path.resolve(import.meta.dirname,'../..');
const mod=n=>import(pathToFileURL(path.join(root,'js',n+'.js')));

const {Bank}=await mod('bank');const {Economy}=await mod('economy');
function ui(bank,e){const buttons=Object.keys(bank.interestRates).map(type=>({dataset:{type},addEventListener(_,fn){this.click=fn;}}));const container={innerHTML:'',querySelectorAll:()=>buttons};bank.render(container,{economy:e,saveState(){}});return{container,buttons};}
function dialogs(fn){const a=globalThis.alert,c=globalThis.confirm;const messages=[];globalThis.alert=x=>messages.push(x);globalThis.confirm=()=>true;try{return fn(messages);}finally{globalThis.alert=a;globalThis.confirm=c;}}
test('RC6R-BANK-01: borrowing at the exact principal ceiling succeeds from the real rendered button',()=>{const b=new Bank(),e=new Economy();e.balance=20000000;b.startingBalance=20000000;const {buttons}=ui(b,e);dialogs(messages=>{buttons.find(x=>x.dataset.type==='mega').click();assert.equal(b.loans.length,1);assert.equal(e.balance,30000000);assert.equal(messages.length,0);});});
test('RC6R-BANK-02: displayed button state agrees with principal not interest',()=>{const b=new Bank(),e=new Economy();b.startingBalance=20000000;const {container}=ui(b,e);const btn=container.innerHTML.match(/<button[^>]*data-type="mega"[^>]*>/)[0];assert.ok(!btn.includes('not-allowed'));assert.ok(!/\bdisabled(?:[\s=>])/.test(btn));});
test('RC6R-BANK-03: rendering an unopened bank previews the same initial ceiling as borrow',()=>{const b=new Bank(),e=new Economy();e.balance=2000000;const {container}=ui(b,e);const btn=container.innerHTML.match(/<button[^>]*data-type="medium"[^>]*>/)[0];assert.match(btn,/\bdisabled/);assert.equal(b.startingBalance,null,'render does not redefine the starting balance');dialogs(()=>ui(b,e).buttons.find(x=>x.dataset.type==='medium').click());assert.equal(b.loans.length,0);});
test('RC6R-BANK-04: reaching maxLoans disables additional borrowing in UI and engine',()=>{const b=new Bank(),e=new Economy();b.maxLoans=1;assert.ok(b.borrow(e,'small'));const {container}=ui(b,e);assert.ok([...container.innerHTML.matchAll(/<button[^>]*data-type="[^"]+"[^>]*>/g)].every(x=>/\bdisabled/.test(x[0])));assert.equal(b.borrow(e,'small'),null);});
test('RC6R-BANK-05: over-ceiling rejected without account mutations',()=>{const b=new Bank(),e=new Economy();b.startingBalance=2000000;const before=JSON.stringify(e.toSave());dialogs(()=>ui(b,e).buttons.find(x=>x.dataset.type==='large').click());assert.equal(b.loans.length,0);assert.equal(JSON.stringify(e.toSave()),before);});
test('RC6R-BANK-06: null starting balance remains uninitialized after save roundtrip',()=>{const b=new Bank();b.loadFromSave(JSON.parse(JSON.stringify(new Bank().toSave())));assert.equal(b.startingBalance,null);const e=new Economy();e.balance=2000000;assert.equal(b.borrow(e,'mega'),null);assert.equal(b.getCreditLimit(e.balance),1000000);});
test('RC6R-BANK-07: final loan instalment settles the remaining debt, not an imported underpayment',()=>{const b=new Bank(),e=new Economy();b.loadFromSave({loans:[{id:'old',remaining:1000,daysLeft:1,dailyPayment:1,principal:1000,rate:0}]});const balance=e.balance;b.processDailyRepayments(e,'2026-09-11');assert.equal(e.balance,balance-1000);assert.equal(b.getTotalDebt(),0);});
test('RC6R-BANK-08: repeated repayment date stays idempotent after restore',()=>{const b=new Bank(),e=new Economy();b.borrow(e,'small');b.processDailyRepayments(e,'2026-09-11');const balance=e.balance;const c=new Bank();c.loadFromSave(b.toSave());c.processDailyRepayments(e,'2026-09-11');assert.equal(e.balance,balance);});
