import test from 'node:test';
import assert from 'node:assert/strict';
import {htmlText,htmlJsString,htmlJsValue} from '../html-text.js';
import {UI} from '../ui.js';
import {Rame} from '../rame.js';
import {Dashboard} from '../dashboard.js';
import {SeasonalSchedule} from '../seasonal.js';
import {RotationV2Editor} from '../rotation-v2-editor.js';
const payload=`PE & Évry "O'Brian" <img data-re-injection src=x onerror="globalThis.__reInjected=1">`;
function host(){return{innerHTML:'',value:'',options:[],replaceChildren(...xs){this.options=xs;},appendChild(x){this.options.push(x);},querySelectorAll:()=>[],querySelector:()=>null,addEventListener(){},classList:{add(){},remove(){}},style:{}};}
function dom(run){const old=globalThis.document,oldOption=globalThis.Option,els=new Map();globalThis.Option=class{constructor(text,value){this.text=text;this.value=value;}};globalThis.document={createElement:()=>host(),getElementById:id=>{if(!els.has(id))els.set(id,host());return els.get(id);},querySelectorAll:()=>[],querySelector:()=>null};try{return run(els);}finally{globalThis.document=old;globalThis.Option=oldOption;}}
function ui(){const u=Object.create(UI.prototype);u._animateSolari=()=>{};u.game={engine:{getParisTime:()=>({hours:10,minutes:0})},world:{getStationById:()=>({id:'A',name:payload})},depotManager:{getAll:()=>[{id:'D',name:payload}]},scheduleCreator:{services:[]},rameManager:{getAll:()=>[]}};return u;}
const clean=(s)=>{assert.ok(!/<img\s+data-re-injection/i.test(s),s.slice(0,1500));assert.ok(s.includes('&lt;img data-re-injection'),s.slice(0,1500));};
test('RC11-HTML01 text and quoted attributes escape all five metacharacters, keeping the original model',()=>{assert.equal(htmlText(`<>&"'`),'&lt;&gt;&amp;&quot;&#39;');assert.equal(htmlText(null),'');assert.equal(htmlText(0),'0');assert.equal(htmlText(false),'false');const x={name:payload};htmlText(x.name);assert.equal(x.name,payload);assert.equal(htmlText('A &amp; B'),'A &amp;amp; B');});
test('RC11-HTML02 inline JS string contents cannot terminate either parser or interpolate template expressions',()=>{
 for(const value of [payload,`');globalThis.__reInjected=1;//`,String.raw`x\');alert(1);//`,'${globalThis.__reInjected=1}','\n\r\0\u2028\u2029','`</script><script>globalThis.__reInjected=1</script>']){
  const encoded=htmlJsString(value);assert.ok(!/[<>"'`&$\n\r]/.test(encoded));assert.equal(Function('return "'+encoded+'"')(),value);assert.equal(Function("return '"+encoded+"'")(),value);assert.equal(Function('return `'+encoded+'`')(),value);
 }assert.equal(globalThis.__reInjected,undefined);
});
test('RC11-HTML03 full inline arguments are data rather than executable fragments',()=>{for(const x of [payload,22,true,null,Infinity]){const encoded=htmlJsValue(x).replaceAll('&quot;','"');assert.equal(Function('return '+encoded)(),x===Infinity?null:x);}assert.equal(globalThis.__reInjected,undefined);});
test('RC11-HTML04 rame cards protect names, instance names, serial numbers and the home depot',()=>dom(els=>{const u=ui(),r=new Rame({id:'R',name:payload,serialNumber:payload,depotId:'D',elementDetails:[{name:payload,instanceName:payload,category:'locomotive',length:20,power:1000,mass:80}]});u.game.rameManager.getAll=()=>[r];u.renderRamesList();const s=els.get('rames-list').innerHTML;clean(s);assert.ok(s.includes('rame-card'));assert.ok(!s.includes('&amp;lt;img'));assert.equal(r.name,payload);}));
test('RC11-HTML05 rolling-stock names, notes and titles cannot break their surrounding card',()=>dom(els=>{const u=ui(),item={id:'R',name:payload,seriesName:payload,notes:payload,category:'locomotive',traction:'diesel',maxSpeed:120,length:20,tonnage:80,power:1000,cargoTypes:[],passengerCapacity:0,freightCapacity:0};u.game.rollingStock={items:[item],getAll:()=>[item]};u.renderStockList();clean(els.get('rolling-stock-list')?.innerHTML||els.get('stock-list')?.innerHTML||'');}));
const train={svcId:'S',name:payload,trainNumber:payload,seriesName:payload,origin:payload,destination:payload,servedStations:[payload],fromStations:[payload],depTime:600,arrTime:610,delay:1,delayReason:payload,platform:'1',voie:payload,isDeparture:true,isArrival:true,category:'voyageur'};
for(const method of ['_renderSncfDep','_renderSncfArr','_renderOldSncf','_renderCATI3_3','_renderAFLDepart','_renderAFLArrivee','_renderCATIComplet','_renderCATIAr','_renderDbAbfahrt'])test('RC11-HTML Infogare '+method+' renders station/train/destination/reason as text',()=>{const u=ui();const s=u[method]({id:'A',name:payload},[train],'10:00');clean(s);assert.ok(!s.includes('&amp;lt;img'));assert.equal(train.name,payload);});
for(const method of ['_renderPlatformGL','_renderPlatformBanlieue'])test('RC11-HTML platform board '+method+' keeps every served station and train name inert',()=>{const u=ui();const svc={name:payload,train:{name:payload,seriesName:payload,number:payload},rame:{},stops:[]};const s=u[method](svc,{id:'A',name:payload},{id:'B',name:payload},[{name:payload,isLast:true}],600,'','10:00',5);clean(s);assert.ok(!s.includes('&amp;lt;img'));});
test('RC11-HTML station list, next stop and situation retain formatting without interpreting station names',()=>{const u=ui(),s={state:'moving',train:{delay:2,speed:60},stops:[{stationId:'A',type:'arret',departureTime:600,arrivalTime:600},{stationId:'B',type:'arret',departureTime:610,arrivalTime:610}],currentStopIndex:1};const x=u._buildLivemapPanelContent(s);clean(x.rows);clean(x.situation);clean(x.nextHtml);assert.ok(x.situation.includes('<b>'));});
test('RC11-HTML rotation status labels are encoded exactly once',()=>{const ed=Object.create(RotationV2Editor.prototype);const s=ed._rv63StatusHtml({key:'ok',label:payload},true);clean(s);assert.ok(!s.includes('&amp;lt;img'));});
test('RC11-HTML schedule grouping by route cannot reintroduce an unescaped station alias',()=>dom(els=>{const u=ui();globalThis.document.getElementById('sched-sort').value='route';globalThis.document.getElementById('schedules-sort').value='route';u.game.scheduleCreator.services=[{id:'S',name:payload,stops:[{stationId:'A',departureTime:600,arrivalTime:600,type:'arret'},{stationId:'B',departureTime:620,arrivalTime:620,type:'arret'}],train:{},active:true}];u.game.rameManager.getById=()=>({name:payload});u.renderSchedulesList();const all=[...els.values()].map(x=>x.innerHTML).join('');clean(all);}));
test('RC11-HTML seasonal schedule list protects persisted service names',()=>{const m=new SeasonalSchedule(),h=host();m.render(h,{scheduleCreator:{services:[{id:'S',name:payload,stops:[],active:true}]},saveState(){}});clean(h.innerHTML);});

test('RC11-HTML21 a custom cargo key is text even inside a nested capacity summary',()=>dom(els=>{const u=ui(),r=new Rame({id:'R',name:'Cargo',elementDetails:[{category:'wagon',freightCapacity:50,cargoTypes:[payload],mass:20,length:20}]});u.game.rameManager.getAll=()=>[r];u.renderRamesList();clean(els.get('rames-list').innerHTML);assert.equal(r.elementDetails[0].cargoTypes[0],payload);}));
