import test from 'node:test';import assert from 'node:assert/strict';
import {cloneEditableGraph,prepareEditableClone,incrementLabel,LabelAllocator,duplicatedTrainName} from '../duplicate-tools.js';
import {ScheduleV2Manager,ScheduleRecord,ScheduleState,RoundTripGroup} from '../schedule-v2-model.js';
function record(number='001',name='Train 001') {const rec=new ScheduleRecord({number,name,versions:[{locations:[{stationId:'B',departureSec:3600},{stationId:'K',arrivalSec:5400}],outboundPath:{routePoints:[{lat:50.123456789,lon:7.123456789,meta:{x:1}},{lat:51.1,lon:6.9}],segments:[]},state:ScheduleState.VALID}]});return rec;}
for(const [input,delta,expected] of [['Rame 009',1,'Rame 010'],['ICE 099 A',2,'ICE 101 A'],['000099999999999999999',2,'000100000000000000001'],['Navette',1,'Navette']])test(`RC20 increment ${input}`,()=>assert.equal(incrementLabel(input,delta),expected));
test('RC20 names without digits acquire a free numeric suffix',()=>assert.equal(new LabelAllocator(['Navette','Navette 2']).next('Navette'),'Navette 3'));
test('RC20 numbering skips collisions without changing parity',()=>assert.equal(new LabelAllocator(['003','005']).claim('003',2),'007'));
test('RC20 explicit train number in name follows actual allocated number',()=>assert.equal(duplicatedTrainName('ICE 001 – Rhône','001','007',2,new LabelAllocator([])),'ICE 007 – Rhône'));
test('RC20 unrelated numeric suffix in train name follows frequency +2',()=>assert.equal(duplicatedTrainName('Navette 009','1001','1003',2,new LabelAllocator([])),'Navette 011'));
test('RC20 clone retains prototypes, aliases, cycles, independent arrays and Map/Set',()=>{class A{get value(){return this.x;}}const a=new A();a.x=7;a.list=[{p:1}];a.alias=a.list[0];a.self=a;a.m=new Map([['x',a.alias]]);a.s=new Set([a.alias]);a.d=new Date(123);const b=cloneEditableGraph(a);assert.ok(b instanceof A);assert.equal(b.value,7);assert.equal(b.self,b);assert.equal(b.list[0],b.alias);assert.equal(b.m.get('x'),b.alias);assert.equal([...b.s][0],b.alias);assert.notEqual(b.alias,a.alias);b.alias.p=8;assert.equal(a.alias.p,1);assert.equal(b.d.getTime(),123);});
test('RC20 clone __proto__ key stays an inert own property',()=>{const a=JSON.parse('{"__proto__":{"injected":true}}');const b=cloneEditableGraph(a);assert.equal(Object.getPrototypeOf(b),Object.prototype);assert.equal(b.injected,undefined);assert.equal(b.__proto__.injected,true);});
test('RC20 frequency does not serialize the whole network or source routes',()=>{const m=new ScheduleV2Manager(),r=record();m.schedules.push(r);m.toSave=()=>{throw Error('Network serialization forbidden');};r.toJSON=()=>{throw Error('Lossy route serialization forbidden');};const copies=m.duplicateScheduleFrequency(r.id,{intervalSec:600,totalCount:4});assert.equal(copies.length,3);assert.deepEqual(copies.map(x=>x.number),['003','005','007']);assert.deepEqual(copies.map(x=>x.name),['Train 003','Train 005','Train 007']);assert.deepEqual(copies.map(x=>x.currentVersion.firstDepartureSec),[4200,4800,5400]);assert.ok(copies[0] instanceof ScheduleRecord);});
test('RC20 duplicate preserves sub-microdegree positions and isolated nested geometry',()=>{const m=new ScheduleV2Manager(),r=record();m.schedules.push(r);const c=m.duplicateSchedule(r.id);const p=c.currentVersion.outboundPath.routePoints[0];assert.equal(p.lat,50.123456789);p.meta.x=42;p.lat=12;assert.equal(r.currentVersion.outboundPath.routePoints[0].lat,50.123456789);assert.equal(r.currentVersion.outboundPath.routePoints[0].meta.x,1);});
test('RC20 batch failure at third copy leaves existing live objects untouched',()=>{const m=new ScheduleV2Manager(),r=record();m.schedules.push(r);const real=m.duplicateSchedule;let n=0;m.duplicateSchedule=function(...args){if(++n===3)throw Error('injected');return real.apply(this,args);};assert.throws(()=>m.duplicateScheduleFrequency(r.id,{intervalSec:60,totalCount:6}),/injected/);assert.equal(m.schedules.length,1);assert.equal(m.schedules[0],r);assert.equal(m._batchNumbers,null);});
test('RC20 independent version/stop/path IDs do not retain source binding IDs',()=>{const m=new ScheduleV2Manager(),r=record();m.schedules.push(r);const c=m.duplicateSchedule(r.id);assert.notEqual(c.id,r.id);assert.notEqual(c.currentVersion.id,r.currentVersion.id);assert.notEqual(c.currentVersion.locations[0].id,r.currentVersion.locations[0].id);assert.notEqual(c.currentVersion.outboundPath.id,r.currentVersion.outboundPath.id);});
test('RC20 roundtrip collision shifts both numbers, preserves their +1 pairing',()=>{const m=new ScheduleV2Manager(),out=record('001','Train 001'),ret=record('002','Train 002');ret.currentVersion.locations[0].stationId='K';ret.currentVersion.locations[0].departureSec=6000;ret.currentVersion.locations[1].stationId='B';ret.currentVersion.locations[1].arrivalSec=7800;m.schedules.push(out,ret,record('004','Reserved'));const g=new RoundTripGroup({outboundScheduleId:out.id,returnScheduleId:ret.id,terminalLayoverSec:300});m.roundTrips.push(g);const made=m.duplicateRoundTrip(g.id,{intervalSec:3600,horizonSec:3600});assert.equal(made[0].outbound.number,'005');assert.equal(made[0].return.number,'006');});
test('RC20 name label collision never changes the train number embedded in it',()=>assert.equal(duplicatedTrainName('Train 001','001','003',2,new LabelAllocator(['Train 003'])),'Train 003 (2)'));

test('RC20 prepared clone shares no mutable nodes between results, preserves internal aliases',()=>{class Model{get ok(){return this.point.x;}}const root=new Model();root.point={x:1};root.alias=root.point;root.self=root;root.m=new Map([[root.point,root]]);root.s=new Set([root.point]);root.date=new Date(777);const make=prepareEditableClone(root),a=make(),b=make();assert.ok(a instanceof Model);assert.equal(a.self,a);assert.equal(a.point,a.alias);assert.equal(a.m.get(a.point),a);assert.equal([...a.s][0],a.point);a.point.x=9;assert.equal(b.ok,1);assert.equal(root.ok,1);assert.equal(b.date.getTime(),777);});
test('RC20 prepared clone captures primitive values and topology at batch preparation',()=>{const a={n:1,child:{v:2}},make=prepareEditableClone(a);a.n=9;a.child.v=7;a.child={v:10};const b=make();assert.deepEqual(b,{n:1,child:{v:2}});});
test('RC20 both clone paths preserve sparse arrays and extra own properties safely',()=>{const a=new Array(3);a[2]={v:1};a.label='test';Object.defineProperty(a,'__proto__',{value:{injected:true},enumerable:true});for(const b of[cloneEditableGraph(a),prepareEditableClone(a)()]){assert.equal(0 in b,false);assert.equal(b.label,'test');assert.equal(Object.getPrototypeOf(b),Array.prototype);assert.equal(b.injected,undefined);assert.equal(b.__proto__.injected,true);assert.notEqual(a[2],b[2]);}});
test('RC20 batch clone plan is released on completion and error',()=>{const m=new ScheduleV2Manager(),r=record();m.schedules.push(r);const copies=m.duplicateScheduleFrequency(r.id,{intervalSec:60,totalCount:4});assert.equal(m._batchClones,null);copies[0].currentVersion.outboundPath.routePoints[0].meta.x=9;assert.equal(copies[1].currentVersion.outboundPath.routePoints[0].meta.x,1);assert.equal(r.currentVersion.outboundPath.routePoints[0].meta.x,1);});
test('RC20 purely descriptive train names remain unchanged',()=>assert.equal(duplicatedTrainName('Dijon → Lyon','1001','1003',2,new LabelAllocator(['Dijon → Lyon'])),'Dijon → Lyon'));
test('RC20 batch graph clone preserves all canonical geometry and physical constraints over 50 profiles',()=>{for(let n=0;n<50;n++){const m=new ScheduleV2Manager(),points=Array.from({length:10+n},(_,i)=>({lat:50.123456789+i*1e-7,lon:7.234567891+i*2e-7,wayId:'W'+(i%3),maxSpeed:80+n,voltage:[15000,25000],frequency:[16.7,50],tags:{incline:(i%4)+'%',custom:{n}}}));const r=new ScheduleRecord({number:'1001',name:'Train 1001',versions:[{state:ScheduleState.VALID,locations:[],outboundPath:{legs:[{routePoints:points}]}}]});m.schedules.push(r);const made=m.duplicateScheduleFrequency(r.id,{intervalSec:60,totalCount:4});for(const c of made){assert.deepEqual(c.currentVersion.outboundPath.routePoints,r.currentVersion.outboundPath.routePoints);assert.deepEqual(c.currentVersion.outboundPath.segments,r.currentVersion.outboundPath.segments);}made[0].currentVersion.outboundPath.legs[0].routePoints[0].tags.custom.n=999;assert.equal(made[1].currentVersion.outboundPath.legs[0].routePoints[0].tags.custom.n,n);assert.equal(r.currentVersion.outboundPath.legs[0].routePoints[0].tags.custom.n,n);}});
