import test from 'node:test';import assert from 'node:assert/strict';
import {Economy} from '../economy.js';import {Dashboard} from '../dashboard.js';import {Bank} from '../bank.js';
import {financePage,financialCSV} from '../financial-panel.js';import {chartWindow,zoomChartWindow} from '../dashboard-chart.js';
const view=()=>({page:0,query:'',type:'',from:'',to:''});
function eco(){globalThis.window={game:{engine:{getSimulationEpochMs:()=>1700000000000}}};return new Economy();}
test('RC19 finance: 1,500 mixed transactions survive write and read intact',()=>{const e=eco();for(let i=0;i<500;i++){e.addRevenue(30,'fret','R'+i);e.addExpense(10,'exploitation','E'+i);e.addPenalty(2,'P'+i);}assert.equal(e.history.length,1500);const restored=new Economy();restored.loadFromSave(JSON.parse(JSON.stringify(e.toSave())));assert.deepEqual(restored.history,e.history);assert.equal(restored.balance,50000000000+500*18);assert.equal(restored.penalties,1000);});
test('RC19 finance: a transaction is timestamped with simulated time during replay',()=>{const e=eco();e.addRevenue(1,'fret','x');assert.equal(e.history[0].time,1700000000000);});
test('RC19 finance: more than thirty daily balances survive save/load',()=>{const e=eco();for(let i=0;i<65;i++){e.processDailyCharges([],[],new Date(Date.UTC(2026,0,1+i)).toISOString().slice(0,10));e.addRevenue(i+1,'fret','day');}assert.equal(e.dailySnapshots.length,64);const f=eco();f.loadFromSave(e.toSave());assert.deepEqual(f.dailySnapshots,e.dailySnapshots);});
test('RC19 finance: legacy truncation is disclosed and new saves retain that warning',()=>{const e=eco();const raw=e.toSave();delete raw.historyVersion;const f=eco();f.loadFromSave(raw);assert.equal(f.historyInheritedTruncation,true);const g=eco();g.loadFromSave(f.toSave());assert.equal(g.historyInheritedTruncation,true);assert.equal(e.historyInheritedTruncation,false);});
test('RC19 finance: save output does not alias individual history rows',()=>{const e=eco();e.addRevenue(1,'fret','original');const saved=e.toSave();e.history[0].amount=99;assert.equal(saved.history[0].amount,1);});
test('RC19 finance: pagination and filters never discard journal rows',()=>{const e=eco();for(let i=0;i<1055;i++)e.addRevenue(1,'fret','train '+i);const before=JSON.stringify(e.history);const a=financePage(e.history,view());assert.equal(a.count,1055);assert.equal(a.rows.length,100);assert.equal(a.rows[0].description,'train 1054');assert.equal(financePage(e.history,{...view(),page:10}).rows.length,55);assert.equal(financePage(e.history,{...view(),page:999}).page,10);assert.equal(financePage(e.history,{...view(),query:'train 1000'}).count,1);assert.equal(JSON.stringify(e.history),before);});
test('RC19 finance: date/type filters operate on all history including old pages',()=>{const history=[{time:Date.parse('2026-01-01T00:00Z'),type:'expense'},{time:Date.parse('2026-02-01T00:00Z'),type:'revenue'}];assert.equal(financePage(history,{...view(),from:'2026-02-01',type:'revenue'}).count,1);assert.equal(financePage(history,{...view(),to:'2026-01-01'}).count,1);});
test('RC19 finance: CSV includes all rows, quotes text and neutralises formula descriptions',()=>{const e=eco();e.addRevenue(1,'fret','="test"; injection');const csv=financialCSV(e.history);assert.ok(csv.startsWith('\uFEFF'));assert.ok(csv.includes(`"'=""test""; injection"`));assert.ok(csv.includes('2023-11-14T22:13:20.000Z'));});
test('RC19 finance: a loan does not trim the journal or inflate operating revenue',()=>{const e=eco(),b=new Bank();for(let i=0;i<600;i++)e.addRevenue(1,'fret','x');b.startingBalance=e.balance;const keys=Object.getOwnPropertyNames(Bank.prototype);const method=keys.find(x=>/^(takeLoan|borrow)$/.test(x));assert.ok(method,keys.join(','));const before=e.revenue;const result=b[method](e,'small');assert.ok(result);assert.ok(e.history.length>600);assert.equal(e.revenue,before);});
test('RC19 finance: dashboard retains revenue and expenditure beyond rolling UI limit',()=>{const e=eco(),d=new Dashboard();let epoch=Date.parse('2026-01-01T00:00Z');const game={economy:e,engine:{getParisTime:()=>({hours:0,minutes:0}),getParisDate:()=>new Date(epoch).toISOString().slice(0,10),getSimulationEpochMs:()=>epoch},scheduleCreator:{getActiveServices:()=>[]},rameManager:{getAll:()=>[]}};for(let i=0;i<600;i++){epoch+=300000;e.addRevenue(2,'fret','x');e.addExpense(1,'charge','x');d.record(game);}assert.equal(d.revenueHistory.length,600);assert.equal(d.expenseHistory.length,600);assert.equal(d.punctualityHistory.length,288);const f=new Dashboard();f.loadFromSave(d.toSave());assert.deepEqual(f.expenseHistory,d.expenseHistory);assert.deepEqual(f.revenueHistory,d.revenueHistory);});
test('RC19 finance: old unknown expenditure samples are not fabricated zeroes',()=>{const d=new Dashboard();d.loadFromSave({punctualityHistory:[],passengerHistory:[],kmHistory:[],revenueHistory:[{time:'old',value:12}]});assert.deepEqual(d.expenseHistory,[{time:'old',value:null}]);});
test('RC19 chart: dragging bounds and zoom cannot mutate numeric financial values',()=>{assert.deepEqual(chartWindow(10,-10,500),[0,9]);assert.deepEqual(chartWindow(0,12,15),[0,0]);assert.deepEqual(zoomChartWindow(101,0,100,50,.5),[25,75]);assert.deepEqual(zoomChartWindow(101,25,75,50,2),[0,100]);});
