import test from 'node:test';
import assert from 'node:assert/strict';
import { makeGame, addValidSchedule, addDieselFormation } from './re-rc2-fixtures.mjs';
import { ActiveService, ServiceStop } from '../schedule-creator.js';
import { RotationAction, FormationRole, FormationMember, RotationV2Manager } from '../rotation-v2-model.js';
import { ScheduleV2Manager, ScheduledLocation, ScheduleState, TrackBinding } from '../schedule-v2-model.js';
import { PlatformManager } from '../line.js';
import { Unions } from '../unions.js';
import { Economy } from '../economy.js';
import { StationUpgrades } from '../station-upgrades.js';
import { SeededRng, setGlobalRng } from '../rng.js';
import { UI } from '../ui.js';
import { ScheduleV2Editor } from '../schedule-v2-editor.js';
const day='2026-08-16', next='2026-08-17';
function withGame(game, fn) {const prev=globalThis.window;globalThis.window={game};try{return fn();}finally{if(prev===undefined)delete globalThis.window;else globalThis.window=prev;}}
function fixture(){const g=makeGame(),rec=addValidSchedule(g),rot=g.rotationV2.addRotation({name:'RC2'}),{loco,occ}=addDieselFormation(g,rot,rec);g.platformManager=new PlatformManager();g.economy=new Economy();g.scheduleV2Runtime.sync(1429,day);return{g,rec,rot,loco,occ,svc:g.scheduleCreator.services[0]};}
function terminal({operations=true}={}){const f=fixture(),{g,rot,occ,svc,loco}=f; if(operations)rot.actions.push(new RotationAction({type:'DETACH',occurrenceId:occ.id,locationOccurrenceId:'lb',durationSec:600,vehicleIds:[loco.id]}));svc._currentDate=next;svc.currentStopIndex=1;svc.state='moving';svc.train.state='moving';svc.position={lat:48.2,lon:2.2};return f;}
test('RC2-TERM-01: terminal detach retains the physical train and its platform until actual completion',()=>{
 const{g,svc}=terminal();withGame(g,()=>{svc.arriveAtStation(g.world.getStationById('B'),10,g.economy);assert.ok(svc._v2OperationState&&!svc._v2OperationState.completed);assert.equal(svc.completed,false);assert.equal(svc.state,'stopped_at_station');assert.ok(svc.position);assert.notEqual(g.platformManager.getPlatformForTrain('B',svc.id),null);assert.equal(g.platformManager.assignPlatform('B','second',2,svc.train.platform,{exactPreferred:true}),null);
 svc.scheduleTick(19,next,g.economy);assert.equal(svc.completed,false);assert.ok(svc.position);
 svc.scheduleTick(20,next,g.economy);assert.equal(svc._v2OperationState.completed,true);assert.equal(svc.completed,true);assert.equal(svc.position,null);assert.equal(g.platformManager.getPlatformForTrain('B',svc.id),null);});
});
test('RC2-TERM-02: a terminal without operations still despawns on arrival',()=>{const{g,svc}=terminal({operations:false});withGame(g,()=>{svc.arriveAtStation(g.world.getStationById('B'),10,g.economy);assert.equal(svc.completed,true);assert.equal(svc.position,null);});});
test('RC2-TERM-03: a failed terminal operation cannot be erased by completeService',()=>{const{g,svc}=terminal();withGame(g,()=>{svc.arriveAtStation(g.world.getStationById('B'),10,g.economy);svc._v2OperationState.failed=true;svc.completeService(g.economy);assert.equal(svc.completed,false);assert.ok(svc.position);});});
test('RC2-DEPOT-01: stopping at a station does not mark a rame as present in its home depot',()=>{const{g,svc}=fixture();svc.rame.depotId='HOME';svc._currentDate=next;svc.currentStopIndex=1;svc.stops.push(new ServiceStop('A','arret',1500,1498));svc.routes.push(svc.routes[0].slice().reverse());withGame(g,()=>{svc.arriveAtStation(g.world.getStationById('B'),10,g.economy);assert.equal(svc.rame.currentLocation.depotId,'');svc.scheduleTick(11,next,g.economy);assert.equal(svc.train.inDepot,false);assert.ok(svc.position);});});
test('RC2-PLAT-01: exact alphanumeric track labels do not become numeric fallbacks',()=>{for(const label of ['A','1 bis','V1M','Gleis A']){const pm=new PlatformManager();assert.equal(pm.assignPlatform('S','A',2,label,{exactPreferred:true}),label);assert.equal(pm.assignPlatform('S','B',2,label,{exactPreferred:true}),null);assert.equal(pm.getPlatformForTrain('S','A'),label);}});
test('RC2-PLAT-02: a stale assignment object is not proof of real platform ownership',()=>{const{g,svc}=fixture();g.platformManager.assignPlatform('B','other',2,'2',{exactPreferred:true});g.scheduleCreator.services.push({id:'other',active:true,state:'stopped_at_station',position:{lat:48.2,lon:2.2},train:{stoppedAt:{id:'B'}}});svc._platformAssignment={stationId:'B',platform:2,source:'PLATFORM_MANAGER'};svc.stops[1].platform='2';withGame(g,()=>assert.equal(svc._reserveArrivalResources(g.world.getStationById('B'),svc.stops[1]),false));});
function directFixture(){const sm=new ScheduleV2Manager(),rm=new RotationV2Manager(sm),l=rm.addVehicle({id:'L',number:'L001',category:'locomotive',traction:'diesel',massKg:80000,powerW:3000000,lengthM:20,maxSpeed:120});function add(number,start,end,calendarIds=[]){const r=sm.createDraft({number});r.currentVersion.locations=[new ScheduledLocation({id:'a'+number,stationId:'A',departureSec:start,dwellSec:0}),new ScheduledLocation({id:'b'+number,stationId:'B',arrivalSec:end,departureSec:end,dwellSec:0})];r.currentVersion.state=ScheduleState.VALID;r.currentVersion.calendarIds=calendarIds;const a=rm.setDirectAssignment(r.id,r.currentVersion.id,{members:[{vehicleId:l.id,role:FormationRole.LEAD}]},{rameId:'R'});return{r,a};}return{sm,rm,l,add};}
test('RC2-DIRECT-01: two overlapping simple assignments of the same vehicle conflict before departure',()=>{const{rm,add}=directFixture();add('1',36000,39600);add('2',36900,43200);const issues=rm.validateMaterialConflicts();assert.ok(issues.some(i=>i.code==='VEHICLE_DOUBLE_BOOKED'&&i.vehicleId==='L'));});
test('RC2-DIRECT-02: simple and real rotation assignments participate in the same conflict check',()=>{const{rm,add}=directFixture();const{r,a}=add('1',36000,39600);const second=add('2',36500,39000);rm.removeDirectAssignment(second.r.id);const rot=rm.addRotation({name:'Real'});const occ=rm.addOccurrence(rot.id,{scheduleId:second.r.id,versionId:second.r.currentVersion.id});occ.formation.members=[new FormationMember({vehicleId:'L',role:FormationRole.LEAD})];assert.ok(rm.validateMaterialConflicts().some(i=>i.code==='VEHICLE_DOUBLE_BOOKED'));});
test('RC2-DIRECT-03: exclusive calendar days do not falsely conflict in simple mode',()=>{const{sm,rm,add}=directFixture();sm.calendars.push({id:'MON',enabled:true,weekdays:[1]},{id:'TUE',enabled:true,weekdays:[2]});add('1',36000,39600,['MON']);add('2',36000,39600,['TUE']);assert.equal(rm.validateMaterialConflicts().filter(i=>i.code==='VEHICLE_DOUBLE_BOOKED').length,0);});
test('RC2-DIRECT-04: a 25-hour simple duty conflicts with its own following daily occurrence',()=>{const{rm,add}=directFixture();add('1',36000,126000);assert.ok(rm.validateMaterialConflicts().some(i=>i.code==='VEHICLE_DOUBLE_BOOKED'));});
test('RC2-DIRECT-05: a conflicting simple assignment is not advertised as READY',()=>{const{sm,rm,add}=directFixture();const{r}=add('1',36000,39600);add('2',36900,43200);const status=ScheduleV2Editor.prototype._operationalReadiness.call({game:{rotationV2:rm,scheduleV2:sm,realismSettings:{},rameManager:{getById:()=>({id:'R',name:'R'})}}},r,r.currentVersion);assert.notEqual(status.code,'READY_SIMPLE');assert.match(status.label,/CONFLIT/);});
const socialGame=eco=>({economy:eco,staffManager:{staff:[],getDailySalaryExpense:()=>120,getByRole:()=>[]},scheduleCreator:{getActiveServices:()=>[]}});
test('RC2-SOCIAL-01: a purchased social bonus survives next-day recomputation and save/load',()=>{const e=new Economy();e.balance=200000;const game=socialGame(e),u=new Unions();u.dailyUpdate(game,{random:()=>1},'2026-09-11');const before=u.satisfaction;assert.equal(u.negotiate(e,'bonus'),true);const save=JSON.parse(JSON.stringify(u.toSave()));const v=new Unions();v.loadFromSave(save);v.dailyUpdate(game,{random:()=>1},'2026-09-12');assert.equal(v.satisfaction,before+15);});
test('RC2-AR-01: reverse running times exclude station dwell, including midnight',()=>{const f=fixture(),s=f.svc;s._v2OccurrenceId='';s._returnStopsData=null;s.terminusWait=5;s.stops=[new ServiceStop('A','arret',1380,1380),new ServiceStop('B','arret',1412,1410),new ServiceStop('C','arret',2,0)];const out=s.buildReturnStops();const diff=(a,b)=>(b-a+1440)%1440;assert.equal(out[0].departureTime,5);assert.equal(diff(out[0].departureTime,out[1].arrivalTime),28);assert.equal(diff(out[1].departureTime,out[2].arrivalTime),30);});
test('RC2-AR-02: auto 24h generates rotations for a 23:00 to 00:30 journey',()=>{const old=globalThis.document;const els={'sched-terminus-wait':{value:'5'},'sched-multi-departures':{value:'unset'},'sched-round-trip':{checked:true}};globalThis.document={getElementById:id=>els[id]};try{UI.prototype._calcAutoAR.call({schedStops:[{depTimeMin:1380},{arrTimeMin:30}]});assert.equal(Number(els['sched-multi-departures'].value),7);}finally{globalThis.document=old;}});
test('RC2-UPGRADE-01: purchased parking and hall change boarding demand, without exceeding seats',()=>{const upgrade=new StationUpgrades(),eco=new Economy();eco.balance=100000;const run=()=>{setGlobalRng(new SeededRng(17));const s={rame:{totalCapacity:1000,maxSpeed:100,totalMass:80,elementDetails:[]},serviceType:'passager',currentStopIndex:0,stops:[{stationId:'A',type:'arret'},{stationId:'B',type:'arret'}],train:{},name:'Test'};withGame({stationUpgrades:upgrade},()=>eco.processStopRevenue(s,'A',0,true,false,'A',[]));return s._onboardPax;};const base=run();upgrade.buyModule('A','parking',eco);upgrade.buyModule('A','hall',eco);const after=run();assert.ok(after>base);assert.ok(Math.abs(after-base*1.15)<=1);assert.ok(after<=1000);});

test('RC2-TERM-04: adjusted stops retain material-operation minimum duration',()=>{const{svc}=fixture();svc.stops[1].v2OperationSec=600;assert.equal(svc._buildAdjustedStops()[1].v2OperationSec,600);});
test('RC2-PLAT-03: discovering twenty platforms does not duplicate a previously reserved exact 20',()=>{const pm=new PlatformManager();assert.equal(pm.assignPlatform('S','first',2,'20',{exactPreferred:true}),'20');assert.equal(pm.assignPlatform('S','second',20,'20',{exactPreferred:true}),null);for(let n=1;n<20;n++)assert.notEqual(pm.assignPlatform('S','other'+n,20,null),null);assert.equal(pm.assignPlatform('S','overflow',20,null),null);});
test('RC2-PLAT-04: V1, voie 1 and numeric 1 remain aliases, while V1M stays distinct',()=>{const pm=new PlatformManager();assert.equal(pm.assignPlatform('S','first',2,'V1',{exactPreferred:true}),1);assert.equal(pm.assignPlatform('S','second',2,'voie 1',{exactPreferred:true}),null);assert.equal(pm.assignPlatform('S','third',2,'V1M',{exactPreferred:true}),'V1M');});
test('RC2-DIRECT-06: inactive simple assignments are ignored when advanced rotations are required',()=>{const{rm,add}=directFixture();add('1',36000,39600);add('2',36900,43200);withGame({realismSettings:{rotationsRequired:true}},()=>assert.equal(rm.validateMaterialConflicts().filter(i=>i.code==='VEHICLE_DOUBLE_BOOKED').length,0));});

test('RC2-DIRECT-07: list-row readiness reuses supplied conflict validation rather than repeating it',()=>{const{sm,rm,add}=directFixture();const{r}=add('1',36000,39600);add('2',36900,43200);const conflicts=rm.validateMaterialConflicts();let calls=0;rm.validateMaterialConflicts=()=>{calls++;return conflicts;};const status=ScheduleV2Editor.prototype._operationalReadiness.call({game:{rotationV2:rm,scheduleV2:sm,realismSettings:{},rameManager:{getById:()=>({id:'R'})}}},r,r.currentVersion,conflicts);assert.equal(status.code,'MATERIAL_CONFLICT');assert.equal(calls,0);});
