import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const root=process.env.RE_BASE||path.resolve(import.meta.dirname,'../..');
const {ActiveService,cantonManager}=await import(pathToFileURL(path.join(root,'js/schedule-creator.js')));
function fixture(fn){const old=globalThis.window;const services=Array.from({length:20},(_,i)=>({id:'s'+i,active:true,state:'moving',position:{lat:48,lon:2}}));const g={scheduleCreator:{services}};globalThis.window={game:g};const check=id=>ActiveService.prototype._isLiveResourceOwner.call({id:'observer'},id);const end=cantonManager.beginServiceLookupFrame(services);try{fn({services,g,check});}finally{end();if(old===undefined)delete globalThis.window;else globalThis.window=old;}}
test('RC8-OWNER-01: station occupancy queries share a tick index instead of full-fleet searches',()=>fixture(({services,check})=>{let finds=0;const find=services.find;services.find=function(...a){finds++;return find.apply(this,a);};for(let i=0;i<400;i++)assert.equal(check('s'+(i%20)),true);assert.equal(finds,0);}));
test('RC8-OWNER-02: cancellation and coordinate changes are read live',()=>fixture(({services,check})=>{assert.equal(check('s2'),true);services[2].cancelled=true;assert.equal(check('s2'),false);services[2].cancelled=false;services[2].state='waiting';services[2].position=null;assert.equal(check('s2'),false);services[2].position={lat:48,lon:2};assert.equal(check('s2'),true);}));
test('RC8-OWNER-03: same-length replacement cannot create a false vacant platform',()=>fixture(({services,check})=>{assert.equal(check('s2'),true);services[2]={id:'replacement',state:'moving'};assert.equal(check('replacement'),true);assert.equal(check('s2'),false);}));
test('RC8-OWNER-04: reordering addition deletion and renamed IDs are supported',()=>fixture(({services,check})=>{assert.equal(check('s2'),true);services.reverse();assert.equal(check('s2'),true);services.push({id:'new',state:'stopped_at_station'});assert.equal(check('new'),true);services[0].id='renamed';assert.equal(check('s19'),false);assert.equal(check('renamed'),true);services.splice(services.findIndex(x=>x.id==='s2'),1);assert.equal(check('s2'),false);}));
test('RC8-OWNER-05: replacing the authoritative fleet within a tick is respected',()=>fixture(({g,check})=>{assert.equal(check('s1'),true);g.scheduleCreator.services=[{id:'replacement',state:'moving'}];assert.equal(check('s1'),false);assert.equal(check('replacement'),true);}));
test('RC8-OWNER-06: legacy numeric IDs and string IDs keep resource compatibility',()=>fixture(({services,check})=>{services.push({id:123,state:'moving'});assert.equal(check('123'),true);assert.equal(check(123),true);}));
test('RC8-OWNER-07: invalid duplicate IDs fail closed while any physical owner remains',()=>fixture(({services,check})=>{services[5].active=false;assert.equal(check('s5'),false);services[0].id='s5';assert.equal(check('s5'),true);services[0].completed=true;assert.equal(check('s5'),false);}));
test('RC8-OWNER-08: physically blocked or broken trains keep their occupancy',()=>fixture(({services,check})=>{services[5].state='blocked_route';services[5].speed=0;assert.equal(check('s5'),true);services[5].position=null;assert.equal(check('s5'),false);}));
test('RC8-OWNER-09: tiny legacy worlds without coordinates preserve moving-owner protection',()=>fixture(({services,check})=>{services[5].position=null;assert.equal(check('s5'),true);services[5].state='stopped_at_station';assert.equal(check('s5'),true);services[5].state='preparing';assert.equal(check('s5'),false);}));
test('RC8-OWNER-10: scope finalization drops the identity maps and outside queries remain live',()=>{fixture(({check})=>assert.equal(check('s1'),true));assert.equal(cantonManager._serviceLookupFrame,null);const old=globalThis.window;globalThis.window={game:{scheduleCreator:{services:[{id:'outside',state:'moving'}]}}};try{assert.equal(ActiveService.prototype._isLiveResourceOwner.call({id:'observer'},'outside'),true);}finally{if(old===undefined)delete globalThis.window;else globalThis.window=old;}});
