import test from 'node:test';
import assert from 'node:assert/strict';
import {CantonManager} from '../simulation.js';
import {displayBlockSignals} from '../block-signal-view.js';
const route=(offset=0)=>Array.from({length:121},(_,i)=>({lat:48+offset+i*.001,lon:2,wayId:'rail',maxSpeed:60,maxSpeedSource:'OSM'}));
const svc=id=>({id,active:true,position:{lat:48,lon:2},state:'moving'});
const bounds={minLat:47,maxLat:50,minLon:1,maxLon:3};
function setup(){const m=new CantonManager(),r=route(),a=m.createRouteCantons(r),services=[svc('a'),svc('b')];globalThis.window={game:{scheduleCreator:{services,getActiveServices:()=>services}}};return {m,r,a,services};}
test('RC19 block: cleanup retains empty blocks that a cached route still uses',()=>{const {m,a}=setup();m.cleanup();assert.equal(m.cantons.size,a.length);assert.equal(m.occupy(a[1].cantonId,'a'),true);assert.equal(m.occupy(a[1].cantonId,'b'),false);});
test('RC19 block: a live route survives eviction from the route cache',()=>{const {m,a,services}=setup();services[0]._cantonAssignments=a;for(let i=1;i<=220;i++)m.createRouteCantons(route(i));m.cleanup();assert.ok(a.every(x=>m.cantons.has(x.cantonId)));});
test('RC19 block: unused route entries can still be reclaimed',()=>{const {m,a}=setup();m.routeCantons.clear();m.cleanup();assert.ok(a.every(x=>!m.cantons.has(x.cantonId)));});
test('RC19 block: occupancy rehydrates a table evicted before its service starts',()=>{const {m,a}=setup();m.routeCantons.clear();m.cleanup();assert.equal(m.syncFootprint('a',a,a[2].startKm+.02,750),true);assert.equal(m.syncFootprint('b',a,a[2].startKm+.02,750),false);});
test('RC19 block: a seven-hundred-fifty metre rear remains occupied after cleanup',()=>{const {m,a}=setup();m.syncFootprint('a',a,a[1].startKm+.1,750);m.cleanup();assert.equal(m.isAvailable(a[0].cantonId,'b'),false);m.syncFootprint('a',a,a[1].startKm+.8,750);assert.equal(m.isAvailable(a[0].cantonId,'b'),true);});
test('RC19 block: own reservation is clear rather than a yellow signal',()=>{const {m,a}=setup();m.reserve(a[1].cantonId,'a');assert.equal(m.getEntrySignalAspect(a,1,'a'),null);assert.equal(m.getEntrySignalAspect(a,1,'b'),0);});
test('RC19 block: red protects the next occupied block, yellow the block before',()=>{const {m,a}=setup();m.occupy(a[2].cantonId,'b');assert.equal(m.getEntrySignalAspect(a,1,'a'),30);assert.equal(m.getEntrySignalAspect(a,2,'a'),0);assert.equal(m.getEntrySignalAspect(a,3,'a'),null);});
test('RC19 block: display uses the block beyond the painted boundary',()=>{const {m,a,r,services}=setup();Object.assign(services[0],{_cantonAssignments:a,_state:{cachedRoute:r,index:0,progress:0}});m.occupy(a[2].cantonId,'b');const signals=displayBlockSignals(services,m,bounds);assert.equal(signals[0].lat,r[a[0].endIndex].lat);assert.equal(signals[0].aspect,30);assert.equal(signals[1].aspect,0);assert.equal(signals.length,a.length-1);});
test('RC19 block: off-screen cab does not erase its visible route signals',()=>{const {m,a,r,services}=setup();Object.assign(services[0],{_cantonAssignments:a,_state:{cachedRoute:r,index:0}});const visible={...bounds,minLat:r[a[3].endIndex].lat-.001,maxLat:r[a[3].endIndex].lat+.001};const signals=displayBlockSignals(services,m,visible);assert.ok(signals.length);assert.ok(signals.every(x=>x.lat>=visible.minLat&&x.lat<=visible.maxLat));});
test('RC19 block: passed signals are not cleared by their own occupying train',()=>{const {m,a,r,services}=setup();Object.assign(services[0],{_cantonAssignments:a,_state:{cachedRoute:r,index:a[1].startIndex+1}});m.occupy(a[1].cantonId,'a');assert.equal(displayBlockSignals(services,m,bounds)[0].aspect,0);});
test('RC19 block: duplicate same-route signals prefer the nearest approaching train',()=>{const {m,a,r,services}=setup();for(let i=0;i<2;i++)Object.assign(services[i],{_cantonAssignments:a,_state:{cachedRoute:r,index:i}});m.reserve(a[1].cantonId,'b');const list=displayBlockSignals(services,m,bounds);assert.equal(list.length,a.length-1);assert.equal(list[0].aspect,null);});
test('RC19 block: binary assignment lookup matches the original interval definition',()=>{const {m,a,r}=setup();for(let i=-1;i<=r.length+1;i++){assert.equal(m.getCantonForSegment(a,i),a.find(x=>i>=x.startIndex&&i<x.endIndex)||null);}});
test('RC19 block: indexed footprint matches linear compatibility at every boundary',()=>{const {m,a}=setup();for(const block of a)for(const delta of [-.000002,-.000001,0,.000001,.01]){const front=Math.max(0,block.startKm+delta);m.releaseAll('a');m.syncFootprint('a',a,front,750);const fast=[...m.getTrackedCantons('a')].sort();m.releaseAll('a');m.syncFootprint('a',a.map(x=>({...x})),front,750);assert.deepEqual([...m.getTrackedCantons('a')].sort(),fast);}});
test('RC19 block: releasing a leader clears the red while a stationary leader stays protected',()=>{const {m,a,services}=setup();m.occupy(a[1].cantonId,'b');services[1].state='waiting';assert.equal(m.getEntrySignalAspect(a,1,'a'),0);services[1].cancelled=true;assert.equal(m.getEntrySignalAspect(a,1,'a'),null);});

for(const mode of ['full','macro'])test(`RC19 real movement: ${mode} stops before a closed signal and restarts after release`,async()=>{
 const {fixture,cantonManager,tick}=await import('./helpers/rc10-fixtures.mjs');const {s,game}=fixture({speed:60});const r=route();s.routes=[r];s._initializeState(r,'rc19-'+mode);s._setRouteProgressKm(r,.01);s._cantonAssignments=cantonManager.createRouteCantons(r);
 const a=s._cantonAssignments,block=a[3],leader={id:'leader',active:true,state:'moving',position:{lat:r[block.startIndex].lat+.002,lon:2},speed:0,train:{speed:0},rame:{totalLength:100},_state:{cachedRoute:r,index:block.startIndex+2,progress:0}};game.scheduleCreator.services=[s,leader];cantonManager.occupy(block.cantonId,'leader');let prior=60;
 for(let i=0;i<2400;i++){if(i%100===0)cantonManager.cleanup();tick(s,mode,game,.1);assert.ok(prior-s.speed<1,'no instantaneous speed collapse');prior=s.speed;assert.ok(s._getRouteProgressKm(s.position,r,s._state.index)<block.startKm);}
 assert.equal(s.speed,0);assert.equal(s.train.movementAuthority.code,'CANTON_STOP');const stopped=s._getRouteProgressKm(s.position,r,s._state.index);assert.ok(block.startKm-stopped>.025);
 leader.cancelled=true;leader.position=null;game.scheduleCreator.services=[s];cantonManager.releaseAll('leader');for(let i=0;i<900;i++)tick(s,mode,game,.1);assert.ok(s.speed>20);assert.ok(s._getRouteProgressKm(s.position,r,s._state.index)>block.startKm);
});
