import test from 'node:test';import assert from 'node:assert/strict';
import {setup,flush,DepotManager} from './helpers/rc17-rescue-fixtures.mjs';
import {ActiveService,cantonManager} from './helpers/rc10-fixtures.mjs';
import {WorksManager} from '../works.js';import {samePhysicalMovement} from '../physical-service-identity.js';
import {validRescueMotion} from '../rescue-movement.js';import {VoiePointManager} from '../voie-points.js';
function work(f,impact,speedLimit=0){const w=f.game.worksManager=new WorksManager();w.add({id:'WORK',name:'Work',startDate:'2026-09-12',endDate:'2026-09-12',startTime:'00:00',endTime:'23:59',impact,speedLimit,zones:[{impact,speedLimit,route:f.r.route}]});w.update(f.world,'2026-09-12',600);return w;}
test('RC17 DDS04 outbound and return use genuine ActiveService integrator',async()=>{const f=await setup();assert.ok(f.controller() instanceof ActiveService);const origin={...f.r.position};f.tick(10);assert.notDeepEqual(f.r.position,origin);assert.ok(f.r.speed>0);await f.getToReturn();const c=f.controller();assert.equal(c.rame.totalLength,320);assert.equal(c.rame.totalMass,1084);assert.equal(c.rame.totalPower,2400);assert.equal(c.returning,true);assert.ok(c._carryoverCantonIds.size>0);for(let i=0;i<900&&f.r.state!=='done';i++)f.tick();assert.equal(f.r.state,'done',f.r.routeStatusMessage);assert.equal(f.rame.currentLocation.depotId,'D');assert.equal(f.manager.repairQueue.length,1);assert.equal(cantonManager.getTrackedCantons(f.r.id).size,0);});
for(const traction of ['diesel','electric'])test(`RC17 DDS04 closure holds ${traction} rescue, removing it releases movement`,async()=>{const f=await setup({traction,electrified:true});const w=work(f,'stop');const pos={...f.r.position};f.tick(30);assert.deepEqual(f.r.position,pos);assert.equal(f.r.speed,0);assert.match(f.r.routeStatusMessage,/travaux|voie|arrêt/i);w.works=[];w.revision++;f.tick(30);assert.notDeepEqual(f.r.position,pos);});
test('RC17 DDS04 5 km/h temporary limit applies to the locomotive',async()=>{const f=await setup();work(f,'slow',5);for(let i=0;i<25;i++){f.tick();assert.ok(f.r.speed<=5+1e-8);}assert.ok(f.controller().totalDistance>0);});
for(const [traction,electrified,blocked] of [['electric',false,true],['electric',true,false],['diesel',false,false]])test(`RC17 DDS04 ${traction}, energized=${electrified}: physics traction compatibility`,async()=>{const f=await setup({traction,electrified}),pos={...f.r.position};f.tick(20);if(blocked){assert.deepEqual(f.r.position,pos);assert.equal(f.r.speed,0);}else assert.notDeepEqual(f.r.position,pos);});
test('RC17 DDS04 diesel empty tank cannot power rescue departure',async()=>{const f=await setup(),c=f.controller();c.rame.consumables.fuelCapacityL=100;c.rame.consumables.fuelL=0;const pos={...f.r.position};f.tick(20);assert.deepEqual(f.r.position,pos);assert.equal(f.r.speed,0);c.rame.consumables.fuelL=100;f.tick(10);assert.notDeepEqual(f.r.position,pos);});
test('RC17 DDS04 unavailable physical stock holds instead of inventing acceleration',async()=>{const f=await setup({power:0});f.tick(50);assert.equal(f.r.speed,0);assert.match(f.r.routeStatusMessage,/caractéristiques/);});
test('RC17 DDS04 coupling authorizes only the immobilized rendezvous target',async()=>{const f=await setup();assert.equal(samePhysicalMovement(f.r.id,f.s.id),true);assert.equal(samePhysicalMovement(f.r.id,'THIRD'),false);f.s.speed=2;assert.equal(samePhysicalMovement(f.r.id,f.s.id),false);f.s.speed=0;f.s.position.lat+=.005;assert.equal(samePhysicalMovement(f.r.id,f.s.id),false);});
test('RC17 DDS04 a third train occupies the rescue canton and remains protected',async()=>{const f=await setup(),c=f.controller(),third={id:'THIRD',active:true,state:'stopped_at_station',position:{...f.r.position},speed:0,train:{length:750}};f.game.scheduleCreator.services.push(third);const ids=cantonManager.getTrackedCantons(c.id);assert.ok(ids.size>0);const id=[...ids][0];cantonManager.release(id,c.id);cantonManager.occupy(id,third.id);const before={...f.r.position};f.tick(10);assert.deepEqual(f.r.position,before);assert.equal(f.r.speed,0);assert.equal(cantonManager.cantons.get(id).occupiedBy,third.id);});
test('RC17 DDS04 ordinary train sees genuine rescue occupancy, not a vanished owner',async()=>{const f=await setup(),c=f.controller();const id=[...cantonManager.getTrackedCantons(c.id)][0];assert.equal(cantonManager._isTrainGone(c.id),false);assert.ok(cantonManager.cantons.get(id));assert.equal(cantonManager.occupy(id,'THIRD'),false);assert.equal(cantonManager.cantons.get(id).occupiedBy,c.id);});
test('RC17 DDS04 physical identity changes atomically at coupling, retaining rear approach',async()=>{const f=await setup();const targetIds=[...cantonManager.getTrackedCantons(f.s.id)];assert.ok(targetIds.length>0);await f.getToReturn();const c=f.controller();for(const id of targetIds){assert.equal(cantonManager.cantons.get(id)?.occupiedBy,c.id);}assert.equal(cantonManager.getTrackedCantons(f.s.id).size,0);assert.ok(c._carryoverCantonIds.size>0);});
test('RC17 DDS04 movement snapshot restores position, efforts and retained locks without a jump',async()=>{const f=await setup();await f.getToReturn();f.tick(7);const pos={...f.r.position},c=f.controller(),state=c.snapshot(),save=JSON.parse(JSON.stringify(f.manager.toSave()));f.manager.loadFromSave(save);const restored=f.manager.activeRescues[0];assert.equal(cantonManager._isTrainGone(restored.id),false,'loading is not disappearance');const v=new VoiePointManager();assert.equal(v._isDeadInterlockingOwner(restored.id),false);const c2=f.controller();assert.deepEqual(restored.position,pos);assert.equal(c2._tractiveEffort,state.tractiveEffort);assert.equal(c2._brakeEffort,state.brakeEffort);assert.equal(c2.totalDistance,state.distance);assert.deepEqual(c2._carryoverCantonIds,new Set(state.carryover));f.tick(1);assert.notDeepEqual(restored.position,pos);});
for(const key of ['progress','speed','tractiveEffort','carryover','tronconExits'])test(`RC17 DDS04 malformed snapshot ${key} cannot silently lose footprint`,async()=>{const f=await setup();f.tick(5);const save=JSON.parse(JSON.stringify(f.manager.toSave())),raw=save.activeRescues[0].movementSnapshot;raw[key]=key==='carryover'?'bad':key==='tronconExits'?[[null,3]]:-1;assert.equal(validRescueMotion(raw),null);f.manager.loadFromSave(save);const r=f.manager.activeRescues[0],before={...r.position};f.tick(30);assert.deepEqual(r.position,before);assert.match(r.routeStatusMessage,/sauvegardé invalide/);});

test('RC17 DDS04 a 750 m target keeps approach locks under its full 770 m coupled footprint',async()=>{const f=await setup();f.rame.totalLength=750;f.s.train.length=750;f.s._syncCantonFootprint();await f.getToReturn();const c=f.controller();assert.equal(c.rame.totalLength,770);const origin=[...c._carryoverCantonIds];assert.ok(origin.length>0);for(let i=0;i<35;i++){f.tick();if(f.r.state==='done')break;assert.ok(c.totalDistance-c._carryoverStartTravelKm<.77);for(const id of origin)assert.equal(cantonManager.cantons.get(id)?.occupiedBy,c.id,'tail still retains approach');}});
test('RC17 DDS04 third-party crossing reservation holds rescue without deleting its authority',async()=>{const f=await setup(),v=f.game.voiePointManager=new VoiePointManager();const third={id:'CROSS',active:true,position:{lat:48,lon:2.002},speed:0,state:'stopped_at_station'};f.game.scheduleCreator.services.push(third);const own={id:'OWN',route:f.r.route,occupiedBy:null,reservedBy:null};const crossing={id:'CROSSING',route:[{lat:48.00001,lon:1.999},{lat:48.00001,lon:2.001}],occupiedBy:null,reservedBy:third.id};v.troncons=[own,crossing];v._rebuildMaps();assert.equal(v.checkCisaillement('OWN',f.r.id),crossing);assert.equal(v.isTronconReserved('CROSSING',f.r.id),true);const before={...f.r.position};f.tick(3);assert.deepEqual(f.r.position,before);assert.equal(crossing.reservedBy,third.id);});
test('RC17 DDS04 mission removal does not reset depot locomotive fuel or mileage',async()=>{const f=await setup(),c=f.controller();c.rame.consumables.fuelCapacityL=100;c.rame.consumables.fuelL=100;f.tick(20);const registered=f.depot.rescueLocos[0];assert.ok(registered.totalKmRun>0);assert.ok(registered.consumables.fuelL<100);const save=JSON.parse(JSON.stringify(f.manager.toSave()));f.manager.loadFromSave(save);const c2=f.controller();assert.equal(c2.rame.consumables.fuelL,registered.consumables.fuelL);assert.equal(c2.rame.totalKmRun,registered.totalKmRun);});
