import test from 'node:test';import assert from 'node:assert/strict';
import {compactJson,expandJson,encodeJson,decodeJson,textByteStream} from '../storage-codec.js';
const pts=()=>Array.from({length:400},(_,i)=>({lat:48.1234567890123+i/12345,lon:2.023456789012345-i/65432,wayId:912345678900+i,maxSpeed:160,tags:{name:'Évry / Köln 🐒',electrified:'contact_line'}}));
for(const [label,value]of Object.entries({empty:{},array:[],null:null,unicode:{s:'é\ud800🐒\u0000<>&"',b:false},numerics:{n:1.23456789012345,s:-1e-250,t:1e250},nested:{a:{routePoints:pts()},b:{routePoints:pts()},nil:null}}))test(`RC13 codec: JSON round trip ${label}`,async()=>{const c=compactJson(value);assert.equal(c.rawBytes,new Blob([JSON.stringify(value)]).size);assert.deepEqual(expandJson(c.json),JSON.parse(JSON.stringify(value)));assert.deepEqual(await decodeJson(await encodeJson(value)),JSON.parse(JSON.stringify(value)));});
test('RC13 codec: independent copies and no mutation of live data',()=>{const p=pts(),v={a:{routePoints:p},b:{routePoints:p}},before=JSON.stringify(v),c=compactJson(v),r=expandJson(c.json);assert.equal(c.references,1);r.b.routePoints[0].lat=0;assert.equal(r.a.routePoints[0].lat,p[0].lat);assert.equal(JSON.stringify(v),before);});
test('RC13 codec: nested references expand in dependency order',()=>{const row={id:1,geometry:pts()};const v={first:{geometry:pts()},a:{ways:[row,row,row,row]},b:{ways:[row,row,row,row]}};const c=compactJson(v);assert.ok(c.references>=4);assert.equal(c.rawBytes,new Blob([JSON.stringify(v)]).size);assert.deepEqual(expandJson(c.json),v);});
test('RC13 codec: almost-identical geometry is never merged',()=>{const a=pts(),b=pts();b[200].lat+=1e-12;const c=compactJson({a:{geometry:a},b:{geometry:b}});assert.equal(c.references,0);assert.notEqual(expandJson(c.json).a.geometry[200].lat,expandJson(c.json).b.geometry[200].lat);});
test('RC13 codec: dictionary can be disabled with no data loss',()=>{const v={a:{geometry:pts()},b:{geometry:pts()}},c=compactJson(v,{dictionaryChars:0});assert.equal(c.references,0);assert.deepEqual(expandJson(c.json),v);});
test('RC13 codec: reserved-looking user data and prototype names stay literal',()=>{const v=JSON.parse('{"__proto__":{"polluted":true},"format":"RE13-JSON-1","refs":[[1,2]],"root":{"$re13ref":0}}');v.a={routePoints:pts()};v.b={routePoints:pts()};assert.deepEqual(expandJson(compactJson(v).json),v);assert.equal({}.polluted,undefined);});
test('RC13 codec: cyclic/BigInt inputs fail, not silently truncate',()=>{const x={};x.x=x;assert.throws(()=>compactJson(x));assert.throws(()=>compactJson({x:1n}));assert.throws(()=>compactJson(undefined));});
for(const ref of [null,[[],['a']],[['missing'],['a']],[['b'],['no']],[['b'],['b']],[['a','b'],['a']]])test(`RC13 codec: rejects corrupt references ${JSON.stringify(ref)}`,()=>{assert.throws(()=>expandJson(JSON.stringify({format:'RE13-JSON-1',root:{a:{b:null},b:null},refs:[ref]})));});
test('RC13 codec: gzip corruption is detected',async()=>{const packed=await encodeJson({routePoints:pts()}),bytes=new Uint8Array(await packed.data.arrayBuffer());bytes[Math.floor(bytes.length/2)]^=255;await assert.rejects(()=>decodeJson({...packed,data:new Blob([bytes])}));});
test('RC13 codec: no compression API still round trips and deduplicates',async()=>{const old=globalThis.CompressionStream;try{globalThis.CompressionStream=undefined;const v={a:{geometry:pts()},b:{geometry:pts()}},p=await encodeJson(v);assert.equal(p.codec,'RE13/json');assert.equal(p.references,1);assert.deepEqual(await decodeJson(p),v);}finally{globalThis.CompressionStream=old;}});
test('RC13 codec: UTF-8 chunk boundaries preserve surrogate pairs',async()=>{const s='x'.repeat(32767)+'🐒'+'é'.repeat(70000);assert.equal(await new Response(textByteStream(s)).text(),s);});
test('RC13 codec: 100 deterministic random JSON documents',async()=>{let seed=5;const rnd=()=>((seed=(seed*1664525+1013904223)>>>0)/2**32);for(let i=0;i<100;i++){const p=Array.from({length:64},()=>({lat:rnd()*180-90,lon:rnd()*360-180,v:rnd()*200,id:String(rnd())}));const v={i,geom:[{routePoints:p},{routePoints:p}],flag:rnd()>.5,t:'é🐒'+rnd()};const c=compactJson(v);assert.equal(c.rawBytes,new Blob([JSON.stringify(v)]).size);assert.deepEqual(expandJson(c.json),v);}});

test('RC13 codec: deep valid JSON is retained without emitting un-loadable reference paths',async()=>{let value={geometry:Array.from({length:40},(_,i)=>({lat:48+i/10000,lon:2+i/10000}))};value.routePoints=structuredClone(value.geometry);for(let i=0;i<520;i++)value={child:value};const compact=compactJson(value);assert.equal(compact.references,0);assert.deepEqual(expandJson(compact.json),value);});
