import test from 'node:test';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
const root=process.env.RE_BASE||path.resolve(import.meta.dirname,'../..');
const {ActiveService,ScheduleCreator,cantonManager}=await import(pathToFileURL(path.join(root,'js/schedule-creator.js')));
const {PlatformManager}=await import(pathToFileURL(path.join(root,'js/line.js')));
const {Economy}=await import(pathToFileURL(path.join(root,'js/economy.js')));
function fixture({dep=1439,arr=30,days=[1],dates=[]}={}){
 for(const key of ['cantons','routeCantons','trainCantons','resourceCantons'])cantonManager[key].clear();
 const world={stations:[{id:'A',name:'A',lat:48,lon:2,platforms:2},{id:'B',name:'B',lat:48.01,lon:2.01,platforms:2}],getStationById(id){return this.stations.find(s=>s.id===id)||null;}};
 const rame={id:'R',maxSpeed:120,totalMass:80,totalPower:2500,totalLength:20,totalCapacity:80,totalFreightCapacity:0,elements:[],elementDetails:[]};
 const creator=new ScheduleCreator(),eco=new Economy();const svc=new ActiveService({id:'calendar',rameId:'R',name:'Night',stops:[{stationId:'A',type:'arret',departureTime:dep,arrivalTime:dep},{stationId:'B',type:'arret',departureTime:arr,arrivalTime:arr}],routes:[world.stations.map(s=>({...s,maxSpeed:120,electrified:true}))],runDays:days,runDates:dates},rame,world,null);
 creator.services.push(svc);const g={world,scheduleCreator:creator,platformManager:new PlatformManager(),economy:eco,realismSettings:{},rameManager:{getById:id=>id==='R'?rame:null}};return{g,svc,rame};
}
function withGame(g,fn){const old=globalThis.window;globalThis.window={game:g};try{return fn();}finally{globalThis.window=old;}}
const mon='2026-09-07',tue='2026-09-08',stop={effect:'stop',name:'Incident origine'};
test('RC6-CAL-01: delayed Monday 23:59 service departs Tuesday 00:03 with four minutes delay',()=>{const{g,svc}=fixture();withGame(g,()=>{svc.train.incident=stop;svc.scheduleTick(1439,mon,g.economy);svc.train.incident=null;svc.scheduleTick(3,tue,g.economy);assert.equal(svc.state,'moving');assert.equal(svc.currentStopIndex,1);assert.equal(svc.train.delay,4);});});
test('RC6-CAL-02: first observation after midnight infers eligible previous day',()=>{const{g,svc}=fixture();withGame(g,()=>{svc.scheduleTick(3,tue,g.economy);assert.equal(svc.state,'moving');});});
test('RC6-CAL-03: Tuesday-only 23:59 service cannot run Monday night after clock wrap',()=>{const{g,svc}=fixture({days:[2]});withGame(g,()=>{svc.scheduleTick(3,tue,g.economy);assert.notEqual(svc.state,'moving');assert.equal(svc.position,null);});});
test('RC6-CAL-04: specific operation dates refer to departure day',()=>{const{g,svc}=fixture({dates:[mon]});withGame(g,()=>{svc.train.incident=stop;svc.scheduleTick(1439,mon,g.economy);svc.train.incident=null;svc.scheduleTick(3,tue,g.economy);assert.equal(svc.state,'moving');});});
test('RC6-CAL-05: Tuesday 00:00 train prepares Monday 23:59 but never departs early',()=>{const{g,svc}=fixture({dep:0,arr:30,days:[2]});withGame(g,()=>{svc.scheduleTick(1439,mon,g.economy);assert.ok(svc.position);assert.equal(svc.state,'waiting');svc.scheduleTick(0,tue,g.economy);assert.equal(svc.state,'moving');});});
test('RC6-CAL-06: no duplicate same-day run; next eligible duty rearms when stock is at origin',()=>{const{g,svc}=fixture({dep:600,arr:630,days:[1,2]});withGame(g,()=>{svc.scheduleTick(600,mon,g.economy);svc._currentDate=mon;svc.completeService(g.economy,g.world.stations[1]);svc.scheduleTick(601,mon,g.economy);assert.equal(svc.completed,true);svc.rame.currentLocation={stationId:'A',depotId:''};svc.scheduleTick(600,tue,g.economy);assert.equal(svc.state,'moving');assert.equal(svc.completed,false);});});
test('RC6-CAL-07: Monday duty finishing Tuesday does not consume Tuesday night duty',()=>{const{g,svc}=fixture({days:[1,2]});withGame(g,()=>{svc.scheduleTick(1439,mon,g.economy);svc._currentDate=tue;svc.completeService(g.economy,g.world.stations[1]);svc.rame.currentLocation={stationId:'A',depotId:''};svc.scheduleTick(1439,tue,g.economy);assert.equal(svc.state,'moving');});});
test('RC6-CAL-08: inactive service never rearms',()=>{const{g,svc}=fixture({dep:600,arr:630,days:[1,2]});withGame(g,()=>{svc.scheduleTick(600,mon,g.economy);svc.completeService(g.economy);svc.active=false;svc.scheduleTick(600,tue,g.economy);assert.equal(svc.completed,true);});});
test('RC6-CAL-09: delayed overnight origin survives compact save/reload',()=>{const{g,svc}=fixture();withGame(g,()=>{svc.train.incident=stop;svc.scheduleTick(1439,mon,g.economy);const save=JSON.parse(JSON.stringify(g.scheduleCreator.toSave()));const restored=new ScheduleCreator();restored.loadFromSave(save,g.rameManager,g.world,3,tue);g.scheduleCreator=restored;const again=restored.services[0];again.scheduleTick(3,tue,g.economy);assert.equal(again.state,'moving');assert.equal(again.train.delay,4);});});
test('RC6-CAL-10: completed operating day persists through midnight reload',()=>{const{g,svc}=fixture({days:[1,2]});withGame(g,()=>{svc.scheduleTick(1439,mon,g.economy);svc._currentDate=tue;svc.completeService(g.economy);const save=JSON.parse(JSON.stringify(g.scheduleCreator.toSave()));const restored=new ScheduleCreator();restored.loadFromSave(save,g.rameManager,g.world,1439,tue);g.scheduleCreator=restored;restored.services[0].scheduleTick(1439,tue,g.economy);assert.equal(restored.services[0].state,'moving');});});
test('RC6-CAL-11: ineligible day does not monopolize station priority or shared stock',()=>{const{g,svc}=fixture({days:[2]});svc._currentDate=tue;withGame(g,()=>{g.scheduleCreator.beginTick(3);assert.equal(g.scheduleCreator.getEarliestDueServiceAtStation('A',3),null);assert.equal(g.scheduleCreator.isRameInUse('R','other',3),false);g.scheduleCreator._rameUsage=null;assert.equal(g.scheduleCreator.isRameInUse('R','other',3),false);});});
test('RC6-CAL-12: daily restart cannot teleport stock from previous terminus',()=>{const{g,svc}=fixture({dep:600,arr:630,days:[1,2]});withGame(g,()=>{svc.scheduleTick(600,mon,g.economy);svc.completeService(g.economy,g.world.stations[1]);svc.scheduleTick(600,tue,g.economy);assert.equal(svc.completed,false);assert.equal(svc.state,'waiting');assert.equal(svc.position,null);assert.equal(svc.rame.currentLocation.stationId,'B');assert.equal(svc.train.movementAuthority.code,'MATERIAL_POSITION');});});
test('RC6-CAL-13: future next-day duty rearms early and resets positioning flags',()=>{const{g,svc}=fixture({dep:600,arr:630,days:[1,2]});withGame(g,()=>{svc.scheduleTick(600,mon,g.economy);svc.completeService(g.economy,g.world.stations[1]);svc._evoCreated=true;svc._evoCompleted=true;svc.scheduleTick(500,tue,g.economy);assert.equal(svc.completed,false);assert.equal(svc.state,'waiting');assert.equal(svc.position,null);assert.equal(svc._evoCreated,false);assert.equal(svc._evoCompleted,false);});});
test('RC6-CAL-14: completed automatic EVO remains one-shot',()=>{const{g,svc}=fixture({dep:600,arr:630,days:[1,2]});svc.serviceType='evo';withGame(g,()=>{svc.scheduleTick(600,mon,g.economy);svc.completeService(g.economy);svc.scheduleTick(600,tue,g.economy);assert.equal(svc.completed,true);});});
