import test from 'node:test';import assert from 'node:assert/strict';import {gzipSync} from 'node:zlib';
import {installIDB,localMemory,openDB,put,get} from '../../scripts/test-idb-harness.mjs';
let seq=0;const setup=async()=>{const f=installIDB();delete globalThis.Worker;const {GameStorage}=await import(`../storage.js?rc13=${++seq}`);const s=new GameStorage();await s._ready;const db=await openDB('rail-empire-save-db','saves');return{f,s,db};};
const large=()=>({scheduleV2:{schedules:[{versions:[{outboundPath:{legs:[{routePacked:{count:13000,geometry:Array.from({length:13000},(_,i)=>({lat:48+i/1e5,lon:2+i/2e5,id:i,limit:160}))}}]}}]}]},companyName:'PE 🐒'});
test('RC13 persistence: low-memory mode writes binary gzip and restores all data',async()=>{const{s,db}=await setup(),v=large();assert.equal(await s.saveGame(v,{lowMemory:true}),true);const row=await get(db,'saves','main');assert.ok(row.stored instanceof Blob);assert.equal(row.codec,'RE13/gzip');assert.ok(row.sizeBytes<new Blob([JSON.stringify(v)]).size/5);assert.deepEqual(await s.loadGame(),v);assert.ok(s.getSaveInfo().reductionRatio>5);});
test('RC13 persistence: a second import can load binary records after reload',async()=>{const{s}=await setup(),v={fleet:[{name:'Évry'}]};await s.saveGame(v);const {GameStorage}=await import(`../storage.js?reload=${++seq}`);assert.deepEqual(await new GameStorage().loadGame(),v);});
for(const compressed of [false,true])test(`RC13 persistence: legacy IndexedDB ${compressed?'RELZ gzip':'JSON'} remains readable without rewriting`,async()=>{const{s,db,f}=await setup(),v={companyName:'Avant RC13'},json=JSON.stringify(v),stored=compressed?'RELZ:'+gzipSync(json).toString('base64'):json;await put(db,'saves',{key:'main',stored,sizeBytes:stored.length,compressed,updatedAt:1});const n=f.commits;assert.deepEqual(await s.loadGame(),v);assert.equal(f.commits,n);localStorage.clear();assert.equal(await s.hasSaveAsync(),true);assert.ok(localStorage.getItem('rail-empire-save-meta').length<400);});
test('RC13 persistence: legacy localStorage read survives new format save',async()=>{const{s}=await setup(),v={money:12345};localStorage.setItem('rail-empire-save',JSON.stringify(v));assert.deepEqual(await s.loadGame(),v);assert.ok(localStorage.getItem('rail-empire-save'));assert.equal(await s.saveGame(v),true);assert.equal(localStorage.getItem('rail-empire-save'),null);assert.deepEqual(await s.loadGame(),v);});
test('RC13 persistence: newest fallback wins over an older IndexedDB save',async()=>{const{s,f}=await setup();await s.saveGame({revision:1});f.failNextCommit=true;assert.equal(await s.saveGame({revision:2}),true);assert.equal(s.getSaveInfo().backend,'localStorage-fallback');assert.deepEqual(await s.loadGame(),{revision:2});await s.saveGame({revision:3});assert.deepEqual(await s.loadGame(),{revision:3});assert.equal(localStorage.getItem('rail-empire-save'),null);});
test('RC13 persistence: both quotas fail without destroying previous committed save',async()=>{const{s,f}=await setup();await s.saveGame({revision:1});globalThis.localStorage=localMemory(0);f.failNextCommit=true;assert.equal(await s.saveGame({revision:2}),false);assert.match(s.lastError,/QuotaExceededError/);assert.deepEqual(await s.loadGame(),{revision:1});});
test('RC13 persistence: corrupted IndexedDB payload falls back to valid legacy copy',async()=>{const{s,db}=await setup();await put(db,'saves',{key:'main',stored:new Blob(['broken']),codec:'RE13/gzip',updatedAt:100,sizeBytes:6});localStorage.setItem('rail-empire-save',JSON.stringify({rescued:true}));assert.deepEqual(await s.loadGame(),{rescued:true});});
test('RC13 persistence: concurrent saves preserve call order and snapshot values',async()=>{const{s}=await setup(),v={n:1};const a=s.saveGame(v),b=s.saveGame({n:2});v.n=99;assert.deepEqual(await Promise.all([a,b]),[true,true]);assert.deepEqual(await s.loadGame(),{n:2});});
test('RC13 persistence: deletion is ordered after a pending save',async()=>{const{s}=await setup();const p=s.saveGame(large());s.deleteSave();await p;assert.equal(await s.loadGame(),null);assert.equal(s.hasSave(),false);});
test('RC13 persistence: JSON export retains the legacy portable schema',async()=>{const{s}=await setup(),v={companyName:'Évry',routePoints:[{lat:1.23456789,lon:9.87654321}]};const r=await s.makeExportBlob(v);const text=r.ext==='.json.gz'?await new Response(r.blob.stream().pipeThrough(new DecompressionStream('gzip'))).text():await r.blob.text();assert.deepEqual(JSON.parse(text),v);assert.equal(JSON.parse(text).format,undefined);});
test('RC13 persistence: malformed state cannot replace a good save',async()=>{const{s}=await setup();await s.saveGame({good:true});const v={};v.v=v;assert.equal(await s.saveGame(v),false);assert.deepEqual(await s.loadGame(),{good:true});});

test('RC13 persistence: a fallback is newest even if the computer clock moved backwards',async()=>{const{s,f}=await setup();await s.saveGame({revision:1});const before=Date.now;try{Date.now=()=>100;f.failNextCommit=true;assert.equal(await s.saveGame({revision:2}),true);}finally{Date.now=before;}assert.deepEqual(await s.loadGame(),{revision:2});});
test('RC13 persistence: inaccessible IndexedDB deletion stays masked on reload',async()=>{const{s,f}=await setup();await s.saveGame({revision:1});f.failNextCommit=true;s.deleteSave();assert.equal(await s.loadGame(),null);assert.equal(await s.hasSaveAsync(),false);assert.ok(localStorage.getItem('rail-empire-save-deleted-at'));const{GameStorage}=await import(`../storage.js?tombstone=${++seq}`);assert.equal(await new GameStorage().loadGame(),null);assert.equal(await s.saveGame({revision:2}),true);assert.deepEqual(await s.loadGame(),{revision:2});assert.equal(localStorage.getItem('rail-empire-save-deleted-at'),null);});

test('RC13 persistence: committed fallback statistics survive a metadata quota failure',async()=>{const{s,f}=await setup();await s.saveGame({revision:1});const set=localStorage.setItem;localStorage.setItem=(key,value)=>{if(key==='rail-empire-save-meta')throw new DOMException('quota','QuotaExceededError');return set(key,value);};f.failNextCommit=true;assert.equal(await s.saveGame(large()),true);const info=s.getSaveInfo();assert.equal(info.backend,'localStorage-fallback');assert.equal(info.compressed,true);assert.equal(info.sizeBytes,new Blob([localStorage.getItem('rail-empire-save')]).size);assert.ok(info.reductionRatio>5);assert.deepEqual(await s.loadGame(),large());});
