import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {gzipSync,gunzipSync} from 'node:zlib';import {createRequire} from 'node:module';
const {createLocalServer}=createRequire(import.meta.url)('../../scripts/serve-local.cjs');
const source='/* RE 🐒 */\nwindow.probe='+JSON.stringify('é\n"<>'.repeat(15000))+';';
async function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'re14-packed-'));fs.mkdirSync(path.join(root,'js'));fs.writeFileSync(path.join(root,'index.html'),'<h1>RE14</h1>');fs.writeFileSync(path.join(root,'js/test.js.gz'),gzipSync(source));const server=createLocalServer(root);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(async()=>{await new Promise(resolve=>server.close(resolve));fs.rmSync(root,{recursive:true,force:true});});const port=server.address().port;
 const req=(url,headers={},method='GET')=>new Promise((resolve,reject)=>{const r=http.request({host:'127.0.0.1',port,path:url,headers,method},res=>{const chunks=[];res.on('data',x=>chunks.push(x));res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body:Buffer.concat(chunks)}));res.on('error',reject);});r.on('error',reject);r.end();});return {req,root};}
for(const accept of ['gzip','br, gzip, deflate','GZIP','*;q=0.5'])test('RC14 light server: gzip negotiation '+accept,async t=>{const {req}=await fixture(t),r=await req('/js/test.js?v=14',{'Accept-Encoding':accept});assert.equal(r.status,200);assert.equal(r.headers['content-encoding'],'gzip');assert.equal(r.headers['content-type'],'text/javascript; charset=utf-8');assert.equal(r.headers.vary,'Accept-Encoding');assert.equal(gunzipSync(r.body).toString(),source);assert.equal(+r.headers['content-length'],r.body.length);});
for(const accept of ['', 'identity','br','gzip;q=0','gzip;q=0, *;q=1','gzip;q=bad','gzip;q=2'])test('RC14 light server: identity fallback '+accept,async t=>{const {req}=await fixture(t),r=await req('/js/test.js',{'Accept-Encoding':accept});assert.equal(r.status,200);assert.equal(r.headers['content-encoding'],undefined);assert.equal(r.body.toString(),source);assert.equal(r.headers.vary,'Accept-Encoding');});
test('RC14 light server: cache tags distinguish gzip and identity',async t=>{const {req}=await fixture(t),g=await req('/js/test.js',{'Accept-Encoding':'gzip'}),i=await req('/js/test.js');assert.notEqual(g.headers.etag,i.headers.etag);const hit=await req('/js/test.js',{'Accept-Encoding':'gzip','If-None-Match':g.headers.etag});assert.equal(hit.status,304);assert.equal(hit.body.length,0);assert.equal((await req('/js/test.js',{'If-None-Match':g.headers.etag})).status,200);});
test('RC14 light server: HEAD has no decoded or encoded body',async t=>{const {req}=await fixture(t);for(const accept of ['gzip','identity']){const r=await req('/js/test.js',{'Accept-Encoding':accept},'HEAD');assert.equal(r.status,200);assert.equal(r.body.length,0);}});
test('RC14 light server: plain edited file takes precedence over stale sidecar',async t=>{const {req,root}=await fixture(t);fs.writeFileSync(path.join(root,'js/test.js'),'updated');const r=await req('/js/test.js',{'Accept-Encoding':'gzip'});assert.equal(r.body.toString(),'updated');assert.equal(r.headers['content-encoding'],undefined);});
test('RC14 light server: symlinked packed file cannot escape game folder',async t=>{const {req,root}=await fixture(t);fs.unlinkSync(path.join(root,'js/test.js.gz'));fs.symlinkSync(path.join(root,'index.html'),path.join(root,'js/test.js.gz'));assert.equal((await req('/js/test.js')).status,403);});
test('RC14 light server: raw .gz, archives, sources and traversal stay inaccessible',async t=>{const {req}=await fixture(t);for(const url of ['/js/test.js.gz','/src/ts/admin.ts','/QA/test.json','/js/../index.html','/js/%2e%2e/index.html'])assert.equal((await req(url)).status,403,url);assert.equal((await req('/js/absent.js')).status,404);});
