import test from 'node:test';
import assert from 'node:assert/strict';
import { Connections } from '../connections.js';
import { ScheduleV2Runtime } from '../schedule-v2-runtime.js';
import { makeGame, addValidSchedule, addDieselFormation } from './re-rc2-fixtures.mjs';
import { ScheduleCreator } from '../schedule-creator.js';
import { PlatformManager } from '../line.js';
function feeder(id='feeder',station='A',arr=1431){return{id,state:'moving',currentStopIndex:1,active:true,serviceType:'passager',train:{delay:0},stops:[{stationId:'X',type:'arret',departureTime:1400},{stationId:station,type:'arret',arrivalTime:arr,departureTime:arr+2}],getCurrentStops(){return this.stops;}};}
function receiver(id='receiver',station='A',dep=1430){return{id,state:'waiting',currentStopIndex:0,active:true,serviceType:'passager',train:{},stops:[{stationId:station,type:'arret',departureTime:dep},{stationId:'B',type:'arret',arrivalTime:dep+30,departureTime:dep+32}],getCurrentStops(){return this.stops;}};}
function cfixture(policy='moderate',dep=1430,arr=1431){const c=new Connections();c.waitPolicy=policy;const f=feeder('F','A',arr),r=receiver('R','A',dep);c.addTransfer('F','R','A');return{c,f,r,services:[f,r]};}
test('RC2-CONN-01: actual arrival plus three-minute transfer time releases the connecting train',()=>{const{c,f,r,services}=cfixture();assert.equal(c.shouldWait('R','A',1430,services,'2026-09-11'),true);f.state='stopped_at_station';f.currentStopIndex=2;f.train._stoppedSinceGameTime=1431;c.onArrival(f,f.stops[1],1431,'2026-09-11');assert.equal(c.shouldWait('R','A',1433,services,'2026-09-11'),true);assert.equal(c.shouldWait('R','A',1434,services,'2026-09-11'),false);c.onDeparture(r,r.stops[0],1434,'2026-09-11',services);assert.equal(c.stats.successfulTransfers,1);});
test('RC2-CONN-02: a stopped feeder cannot hold another train indefinitely',()=>{const{c,f,services}=cfixture();f.state='stopped_at_station';f.currentStopIndex=2;f.train._stoppedSinceGameTime=1431;assert.equal(c.shouldWait('R','A',1438,services,'2026-09-11'),false);});
test('RC2-CONN-03: strict policy means no added departure delay',()=>{const{c,services}=cfixture('strict');assert.equal(c.shouldWait('R','A',1430,services,'2026-09-11'),false);});
test('RC2-CONN-04: a feeder that cannot meet the maximum hold does not block departure',()=>{const{c,services}=cfixture('moderate',1430,1440);assert.equal(c.shouldWait('R','A',1430,services,'2026-09-11'),false);});
test('RC2-CONN-05: successful departure is accounted only once, including reload',()=>{const{c,f,r,services}=cfixture();c.onArrival(f,f.stops[1],1425,'2026-09-11');c.onDeparture(r,r.stops[0],1430,'2026-09-11',services);const restored=new Connections();restored.loadFromSave(JSON.parse(JSON.stringify(c.toSave())));restored.onDeparture(r,r.stops[0],1430,'2026-09-11',services);assert.deepEqual(restored.stats,{totalTransfers:1,successfulTransfers:1,missedTransfers:0});});
test('RC2-CONN-06: a cancelled feeder is a missed transfer, not an indefinite hold',()=>{const{c,f,r,services}=cfixture();f.cancelled=true;assert.equal(c.shouldWait('R','A',1430,services,'2026-09-11'),false);c.onDeparture(r,r.stops[0],1430,'2026-09-11',services);assert.equal(c.stats.missedTransfers,1);});
test('RC2-CONN-07: a 23:59 departure can wait across midnight but not past 00:04',()=>{const{c,f,r,services}=cfixture('moderate',1439,0);assert.equal(c.shouldWait('R','A',1439,services,'2026-09-11'),true);f.state='stopped_at_station';f.currentStopIndex=2;f.train._stoppedSinceGameTime=0;c.onArrival(f,f.stops[1],0,'2026-09-12');assert.equal(c.shouldWait('R','A',2,services,'2026-09-12'),true);assert.equal(c.shouldWait('R','A',3,services,'2026-09-12'),false);assert.equal(c.shouldWait('R','A',4,services,'2026-09-12'),false);c.onDeparture(r,r.stops[0],3,'2026-09-12',services);assert.equal(c.stats.successfulTransfers,1);});
test('RC2-CONN-08: yesterday\'s completed service must not satisfy today\'s connection',()=>{const{c,f,r,services}=cfixture();c.onArrival(f,f.stops[1],1425,'2026-09-10');f.cancelled=true;c.onDeparture(r,r.stops[0],1430,'2026-09-11',services);assert.equal(c.stats.successfulTransfers,0);assert.equal(c.stats.missedTransfers,1);});
test('RC2-CONN-09: configured V2 connections remain valid for the next dated occurrence',()=>{const{c,f,r,services}=cfixture();c.transfers=[];c.addTransfer('v2:rotA:occA:2026-09-10','v2:rotB:occB:2026-09-10','A');f.id='v2:rotA:occA:2026-09-11';r.id='v2:rotB:occB:2026-09-11';assert.equal(c.shouldWait(r.id,'A',1430,services,'2026-09-11'),true);});
test('RC2-CONN-10: auto detection uses commercial arrivals, not feeder departure time',()=>{const c=new Connections(),f=feeder('F','A',600),r=receiver('R','A',605);f.stops[1].departureTime=620;assert.ok(c.autoDetect([f,r],null).some(x=>x.fromServiceId==='F'&&x.toServiceId==='R'));f.stops[1].technicalLocationId='TECH';assert.equal(c.autoDetect([f,r],null).length,0);});
test('RC2-CONN-11: real ActiveService origin departure obeys the connection and records it',()=>{const g=makeGame(),rec=addValidSchedule(g);rec.currentVersion.category='PASSENGER';const rot=g.rotationV2.addRotation({name:'Connection'});addDieselFormation(g,rot,rec);g.connections=new Connections();g.platformManager=new PlatformManager();g.scheduleV2Runtime.sync(1429,'2026-08-16');const s=g.scheduleCreator.services[0];s.serviceType='passager';const f=feeder('FEED','A',1431);g.scheduleCreator.services.push(f);g.connections.addTransfer('FEED',s.id,'A');const old=globalThis.window;globalThis.window={game:g};try{s.scheduleTick(1430,'2026-08-16',null);assert.equal(s.state,'waiting');assert.match(s.train.delayReason,/correspondance/);f.state='stopped_at_station';f.currentStopIndex=2;f.train._stoppedSinceGameTime=1431;g.connections.onArrival(f,f.stops[1],1431,'2026-08-16');s.scheduleTick(1433,'2026-08-16',null);assert.equal(s.state,'waiting');s.scheduleTick(1434,'2026-08-16',null);assert.equal(s.state,'moving');assert.equal(g.connections.stats.successfulTransfers,1);}finally{if(old===undefined)delete globalThis.window;else globalThis.window=old;}});

import { UI } from '../ui.js';
import fs from 'node:fs';
test('RC2-CONN-12: the removed standalone page has an accessible entry from the schedules toolbar',()=>{assert.equal(typeof UI.prototype.openConnectionsDialog,'function');assert.match(fs.readFileSync(new URL('../../index.html',import.meta.url),'utf8'),/id="btn-schedule-connections"/);});
