import test from 'node:test';import assert from 'node:assert/strict';
import {makeGame,addValidSchedule,addDieselFormation} from './re-rc2-fixtures.mjs';
import {Weather} from '../weather.js';import {SimulationEngine} from '../engine.js';
function setup(){const game=makeGame(),rec=addValidSchedule(game),rot=game.rotationV2.addRotation({name:'Replay'});addDieselFormation(game,rot,rec);game.engine=new SimulationEngine();const epoch=Date.parse('2026-09-12T21:55:00Z');game.engine.enableChronologicalReplay(null,epoch,epoch);globalThis.window={game};game.scheduleV2Runtime.sync(1435,'2026-09-12');return {game,s:game.scheduleCreator.services[0]};}
for(const effort of [0,.15,.8,1])test(`RC17 TIME05 V2 preserves tractive effort ${effort} on restore`,()=>{const {game,s}=setup();s._tractiveEffort=effort;s._brakeEffort=.4;const raw=JSON.parse(JSON.stringify(game.scheduleV2Runtime.toSave()));assert.equal(raw.services[0].tractiveEffort,effort);s._tractiveEffort=0;assert.equal(game.scheduleV2Runtime.loadFromSave(raw),true);game.scheduleV2Runtime._restoreSnapshot(s,1435);assert.equal(s._tractiveEffort,effort);assert.equal(s._brakeEffort,.4);});
test('RC17 TIME05 malformed traction snapshot rejects atomically',()=>{const {game}=setup();const rt=game.scheduleV2Runtime,save=JSON.parse(JSON.stringify(rt.toSave()));for(const bad of [-.1,1.1,'1',null]){const copy=structuredClone(save);copy.services[0].tractiveEffort=bad;if(bad===null){assert.equal(rt.loadFromSave(copy),true);continue;}const before=rt._pendingSnapshots;assert.equal(rt.loadFromSave(copy),false);assert.equal(rt._pendingSnapshots,before);}});
test('RC17 TIME05 known local weather survives JSON reload and stays independent',()=>{const w=new Weather();w._pointCache.set('4800,200',{state:{type:'rain',windSpeed:50,rain6hMm:25,temperature:6,live:true},expiresAt:0});const raw=JSON.parse(JSON.stringify(w.toSave()));const restored=new Weather();restored.loadFromSave(raw);assert.deepEqual(restored._pointCache.get('4800,200'),w._pointCache.get('4800,200'));raw.pointObservations[0].state.windSpeed=99;assert.equal(restored._pointCache.get('4800,200').state.windSpeed,50);});
test('RC17 TIME05 historical replay neither fetches current weather nor discards stale known local conditions',()=>{const w=new Weather();globalThis.window={game:{engine:{getReplayDebtSeconds:()=>3600}}};w._pointCache.set('4800,200',{state:{type:'snow',temperature:-6,windSpeed:10},expiresAt:0});let calls=0;w._fetchLiveWeather=()=>calls++;w._fetchRadarTimestamps=()=>calls++;w.update(605,'2026-09-12',48,2);assert.equal(w.getAt(48,2).type,'snow');w.getAt(49,3);assert.equal(calls,0);assert.equal(w._pointFetchQueue.length,0);assert.equal(w._pointFetchTimer,null);});
test('RC17 TIME05 delayed weather response from prior world does not overwrite loaded observations',async()=>{const w=new Weather();globalThis.window={game:{engine:{getReplayDebtSeconds:()=>0}}};const oldFetch=globalThis.fetch;let respond;globalThis.fetch=()=>new Promise(r=>respond=r);try{const pending=w._fetchLiveWeather(48,2);w.loadFromSave({current:'snow',temperature:-5});respond({ok:true,json:async()=>({current:{temperature_2m:30,weather_code:0}})});await pending;assert.equal(w.current,'snow');assert.equal(w.temperature,-5);}finally{globalThis.fetch=oldFetch;}});
test('RC17 TIME05 bounded weather import rejects untyped or nonfinite local records',()=>{const w=new Weather();w.loadFromSave({pointObservations:[{key:'invalid',state:{type:'snow'}},{key:'4800,200',state:{type:'rain',windSpeed:Infinity,temperature:5}},{key:'4900,200',state:{type:'nonsense'}}]});assert.equal(w._pointCache.size,1);assert.equal(w._pointCache.get('4800,200').state.windSpeed,undefined);});

test('RC17 TIME05 V2 previous physical deceleration survives JSON and rejects corruption',()=>{const {game,s}=setup();s._lastPhysicsDecelMs2=.23456789;const save=JSON.parse(JSON.stringify(game.scheduleV2Runtime.toSave()));assert.equal(save.services[0].physicsDecelMs2,.23456789);s._lastPhysicsDecelMs2=0;assert.equal(game.scheduleV2Runtime.loadFromSave(save),true);game.scheduleV2Runtime._restoreSnapshot(s,1435);assert.equal(s._lastPhysicsDecelMs2,.23456789);save.services[0].physicsDecelMs2=-1;assert.equal(game.scheduleV2Runtime.loadFromSave(save),false);});
test('RC17 TIME05 staff payroll and workforce cursors survive JSON',async()=>{const {StaffManager}=await import('../staff.js');const s=new StaffManager();s._lastTickTime=125.5;s._lastTickDate='2026-09-12';s._lastWorkforceTickTime=124;s._lastWorkforceTickDate='2026-09-12';s._lastAutoAssignKey='2026-09-12:120';const raw=JSON.parse(JSON.stringify(s.toSave())),r=new StaffManager();r.loadFromSave(raw);for(const k of ['_lastTickTime','_lastTickDate','_lastWorkforceTickTime','_lastWorkforceTickDate','_lastAutoAssignKey'])assert.equal(r[k],s[k]);});
test('RC17 TIME05 staff legacy and malformed clock import do not create negative payroll time',async()=>{const {StaffManager}=await import('../staff.js');for(const clock of [undefined,{tick:-1,date:'bad',workforceTick:1500,workforceDate:'bad',autoAssign:4}]){const s=new StaffManager(),raw=JSON.parse(JSON.stringify(s.toSave()));raw.runtimeClock=clock;s.loadFromSave(raw);assert.equal(s._lastTickTime,null);assert.equal(s._lastWorkforceTickTime,null);}});
