import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { ScheduleV2Manager, ScheduleState, ScheduledLocation, TrackBinding, TrainCategory, StopCode } from '../schedule-v2-model.js';
import { RotationV2Manager, FormationRole } from '../rotation-v2-model.js';
import { RotationV2Editor } from '../rotation-v2-editor.js';
function loc(id,name,stationId,arr,dep){return new ScheduledLocation({id,stationId,name,track:new TrackBinding({wayId:`w-${id}`,displayName:'V1',lat:48,lon:2,snapLat:48,snapLon:2}),arrivalSec:arr,departureSec:dep,stopCode:StopCode.C,arrivalOverride:arr!=null,departureOverride:dep!=null});}
function sched(sm,number,dep,arr){const rec=sm.createDraft({number,name:number,category:TrainCategory.PASSENGER,maxSpeed:140});const v=rec.currentVersion;v.locations=[loc('A','Paris Gare de l’Est','PE',null,dep),loc('B','Pantin','PANT',arr,null)];v.locations.forEach((l,i)=>l.order=i);v.state=ScheduleState.VALID;v.outboundPath.distanceKm=6;return rec;}
function setup(){const scheduleV2=new ScheduleV2Manager(),rotationV2=new RotationV2Manager(scheduleV2),game={scheduleV2,rotationV2,saveState(){},world:{getStationById(){return null;}}};const rec=sched(scheduleV2,'445',19*3600+34*60,19*3600+44*60),r=rotationV2.addRotation({name:'Migré — 445'}),v=rotationV2.addVehicle({number:'Z 50001',category:'automotrice',powerW:1}),o=rotationV2.addOccurrence(r.id,{scheduleId:rec.id,versionId:rec.currentVersion.id,formation:{members:[{vehicleId:v.id,role:FormationRole.LEAD}]}});rotationV2.recalculateRotation(r.id);const e=Object.create(RotationV2Editor.prototype);Object.assign(e,{game,ui:{},selectedRotationId:r.id,selectedOccurrenceId:o.id,selectedMaterialId:'',activeView:'sheet',libraryTab:'schedules',searchQuery:'',selectedDate:'',materialSort:'number',sheetZoomIndex:-1,sheetLibraryCollapsed:false,sheetInspectorCollapsed:false,_history:[],_future:[]});return {e,r};}
test('HOTFIX37 uses SVG fixed geometry and readable scale for short services',()=>{const {e,r}=setup(),html=e._renderTimeline(r,true);for(const token of ['rv6-sheet','rv6-paper-scroll','rv6-svg','rv6-mainline','rv6-trainnum','445','19:34','19:44','PGD','PANT','960 px/h'])assert.ok(html.includes(token),token);});
test('HOTFIX37 page/workspace/diagram expose persistent two-axis scrolling',()=>{const src=fs.readFileSync(new URL('../rotation-v2-editor.js',import.meta.url),'utf8');for(const token of ['#page-rotations{overflow:scroll!important','rv3-work{display:grid','overflow:scroll;scrollbar-gutter:stable both-edges','rv6-paper-scroll{position:relative;flex:1;min-height:0;overflow:scroll!important','::-webkit-scrollbar{width:14px;height:14px'])assert.ok(src.includes(token),token);});
test('HOTFIX37 does not auto-hide side panels and keeps explicit toggles',()=>{const src=fs.readFileSync(new URL('../rotation-v2-editor.js',import.meta.url),'utf8');assert.match(src,/sheetLibraryCollapsed\s*=\s*false\s*;\s*this\.sheetInspectorCollapsed\s*=\s*false/);assert.ok(src.includes('toggle-sheet-library'));assert.ok(src.includes('toggle-sheet-inspector'));assert.ok(src.includes('.rv5-sheet-work:not(.rv5-hide-library) .rv3-library{display:block}'));assert.ok(src.includes('.rv5-sheet-work:not(.rv5-hide-inspector) .rv3-inspector{display:block}'));});
test('HOTFIX37 FILE cache is dep30+ and bundle contains SVG duty markers',()=>{const idx=fs.readFileSync(new URL('../../index.html',import.meta.url),'utf8'),bundle=fs.readFileSync(new URL('../rail-empire.file.bundle.js',import.meta.url),'utf8');assert.match(idx,/1199repair24/);assert.match(bundle,/1199repair24/);for(const token of ['rv6-paper-scroll','rv6-mainline','rv6-opbar','HOTFIX37'])assert.ok(bundle.includes(token),token);});
