import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { ScheduleV2Manager, ScheduleState, ScheduledLocation, TrackBinding, TrainCategory, StopCode } from '../schedule-v2-model.js';
import { RotationV2Manager, FormationRole } from '../rotation-v2-model.js';
import { RotationV2Editor } from '../rotation-v2-editor.js';
function loc(id,name,stationId,arr,dep){return new ScheduledLocation({id,stationId,name,track:new TrackBinding({wayId:`w-${id}`,displayName:'V1',lat:48,lon:2,snapLat:48,snapLon:2}),arrivalSec:arr,departureSec:dep,stopCode:StopCode.C,arrivalOverride:arr!=null,departureOverride:dep!=null});}
function sched(sm,number,dep,arr){const rec=sm.createDraft({number,name:number,category:TrainCategory.PASSENGER,maxSpeed:140});const v=rec.currentVersion;v.locations=[loc('A','Paris Gare de l’Est','PE',null,dep),loc('B','Pantin','PANT',arr,null)];v.locations.forEach((l,i)=>l.order=i);v.state=ScheduleState.VALID;v.outboundPath.distanceKm=6;return rec;}
function setup(){const scheduleV2=new ScheduleV2Manager(),rotationV2=new RotationV2Manager(scheduleV2),game={scheduleV2,rotationV2,saveState(){},world:{getStationById(){return null;}}};const rec=sched(scheduleV2,'445',19*3600+34*60,19*3600+44*60),r=rotationV2.addRotation({name:'Migré — 445'}),v=rotationV2.addVehicle({number:'Z 50001',category:'automotrice',powerW:1}),o=rotationV2.addOccurrence(r.id,{scheduleId:rec.id,versionId:rec.currentVersion.id,formation:{members:[{vehicleId:v.id,role:FormationRole.LEAD}]}});rotationV2.recalculateRotation(r.id);const e=Object.create(RotationV2Editor.prototype);Object.assign(e,{game,ui:{},selectedRotationId:r.id,selectedOccurrenceId:o.id,selectedMaterialId:'',activeView:'sheet',libraryTab:'schedules',searchQuery:'',selectedDate:'',materialSort:'number',sheetZoomIndex:-1,sheetLibraryCollapsed:true,sheetInspectorCollapsed:true,_history:[],_future:[]});return {e,r};}
test('HOTFIX36 short duty gets a readable one-hour real sheet instead of six empty hours',()=>{const {e,r}=setup(),[min,max]=e._sheetBounds(r);assert.equal(max-min,3600);const html=e._renderTimeline(r,true);for(const token of ['rv5-sheet','rv5-service','445','19:34','19:44','PGD','PANT','Auto •','rv3-real-sheet'])assert.ok(html.includes(token),token);});
test('HOTFIX36 real sheet keeps locomotive/pilot visual contract and time zoom controls',()=>{const {e,r}=setup(),html=e._renderTimeline(r,true);assert.ok(html.includes('rv3-real-leadline loco'));for(const token of ['data-rv2="sheet-zoom"','data-rv2="sheet-fit"','Journée du roulement','ATTENTE'])assert.ok(html.includes(token)||token==='ATTENTE',token);});
test('HOTFIX36/37 side panels remain explicitly controllable',()=>{const src=fs.readFileSync(new URL('../rotation-v2-editor.js',import.meta.url),'utf8');for(const token of ['toggle-sheet-library','toggle-sheet-inspector','rv5-hide-library','rv5-hide-inspector'])assert.ok(src.includes(token),token);assert.match(src,/sheetLibraryCollapsed\s*=\s*(?:false\s*;\s*this\.sheetInspectorCollapsed\s*=\s*false|true\s*;\s*this\.sheetInspectorCollapsed\s*=\s*true)/);});
