import { htmlText } from './html-text.js';
// @ts-expect-error Browser cache-busted module specifier is resolved at runtime.
import { TileMap } from './map.js?v=1148';
// @ts-expect-error Browser cache-busted module specifier is resolved at runtime.
import { ScheduleV2Router } from './schedule-v2-routing.js?v=1148';
import { normalizeRailSection, cloneRailValue, type RailBinding, type RailPoint, type NormalizedRailSection } from './rail-section-geometry.js';

type StationLike = { id: string; name: string; lat: number; lon: number; type?: string; country?: unknown };
type CandidateLike = Partial<RailBinding> & { wayId?: string | number; trackRef?: string; name?: string; ref?: string; maxSpeed?: number; electrified?: boolean; geometry?: RailPoint[] };
type BoundPoint = RailBinding & { displayName?: string; osmSnapshot?: unknown };
type EditableRailSection = Omit<NormalizedRailSection, 'constraints'> & { constraints: BoundPoint[]; error: string };
type InfraForm = { type: string; name: string; tracks: number; cost: number; infrastructure: string[]; cargoTypes: string[] };
type PixelPoint = { x: number; y: number };
type TileMapLike = { setNetworkEnabled?(enabled: boolean): void; centerLat:number; centerLon:number; zoomLevel:number; viewportWidth:number; viewportHeight:number; applyZoom(delta:number,x:number,y:number):void; pan(dx:number,dy:number):void; markDirty?():void; screenToWorld(x:number,y:number,w:number,h:number):{lat:number;lon:number}; latLonToPixel(lat:number,lon:number):PixelPoint; renderTiles(ctx:CanvasRenderingContext2D,w:number,h:number):void };
type RouterSnapshot = { routePoints: RailPoint[]; segments: unknown[]; distanceKm: number };
type RouterLike = { chooseTrackCandidates(lat:number,lon:number,opts:Record<string,unknown>):Promise<CandidateLike[]>; routeBetweenBindings(start:RailBinding,end:RailBinding,constraints:BoundPoint[],opts:Record<string,unknown>):Promise<unknown>; snapshotRoute(route:unknown):RouterSnapshot };
type WorldLike = { stations?:StationLike[]; getStationById(id:string | undefined):StationLike|null; getStationsInBounds?(a:number,b:number,c:number,d:number):StationLike[]; addStation(data:Record<string,unknown>):StationLike; removeStation?(id:string):void };
type GameLike = { orm:{ getCountryAtPoint(lat:number,lon:number):unknown }; world:WorldLike; renderer?:{tileMap?:TileMapLike;invalidateStatic?():void}; platformManager:{initStation(id:string,tracks:number):void;stationPlatforms?:{delete?(id:string):void}}; depotManager:{add(data:Record<string,unknown>,economy:unknown):unknown;getAll?():Array<{type?:string;railSections?:NormalizedRailSection[]}>}; economy:unknown; saveState():void };
type UiLike = { renderDepotsList():void };
type PickerResolve = ((value: CandidateLike | null)=>void) | null;

function esc(s: unknown){return String(s??'').replace(/[&<>"']/g,(c: string)=>(({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'} as Record<string,string>)[String(c)]));}
function norm(s: unknown){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
function bindFromCandidate(c: CandidateLike): BoundPoint{return {wayId:c?.wayId!=null?String(c.wayId):'',trackRef:c?.trackRef||'',displayName:c?.trackRef||c?.name||c?.ref||'',lat:Number(c?.lat??c?.snapLat),lon:Number(c?.lon??c?.snapLon),snapLat:Number(c?.snapLat??c?.lat),snapLon:Number(c?.snapLon??c?.lon),osmSnapshot:cloneRailValue(c||{})};}
function isITE(type: unknown){return String(type||'').startsWith('ite');}
function sectionColor(selected: boolean){return selected?'#ffffff':'#22c55e';}

// HOTFIX40 — Depot/ITE V2 creator. It deliberately uses the exact same ORM routing
// primitives as Schedule Creator / Travaux V2. Each section is independent: drawing
// A→B then C→D never asks the router to invent B→C.
export class InfrastructureV2Editor {
  declare game: GameLike; declare ui: UiLike; declare router: RouterLike; declare tileMap: TileMapLike; declare sections: EditableRailSection[]; declare activeSectionId: string; declare mode: string; declare busy: boolean; declare dragging: boolean; declare panning: boolean; declare panThresholdPx: number; declare dragStartX:number; declare dragStartY:number; declare dragX:number; declare dragY:number; declare _pickerResolve: PickerResolve; declare _hoverCandidate: CandidateLike | null; declare form: InfraForm; declare overlay:HTMLElement; declare canvas:HTMLCanvasElement; declare ctx:CanvasRenderingContext2D; declare panel:HTMLElement; declare picker:HTMLElement; declare pickerList:HTMLElement;
  constructor(game: GameLike,ui: UiLike){
    this.game=game;this.ui=ui;this.router=new ScheduleV2Router(game.orm) as RouterLike;this.tileMap=new TileMap() as TileMapLike;
    this.sections=[];this.activeSectionId='';this.mode='idle';this.busy=false;this.dragging=false;this.panning=false;this.panThresholdPx=5;this._pickerResolve=null;this._hoverCandidate=null;
    this._ensureOverlay();
  }

  _ensureOverlay(){
    if(document.getElementById('infra-v2-overlay')){this.overlay=document.getElementById('infra-v2-overlay')!;this.canvas=this.overlay.querySelector('#iv2-map') as HTMLCanvasElement;this.ctx=this.canvas.getContext('2d')!;this.panel=this.overlay.querySelector('#iv2-panel-content') as HTMLElement;this.picker=this.overlay.querySelector('#iv2-picker') as HTMLElement;this.pickerList=this.overlay.querySelector('#iv2-picker-list') as HTMLElement;return;}
    const style=document.createElement('style');style.id='infra-v2-style';style.textContent=`
      #infra-v2-overlay{position:fixed;inset:0;z-index:9060;background:#07101d;color:#e8f0fb;display:none;font:12px system-ui,sans-serif}#infra-v2-overlay.open{display:flex;flex-direction:column}
      .iv2-top{height:48px;display:flex;align-items:center;gap:8px;padding:0 10px;background:#0d1726;border-bottom:1px solid #25354b;flex:0 0 auto}.iv2-top strong{font-size:15px}.iv2-top button,.iv2-btn{border:1px solid #344961;background:#16253a;color:#edf5ff;border-radius:6px;padding:7px 10px;cursor:pointer}.iv2-top button:hover,.iv2-btn:hover{background:#213650}.iv2-primary{background:#047857!important;border-color:#10b981!important}.iv2-danger{background:#471f27!important;border-color:#8d3e49!important}
      .iv2-body{position:relative;flex:1;min-height:0}.iv2-map{position:absolute;inset:0;width:100%;height:100%;display:block;background:#08111e}.iv2-panel{position:absolute;right:10px;top:10px;bottom:10px;width:380px;background:rgba(8,16,28,.97);border:1px solid #2b405b;border-radius:10px;box-shadow:0 12px 45px #0008;display:flex;flex-direction:column;overflow:hidden;backdrop-filter:blur(7px)}.iv2-panel-head{padding:8px;border-bottom:1px solid #24374e}.iv2-panel-content{padding:8px;overflow:auto;flex:1}.iv2-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.iv2-field{display:flex;flex-direction:column;gap:3px;margin-bottom:7px}.iv2-field label{font-size:10px;color:#9db0c8;text-transform:uppercase;letter-spacing:.04em}.iv2-field input,.iv2-field select{width:100%;box-sizing:border-box;background:#111d2d;border:1px solid #31455f;border-radius:5px;color:#eff6ff;padding:6px 7px;font:12px system-ui}.iv2-section{margin-top:10px;padding-top:9px;border-top:1px solid #22354a}.iv2-section h4{margin:0 0 7px;font-size:11px;color:#b9cbe0;text-transform:uppercase}.iv2-hint{padding:7px 9px;border:1px solid #27445f;background:#10243a;border-radius:6px;color:#c8e3ff;margin-bottom:8px}.iv2-hint.busy{border-color:#b57b21;color:#ffe2a4}.iv2-route-card{border:1px solid #263a51;background:#0e1a29;border-radius:6px;padding:6px;margin:5px 0;cursor:pointer}.iv2-route-card.active{border-color:#62b2ff;background:#132b43}.iv2-route-head{display:flex;align-items:center;gap:6px}.iv2-route-head b{flex:1}.iv2-route-card small{display:block;color:#91a9c4;margin-top:3px}.iv2-dot{width:9px;height:9px;border-radius:50%;display:inline-block;background:#22c55e}.iv2-badge{font-size:9px;border-radius:4px;padding:2px 5px;background:#283a51;color:#d9e8fa}.iv2-search-results{position:relative}.iv2-search-list{position:absolute;z-index:6;left:0;right:0;top:2px;background:#0c1827;border:1px solid #38516d;border-radius:6px;max-height:210px;overflow:auto}.iv2-search-item{padding:7px 8px;border-bottom:1px solid #22354a;cursor:pointer}.iv2-search-item:hover{background:#16304b}
      .iv2-picker{position:absolute;z-index:8;left:50%;top:50%;transform:translate(-50%,-50%);width:min(570px,90vw);max-height:70vh;background:#0b1726;border:1px solid #395571;border-radius:10px;box-shadow:0 20px 60px #000b;display:none;overflow:hidden}.iv2-picker.open{display:flex;flex-direction:column}.iv2-picker h3{margin:0;padding:11px 12px;border-bottom:1px solid #2a4057;font-size:13px}.iv2-picker-list{overflow:auto;padding:7px}.iv2-candidate{padding:8px;border:1px solid #273e56;border-radius:7px;margin:5px 0;background:#0f1d2d;cursor:pointer}.iv2-candidate:hover{border-color:#55a9ff;background:#16304b}.iv2-candidate small{display:block;color:#93aac4;margin-top:3px}.iv2-picker-foot{display:flex;justify-content:flex-end;gap:6px;padding:9px;border-top:1px solid #283e56}
      .iv2-bottom{height:43px;background:#0c1624;border-top:1px solid #24364d;display:flex;align-items:center;gap:6px;padding:0 10px;flex:0 0 auto}.iv2-bottom .spacer{flex:1}.iv2-status{color:#9fb3cb;font-size:11px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:42vw}.iv2-checks{display:flex;flex-wrap:wrap;gap:7px 10px}.iv2-checks label{font-size:11px;text-transform:none;color:#dce8f7}
      @media(max-width:850px){.iv2-panel{width:330px}.iv2-status{display:none}}
    `;document.head.appendChild(style);
    const o=document.createElement('div');o.id='infra-v2-overlay';o.innerHTML=`
      <div class="iv2-top"><button data-act="close">← Dépôts / ITE</button><strong>Dépôts / ITE V2</strong><span class="iv2-badge">Technologie Schedule Creator</span><span style="flex:1"></span><button data-act="zoom-out">−</button><button data-act="zoom-in">＋</button><button data-act="save" class="iv2-primary">✓ Construire</button></div>
      <div class="iv2-body"><canvas id="iv2-map" class="iv2-map"></canvas><div class="iv2-panel"><div class="iv2-panel-head"><b>Infrastructure</b></div><div class="iv2-panel-content" id="iv2-panel-content"></div></div><div class="iv2-picker" id="iv2-picker"><h3>Choisissez la voie ORM exacte</h3><div id="iv2-picker-list" class="iv2-picker-list"></div><div class="iv2-picker-foot"><button class="iv2-btn" data-act="cancel-picker">Annuler</button></div></div></div>
      <div class="iv2-bottom"><button class="iv2-btn iv2-primary" data-act="add-section">＋ Section / voie</button><button class="iv2-btn" data-act="add-via">＋ VIA</button><button class="iv2-btn" data-act="auto">↺ Auto</button><button class="iv2-btn" data-act="remove-via">✕ Dernier VIA</button><span class="iv2-status" id="iv2-status">Ajoutez une section puis cliquez son point A.</span><span class="spacer"></span><button class="iv2-btn iv2-danger" data-act="delete-section">🗑 Section</button></div>`;
    document.body.appendChild(o);this.overlay=o;this.canvas=o.querySelector('#iv2-map') as HTMLCanvasElement;this.ctx=this.canvas.getContext('2d')!;this.panel=o.querySelector('#iv2-panel-content') as HTMLElement;this.picker=o.querySelector('#iv2-picker') as HTMLElement;this.pickerList=o.querySelector('#iv2-picker-list') as HTMLElement;this._bind();
  }

  _bind(){
    this.overlay.addEventListener('click',(e: MouseEvent)=>{const b=(e.target as Element).closest('[data-act]');if(!b)return;const a=b.dataset.act;if(a==='close')this.close();if(a==='save')this.save();if(a==='zoom-in')this._zoom(1);if(a==='zoom-out')this._zoom(-1);if(a==='add-section')this.addSection();if(a==='delete-section')this.deleteSection();if(a==='add-via')this.armVia();if(a==='auto')this.resetAuto();if(a==='remove-via')this.removeLastVia();if(a==='cancel-picker')this._resolvePicker(null);});
    this.canvas.addEventListener('wheel',(e: WheelEvent)=>{e.preventDefault();const r=this.canvas.getBoundingClientRect();this.tileMap.applyZoom(e.deltaY<0?1:-1,e.clientX-r.left,e.clientY-r.top);this.draw();},{passive:false});
    this.canvas.addEventListener('mousedown',(e: MouseEvent)=>{if(e.button!==0||!this.isOpen())return;this.dragging=true;this.panning=false;this.dragStartX=this.dragX=e.clientX;this.dragStartY=this.dragY=e.clientY;});
    window.addEventListener('mousemove',(e: MouseEvent)=>{if(!this.dragging||!this.isOpen())return;if(!this.panning){const dx=e.clientX-this.dragStartX,dy=e.clientY-this.dragStartY;if(Math.hypot(dx,dy)<this.panThresholdPx)return;this.panning=true;this.tileMap.pan(dx,dy);this.dragX=e.clientX;this.dragY=e.clientY;this.draw();return;}const dx=e.clientX-this.dragX,dy=e.clientY-this.dragY;if(dx||dy){this.tileMap.pan(dx,dy);this.dragX=e.clientX;this.dragY=e.clientY;this.draw();}});
    window.addEventListener('mouseup',(e: MouseEvent)=>{if(!this.dragging||!this.isOpen())return;const pan=this.panning;this.dragging=false;this.panning=false;if(!pan&&e.target===this.canvas)this._handleMapClick(e).catch((err: unknown)=>this._error(err));});
    window.addEventListener('resize',()=>this._resize());
  }

  isOpen(){return this.overlay?.classList.contains('open');}
  open(initialType: string='depot'){
    this.sections=[];this.activeSectionId='';this.mode='idle';this._hoverCandidate=null;
    this.form={type:['depot','ite-fret','ite-industrie','ite-logistique'].includes(initialType)?initialType:'depot',name:'',tracks:isITE(initialType)?2:4,cost:50000,infrastructure:[],cargoTypes:[]};
    this.overlay.classList.add('open');this.tileMap.setNetworkEnabled?.(true);const main=this.game.renderer?.tileMap;if(main){this.tileMap.centerLat=main.centerLat;this.tileMap.centerLon=main.centerLon;this.tileMap.zoomLevel=Math.max(8,main.zoomLevel||9);}else{this.tileMap.centerLat=48.86;this.tileMap.centerLon=2.35;this.tileMap.zoomLevel=9;}
    this._setStatus('Ajoutez une section puis cliquez son point A. Chaque section est indépendante des autres.');this.renderPanel();requestAnimationFrame(()=>{this._resize();this.draw();});
  }
  close(){this._resolvePicker(null);this.overlay.classList.remove('open');this.tileMap.setNetworkEnabled?.(false);this.mode='idle';}
  _zoom(d: number){const r=this.canvas.getBoundingClientRect();this.tileMap.applyZoom(d>0?1:-1,r.width/2,r.height/2);this.draw();}
  _resize(){if(!this.isOpen())return;const r=this.canvas.parentElement!.getBoundingClientRect();this.canvas.width=Math.max(1,Math.floor(r.width));this.canvas.height=Math.max(1,Math.floor(r.height));this.tileMap.viewportWidth=this.canvas.width;this.tileMap.viewportHeight=this.canvas.height;this.draw();}
  _setStatus(t: string,busy: boolean=false){const e=this.overlay.querySelector('#iv2-status');if(e)e.textContent=t;const h=this.panel?.querySelector('#iv2-hint');if(h){h.textContent=t;h.classList.toggle('busy',busy);}}
  _active(){return this.sections.find((s: EditableRailSection)=>s.id===this.activeSectionId)||null;}
  _newSection(): EditableRailSection{const ite=isITE(this.form?.type);return {id:`infra-section-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,name:`${ite?'Voie ITE':'Accès dépôt'} ${this.sections.length+1}`,startBinding:null,endBinding:null,constraints:[],route:[],segments:[],distanceKm:0,length:0,cargoType:'',role:ite?'ite-track':'depot-access',direction:'both',manual:false,error:''};}
  addSection(){const s=this._newSection();this.sections.push(s);this.activeSectionId=s.id;this.mode='start';this._setStatus(`${s.name} : cliquez la voie ORM exacte du point A.`);this.renderPanel();this.draw();}
  deleteSection(){const s=this._active();if(!s)return;this.sections=this.sections.filter((x: EditableRailSection)=>x.id!==s.id);this.activeSectionId=this.sections.at(-1)?.id||'';this.mode='idle';this._setStatus(this.sections.length?'Section supprimée.':'Ajoutez une section.');this.renderPanel();this.draw();}
  armVia(){const s=this._active();if(!s?.startBinding||!s?.endBinding)return this._setStatus('Définissez A et B avant d’ajouter un VIA.');this.mode='via';this._setStatus('MODE VIA : cliquez la voie/aiguille ORM à imposer.');}
  async resetAuto(){const s=this._active();if(!s)return;s.constraints=[];s.manual=false;this.mode='idle';await this._recompute(s);this.renderPanel();this.draw();}
  async removeLastVia(){const s=this._active();if(!s?.constraints?.length)return;s.constraints.pop();await this._recompute(s);this.renderPanel();this.draw();}

  async _handleMapClick(e: MouseEvent){
    if(this.busy||this.picker.classList.contains('open'))return;let s=this._active();if(!s){this.addSection();s=this._active()!;}
    const r=this.canvas.getBoundingClientRect(),p=this.tileMap.screenToWorld(e.clientX-r.left,e.clientY-r.top,r.width,r.height);
    if(this.mode==='idle'){if(!s.startBinding)this.mode='start';else if(!s.endBinding)this.mode='end';else return this._setStatus('Utilisez + VIA ou + Section / voie.');}
    if(this.mode==='start'){const b=await this._chooseBinding(p.lat,p.lon,'Point A — voie exacte');if(!b)return;s.startBinding=b;s.endBinding=null;s.constraints=[];s.route=[];s.segments=[];s.distanceKm=0;s.length=0;this.mode='end';this._setStatus(`${s.name} : A verrouillé. Cliquez le point B, même très loin ou sur une autre zone.`);this.renderPanel();this.draw();return;}
    if(this.mode==='end'){const b=await this._chooseBinding(p.lat,p.lon,'Point B — voie exacte');if(!b)return;s.endBinding=b;this.mode='idle';await this._recompute(s);this._setStatus(`${s.name} : ${s.distanceKm.toFixed(2)} km. Vous pouvez créer une nouvelle section ailleurs sans relier B à la suivante.`);this.renderPanel();this.draw();return;}
    if(this.mode==='via'){const b=await this._chooseBinding(p.lat,p.lon,'Point VIA');if(!b)return;s.constraints.push({lat:b.snapLat,lon:b.snapLon,snapLat:b.snapLat,snapLon:b.snapLon,wayId:b.wayId||'',trackRef:b.trackRef||'',displayName:b.displayName||''});this.mode='idle';await this._recompute(s);this.renderPanel();this.draw();}
  }

  async _chooseBinding(lat: number,lon: number,title: string): Promise<BoundPoint | null>{
    if(typeof navigator!=='undefined'&&navigator.onLine===false){this._error(new Error('ORM hors ligne : impossible de sélectionner une nouvelle voie.'));return null;}
    this.busy=true;this._setStatus('Recherche des voies ORM…',true);try{const cs=await this.router.chooseTrackCandidates(lat,lon,{radiusM:55,limit:12});if(!cs?.length){this._error(new Error('Aucune voie ferroviaire ORM trouvée à proximité.'));return null;}if(cs.length===1)return bindFromCandidate(cs[0]);const c=await this._pickCandidate(cs,title);return c?bindFromCandidate(c):null;}finally{this.busy=false;}
  }
  _pickCandidate(candidates: CandidateLike[],title: string): Promise<CandidateLike | null>{return new Promise<CandidateLike | null>((resolve)=>{this._pickerResolve=resolve;this.picker.querySelector('h3').textContent=title||'Choisissez la voie ORM exacte';this.pickerList.innerHTML=candidates.map((c: CandidateLike,i: number)=>`<div class="iv2-candidate" data-i="${htmlText(i)}"><b>${esc(c.trackRef||c.name||c.ref||`OSM way ${c.wayId}`)}</b><small>ID ${esc(c.wayId)}${c.maxSpeed?` • ${esc(c.maxSpeed)} km/h`:''}${c.electrified===true?' • électrifiée':c.electrified===false?' • non électrifiée':''}</small></div>`).join('');this.pickerList.querySelectorAll('.iv2-candidate').forEach((el: Element)=>{(el as HTMLElement).onclick=()=>this._resolvePicker(candidates[Number(el.dataset.i)]);(el as HTMLElement).onmouseenter=()=>{this._hoverCandidate=candidates[Number(el.dataset.i)];this.draw();};(el as HTMLElement).onmouseleave=()=>{this._hoverCandidate=null;this.draw();};});this.picker.classList.add('open');});}
  _resolvePicker(v: CandidateLike | null){if(!this._pickerResolve){this.picker.classList.remove('open');return;}const r=this._pickerResolve;this._pickerResolve=null;this._hoverCandidate=null;this.picker.classList.remove('open');this.draw();r(v);}
  async _recompute(s: EditableRailSection){if(!s?.startBinding||!s?.endBinding)return false;this.busy=true;this._setStatus('Calcul du vrai tracé ferroviaire ORM…',true);try{const route=await this.router.routeBetweenBindings(s.startBinding,s.endBinding,s.constraints||[],{maxSpeed:300,allowFallback:false});const snap=this.router.snapshotRoute(route);if(!snap.routePoints?.length||snap.routePoints.length<2)throw new Error('Tracé ORM vide.');s.route=snap.routePoints;s.segments=snap.segments;s.distanceKm=snap.distanceKm;s.length=Math.max(1,Math.round(s.distanceKm*1000));s.error='';return true;}catch(err){const e=err as {message?:string}|null;s.error=e?.message||String(err);this._error(err);return false;}finally{this.busy=false;this.draw();}}

  _readForm(){
    this.form.type=this.panel.querySelector('#iv2-type')?.value||this.form.type;this.form.name=this.panel.querySelector('#iv2-name')?.value||'';this.form.tracks=Math.max(1,Math.min(30,Number(this.panel.querySelector('#iv2-tracks')?.value)||1));this.form.cost=Math.max(0,Number(this.panel.querySelector('#iv2-cost')?.value)||0);this.form.infrastructure=[...this.panel.querySelectorAll('.iv2-infra:checked')].map((x: Element)=>(x as HTMLInputElement).value);this.form.cargoTypes=[...this.panel.querySelectorAll('.iv2-cargo:checked')].map((x: Element)=>(x as HTMLInputElement).value);
  }
  renderPanel(){
    if(!this.panel)return;const s=this._active(),f=this.form||{},ite=isITE(f.type);this.panel.innerHTML=`
      <div id="iv2-hint" class="iv2-hint">${esc(this.overlay.querySelector('#iv2-status')?.textContent||'')}</div>
      <div class="iv2-field"><label>Type</label><select id="iv2-type"><option value="depot" ${f.type==='depot'?'selected':''}>Dépôt de maintenance</option><option value="ite-fret" ${f.type==='ite-fret'?'selected':''}>ITE Fret</option><option value="ite-industrie" ${f.type==='ite-industrie'?'selected':''}>ITE Industrie</option><option value="ite-logistique" ${f.type==='ite-logistique'?'selected':''}>ITE Logistique</option></select></div>
      <div class="iv2-field"><label>Nom</label><input id="iv2-name" value="${esc(f.name||'')}" placeholder="ex: Dijon-Perrigny"></div>
      <div class="iv2-field"><label>Rechercher / centrer sur une gare</label><input id="iv2-search" placeholder="Tapez le nom d’une gare…" autocomplete="off"><div class="iv2-search-results"><div id="iv2-search-list" class="iv2-search-list" style="display:none"></div></div></div>
      <div class="iv2-grid"><div class="iv2-field"><label>Nombre de voies</label><input type="number" id="iv2-tracks" min="1" max="30" value="${htmlText(Number(f.tracks||1))}"></div><div class="iv2-field"><label>Coût construction (€)</label><input type="number" id="iv2-cost" min="0" step="5000" value="${htmlText(Number(f.cost||0))}"></div></div>
      ${ite?`<div class="iv2-section"><h4>Fret accepté</h4><div class="iv2-checks">${([['vrac_solide','Vrac solide'],['cereales_agri','Céréales'],['conteneurs','Conteneurs'],['liquides','Liquides'],['gaz','Gaz'],['produits_chimiques','Chimique'],['automobiles','Automobiles']] as Array<[string,string]>).map(([v,l])=>`<label><input type="checkbox" class="iv2-cargo" value="${htmlText(v)}" ${(f.cargoTypes||[]).includes(v)?'checked':''}> ${l}</label>`).join('')}</div></div>`:`<div class="iv2-section"><h4>Équipements dépôt</h4><div class="iv2-checks">${([['remisage','Remisage'],['rotonde','Rotonde'],['technicentre','Technicentre']] as Array<[string,string]>).map(([v,l])=>`<label><input type="checkbox" class="iv2-infra" value="${htmlText(v)}" ${(f.infrastructure||[]).includes(v)?'checked':''}> ${l}</label>`).join('')}</div></div>`}
      <div class="iv2-section"><h4>${ite?'Voies ITE':'Sections d’accès'} (${this.sections.length})</h4>${this.sections.length?this.sections.map((x: EditableRailSection,i: number)=>`<div class="iv2-route-card ${htmlText(x.id===this.activeSectionId?'active':'')}" data-section="${esc(x.id)}"><div class="iv2-route-head"><span class="iv2-dot"></span><b>${esc(x.name||`Section ${i+1}`)}</b><span class="iv2-badge">${x.distanceKm?x.distanceKm.toFixed(2)+' km':'à tracer'}</span></div><small>${x.startBinding&&x.endBinding?'A → B ORM précis':'incomplète'}${x.constraints?.length?` • ${x.constraints.length} VIA`:''}${x.cargoType?` • ${esc(x.cargoType)}`:''}${x.error?` • ⚠ ${esc(x.error)}`:''}</small></div>`).join(''):'<div style="color:#8fa8c1;padding:8px 0">Aucune section. Cliquez + Section / voie.</div>'}</div>
      ${s?`<div class="iv2-section"><h4>Section sélectionnée</h4><div class="iv2-field"><label>Nom</label><input id="iv2-section-name" value="${esc(s.name||'')}"></div>${ite?`<div class="iv2-field"><label>Fret de cette voie</label><select id="iv2-section-cargo"><option value="" ${!s.cargoType?'selected':''}>Tout fret accepté par l’ITE</option><option value="vrac_solide" ${s.cargoType==='vrac_solide'?'selected':''}>Vrac solide</option><option value="cereales_agri" ${s.cargoType==='cereales_agri'?'selected':''}>Céréales</option><option value="conteneurs" ${s.cargoType==='conteneurs'?'selected':''}>Conteneurs</option><option value="liquides" ${s.cargoType==='liquides'?'selected':''}>Liquides</option><option value="gaz" ${s.cargoType==='gaz'?'selected':''}>Gaz</option><option value="produits_chimiques" ${s.cargoType==='produits_chimiques'?'selected':''}>Chimique</option><option value="automobiles" ${s.cargoType==='automobiles'?'selected':''}>Automobiles</option></select></div>`:''}<div style="font-size:10px;color:#8fa8c1">A : ${esc(s.startBinding?.trackRef||s.startBinding?.wayId||'non défini')}<br>B : ${esc(s.endBinding?.trackRef||s.endBinding?.wayId||'non défini')}<br>Longueur réelle : ${s.length?Math.round(s.length)+' m':'—'}<br>VIA : ${s.constraints?.length||0}</div></div>`:''}`;
    this._bindPanel();
  }
  _bindPanel(){
    const preserve=()=>this._readForm();
    this.panel.querySelector('#iv2-type')?.addEventListener('change',(e: Event)=>{preserve();this.form.type=(e.target as HTMLSelectElement).value;for(let i=0;i<this.sections.length;i++){this.sections[i].role=isITE(this.form.type)?'ite-track':'depot-access';if(!this.sections[i].name||/^(Voie ITE|Accès dépôt) \d+$/.test(this.sections[i].name))this.sections[i].name=`${isITE(this.form.type)?'Voie ITE':'Accès dépôt'} ${i+1}`;}this.renderPanel();});
    ['#iv2-name','#iv2-tracks','#iv2-cost'].forEach((sel: string)=>this.panel.querySelector(sel)?.addEventListener('change',preserve));this.panel.querySelectorAll('.iv2-infra,.iv2-cargo').forEach((x: Element)=>x.addEventListener('change',preserve));
    this.panel.querySelectorAll('.iv2-route-card').forEach((el: Element)=>el.addEventListener('click',()=>{preserve();this.activeSectionId=(el as HTMLElement).dataset.section!;this.mode='idle';this.renderPanel();this.draw();}));
    const s=this._active();if(s){this.panel.querySelector('#iv2-section-name')?.addEventListener('change',(e: Event)=>{s.name=(e.target as HTMLInputElement).value.trim()||s.name;this.renderPanel();});this.panel.querySelector('#iv2-section-cargo')?.addEventListener('change',(e: Event)=>{s.cargoType=(e.target as HTMLSelectElement).value||'';this.renderPanel();});}
    const search=this.panel.querySelector('#iv2-search'),list=this.panel.querySelector('#iv2-search-list');if(search&&list){search.addEventListener('input',()=>{const q=norm(search.value);if(q.length<2){list.style.display='none';return;}const hits: StationLike[]=[];for(const st of this.game.world.stations||[]){if(norm(st.name).includes(q)){hits.push(st);if(hits.length>=10)break;}}list.innerHTML=hits.map((st: StationLike)=>`<div class="iv2-search-item" data-st="${esc(st.id)}">${esc(st.name)}</div>`).join('');list.style.display=hits.length?'block':'none';list.querySelectorAll('[data-st]').forEach((el: Element)=>el.addEventListener('click',()=>{const st=this.game.world.getStationById((el as HTMLElement).dataset.st);if(st){this.tileMap.centerLat=st.lat;this.tileMap.centerLon=st.lon;this.tileMap.zoomLevel=Math.max(12,this.tileMap.zoomLevel||12);this.tileMap.markDirty?.();this.draw();search.value=st.name;list.style.display='none';this._setStatus(`${st.name} centrée. Cliquez maintenant les voies exactes.`);}}));});}
  }

  async save(){
    this._readForm();const name=this.form.name.trim()||(isITE(this.form.type)?'ITE':'Dépôt');const valid=this.sections.filter((s: EditableRailSection)=>s.startBinding&&s.endBinding&&s.route?.length>=2);if(!valid.length)return alert('Tracez au moins une section ferroviaire ORM complète.');if(valid.length!==this.sections.length)return alert('Une ou plusieurs sections sont incomplètes.');
    const first=valid[0],lat=Number(first.startBinding?.snapLat??first.route?.[0]?.lat),lon=Number(first.startBinding?.snapLon??first.route?.[0]?.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))return alert('Raccordement ferroviaire invalide.');
    const station=this.game.world.addStation({name,lat,lon,type:isITE(this.form.type)?'ite':'depot',platforms:this.form.tracks,platformNames:[]});station.country=this.game.orm.getCountryAtPoint(lat,lon);this.game.platformManager.initStation(station.id,this.form.tracks);
    const railSections=valid.map((raw: EditableRailSection,i: number)=>normalizeRailSection({...raw,id:`${station.id}-section-${i+1}`,direction:'both'},{name:`Section ${i+1}`,direction:'both'}));
    const iteTracks=isITE(this.form.type)?railSections.map((s: NormalizedRailSection,i: number)=>({name:s.name||`Voie ${i+1}`,length:Math.max(1,Math.round(s.length||s.distanceKm*1000)),cargoType:s.cargoType||'',startBinding:cloneRailValue(s.startBinding),endBinding:cloneRailValue(s.endBinding),constraints:cloneRailValue(s.constraints),route:cloneRailValue(s.route),segments:cloneRailValue(s.segments),distanceKm:s.distanceKm,role:'ite-track'})):[];
    const created=this.game.depotManager.add({schemaVersion:2,type:this.form.type,name,stationId:station.id,tracks:this.form.tracks,cost:this.form.cost,infrastructure:isITE(this.form.type)?[]:this.form.infrastructure,iteTracks,iteCargoTypes:isITE(this.form.type)?[...new Set([...(this.form.cargoTypes||[]),...iteTracks.map((t: {cargoType:string})=>t.cargoType).filter(Boolean)])]:[],railSections,location:{lat,lon}},this.game.economy);
    if(!created){this.game.world.removeStation?.(station.id);this.game.platformManager?.stationPlatforms?.delete?.(station.id);return alert('Fonds insuffisants : l’infrastructure n’a pas été créée.');}
    this.game.saveState();this.game.renderer?.invalidateStatic?.();this.ui.renderDepotsList();this.close();
  }

  _drawRoute(route: RailPoint[],color: string,width: number=4,alpha: number=1){if(!route?.length||route.length<2)return;const ctx=this.ctx;ctx.save();ctx.globalAlpha=alpha;ctx.lineJoin='round';ctx.lineCap='round';ctx.strokeStyle='#06101d';ctx.lineWidth=width+4;ctx.beginPath();route.forEach((p: RailPoint,i: number)=>{const q=this.tileMap.latLonToPixel(p.lat,p.lon);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y);});ctx.stroke();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();route.forEach((p: RailPoint,i: number)=>{const q=this.tileMap.latLonToPixel(p.lat,p.lon);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y);});ctx.stroke();ctx.restore();}
  _drawAnchor(b: RailBinding | null,color: string,r: number=6){if(!b)return;const p=this.tileMap.latLonToPixel(b.snapLat??b.lat,b.snapLon??b.lon),ctx=this.ctx;ctx.save();ctx.fillStyle=color;ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore();}
  draw(){
    if(!this.isOpen()||!this.canvas.width)return;const ctx=this.ctx,w=this.canvas.width,h=this.canvas.height;ctx.clearRect(0,0,w,h);this.tileMap.renderTiles(ctx,w,h);const zoom=this.tileMap.zoomLevel;let sts=this.game.world.stations||[];if(zoom>=7&&this.game.world.getStationsInBounds){const a=this.tileMap.screenToWorld(0,0,w,h),b=this.tileMap.screenToWorld(w,h,w,h);sts=this.game.world.getStationsInBounds(Math.min(a.lat,b.lat),Math.min(a.lon,b.lon),Math.max(a.lat,b.lat),Math.max(a.lon,b.lon));}
    ctx.save();ctx.fillStyle='#f4f7fb';ctx.strokeStyle='#182a3d';ctx.lineWidth=1;for(const st of sts){const p=this.tileMap.latLonToPixel(st.lat,st.lon);if(p.x<-5||p.y<-5||p.x>w+5||p.y>h+5)continue;if(zoom<7){ctx.fillRect(p.x,p.y,1.3,1.3);continue;}ctx.beginPath();ctx.arc(p.x,p.y,3.2,0,Math.PI*2);ctx.fill();ctx.stroke();if(zoom>=9){ctx.fillStyle='#dce8f7';ctx.font='10px system-ui';ctx.fillText(st.name,p.x+5,p.y-4);ctx.fillStyle='#f4f7fb';}}ctx.restore();
    for(const d of this.game.depotManager?.getAll?.()||[]){for(const s of d.railSections||[]){if(s.route?.length>=2)this._drawRoute(s.route,isITE(d.type)?'#047857':'#1d4ed8',2,0.3);}}
    for(const s of this.sections){if(s.route?.length>=2)this._drawRoute(s.route,sectionColor(s.id===this.activeSectionId),s.id===this.activeSectionId?5:3,s.id===this.activeSectionId?1:0.75);if(s.id===this.activeSectionId){this._drawAnchor(s.startBinding,'#22c55e',7);this._drawAnchor(s.endBinding,'#f97316',7);for(const c of s.constraints||[])this._drawAnchor(c,'#facc15',4);}}
    if(this._hoverCandidate?.geometry?.length)this._drawRoute(this._hoverCandidate.geometry,'#ffffff',5,0.9);
  }
  _error(err: unknown){console.error('Infrastructure V2',err);this._setStatus((err as {message?:string}|null)?.message||String(err));}
}
