// RE Saison 3 / TypeScript Alpha 2
// HOTFIX16 — single movement decision authority.
// Source TypeScript authoritative; js/movement-authority.js is generated by `npm run build:ts`.
// Operational systems submit GO/CAUTION/STOP constraints here; only this module
// mutates train.blockedBy and publishes the authoritative reason/speed ceiling.

export type MovementStatus = 'GO' | 'CAUTION' | 'STOP';

export interface MovementConstraintMeta {
  [key: string]: unknown;
}

export interface MovementConstraint {
  status: 'CAUTION' | 'STOP';
  limitKmh: number;
  code: string;
  reason: string;
  source: string;
  meta: MovementConstraintMeta | null;
}

export interface MovementDecision {
  status: MovementStatus;
  speedLimitKmh: number;
  code: string;
  reason: string;
  source: string;
  meta: MovementConstraintMeta | null;
  limitKmh?: number;
}

export interface PublishedMovementAuthority {
  status: MovementStatus;
  code: string;
  reason: string;
  source: string;
  speedLimitKmh: number;
  sequence: number;
}

export interface MovementAuthorityTrain {
  blockedBy: boolean;
  movementAuthority?: PublishedMovementAuthority;
  [key: string]: unknown;
}

function finiteLimit(value: unknown): number {
  const n = Number(value);
  return Number.isFinite(n) ? Math.max(0, n) : Infinity;
}

export class MovementAuthority {
  readonly train: MovementAuthorityTrain | null;
  readonly constraints: MovementConstraint[];
  sequence: number;
  baseLimitKmh!: number;

  constructor(train: MovementAuthorityTrain | null | undefined) {
    this.train = train || null;
    this.constraints = [];
    this.sequence = 0;
    this.begin();
  }

  begin(baseLimitKmh: unknown = Infinity): this {
    this.baseLimitKmh = finiteLimit(baseLimitKmh);
    this.constraints.length = 0;
    this.sequence++;
    this._publish();
    return this;
  }

  go(): this {
    return this.begin(this.baseLimitKmh);
  }

  caution(
    limitKmh: unknown,
    code = 'CAUTION',
    reason = 'marche prudente',
    source = 'runtime',
    meta: MovementConstraintMeta | null = null,
  ): this {
    const limit = finiteLimit(limitKmh);
    if (!(limit > 0) || limit === Infinity) return this;
    this.constraints.push({ status: 'CAUTION', limitKmh: limit, code, reason, source, meta });
    this._publish();
    return this;
  }

  stop(
    code = 'STOP',
    reason = 'arrêt de sécurité',
    source = 'runtime',
    meta: MovementConstraintMeta | null = null,
  ): this {
    this.constraints.push({ status: 'STOP', limitKmh: 0, code, reason, source, meta });
    this._publish();
    return this;
  }

  limit(
    limitKmh: unknown,
    code = 'LIMIT',
    reason = 'restriction de circulation',
    source = 'runtime',
    meta: MovementConstraintMeta | null = null,
  ): this {
    const limit = finiteLimit(limitKmh);
    if (limit <= 0) return this.stop(code, reason, source, meta);
    return this.caution(limit, code, reason, source, meta);
  }

  private _decision(): MovementDecision {
    // Per-train/per-step hot path: preserve priority and first-cause ties,
    // without allocating three intermediate filtered arrays on each query.
    let stop: MovementConstraint | null = null;
    let caution: MovementConstraint | null = null;
    for (const c of this.constraints) {
      if (c.status === 'STOP' || c.limitKmh <= 0) {
        if (!stop || finiteLimit(c.limitKmh) < finiteLimit(stop.limitKmh)) stop = c;
      } else if (Number.isFinite(c.limitKmh) && c.limitKmh < Infinity) {
        if (!caution || c.limitKmh < caution.limitKmh) caution = c;
      }
    }
    if (stop) return { ...stop, status: 'STOP', speedLimitKmh: 0 };
    if (caution) return { ...caution, status: 'CAUTION', speedLimitKmh: Math.min(this.baseLimitKmh, caution.limitKmh) };
    return { status: 'GO', speedLimitKmh: this.baseLimitKmh, code: 'GO', reason: '', source: 'movement-authority', meta: null };
  }

  private _publish(): MovementDecision | undefined {
    if (!this.train) return;
    const d = this._decision();
    // This is intentionally the single assignment site for blockedBy in HOTFIX16.
    this.train.blockedBy = d.status === 'STOP';
    this.train.movementAuthority = {
      status: d.status,
      code: d.code || d.status,
      reason: d.reason || '',
      source: d.source || 'runtime',
      speedLimitKmh: d.speedLimitKmh,
      sequence: this.sequence,
    };
    return d;
  }

  decision(): MovementDecision {
    return this._decision();
  }
}
