// RE Saison 3 / TypeScript Alpha 2
// HOTFIX40 — reusable railway-section geometry shared by Travaux V2 and Depot/ITE V2.
// Source TypeScript authoritative; js/rail-section-geometry.js is generated by `npm run build:ts`.
// A section is one independent A→B ORM route. Collections of sections do NOT imply
// any physical continuity between B of one section and A of the next.

export const RAIL_SECTION_DIRECTIONS = Object.freeze({
  BOTH: 'both',
  FORWARD: 'forward',
  REVERSE: 'reverse',
} as const);

export type RailSectionDirection = typeof RAIL_SECTION_DIRECTIONS[keyof typeof RAIL_SECTION_DIRECTIONS];

export interface RailPoint {
  lat: number;
  lon: number;
  wayId?: string;
  fallback?: boolean;
  synthetic?: boolean;
  [key: string]: unknown;
}

export interface RailBinding {
  lat: number;
  lon: number;
  snapLat: number;
  snapLon: number;
  wayId?: string;
  trackRef?: string;
  [key: string]: unknown;
}

export interface RailSectionLike {
  id?: unknown;
  name?: unknown;
  startBinding?: unknown;
  endBinding?: unknown;
  constraints?: unknown;
  route?: unknown;
  segments?: unknown;
  distanceKm?: unknown;
  length?: unknown;
  direction?: unknown;
  manual?: unknown;
  cargoType?: unknown;
  role?: unknown;
  [key: string]: unknown;
}

export interface RailSectionDefaults {
  id?: unknown;
  name?: unknown;
  direction?: unknown;
  cargoType?: unknown;
  role?: unknown;
  [key: string]: unknown;
}

export interface NormalizedRailSection {
  id: string;
  name: string;
  startBinding: RailBinding | null;
  endBinding: RailBinding | null;
  constraints: unknown[];
  route: RailPoint[];
  segments: unknown[];
  distanceKm: number;
  length: number;
  direction: RailSectionDirection;
  manual: boolean;
  cargoType: string;
  role: string;
}

export function normalizeSectionDirection(value: unknown): RailSectionDirection {
  return value === RAIL_SECTION_DIRECTIONS.FORWARD || value === RAIL_SECTION_DIRECTIONS.REVERSE
    ? value
    : RAIL_SECTION_DIRECTIONS.BOTH;
}

export function sectionDirectionLabel(value: unknown): string {
  const v = normalizeSectionDirection(value);
  if (v === RAIL_SECTION_DIRECTIONS.FORWARD) return 'A → B uniquement';
  if (v === RAIL_SECTION_DIRECTIONS.REVERSE) return 'B → A uniquement';
  return 'Deux sens';
}

export function cloneRailValue<T>(v: T): T {
  return v == null ? v : JSON.parse(JSON.stringify(v)) as T;
}

export function cleanRailBinding(v: unknown): RailBinding | null {
  if (!v || typeof v !== 'object') return null;
  const input = v as Record<string, unknown>;
  const lat = Number(input.snapLat ?? input.lat), lon = Number(input.snapLon ?? input.lon);
  if (!Number.isFinite(lat) || !Number.isFinite(lon) || lat < -90 || lat > 90 || lon < -180 || lon > 180) return null;
  const out: Record<string, unknown> = { ...input };
  out.lat = Number.isFinite(Number(input.lat)) ? Number(input.lat) : lat;
  out.lon = Number.isFinite(Number(input.lon)) ? Number(input.lon) : lon;
  out.snapLat = lat; out.snapLon = lon;
  if (out.wayId != null) out.wayId = String(out.wayId);
  if (out.trackRef != null) out.trackRef = String(out.trackRef);
  return out as RailBinding;
}

export function cleanRailRoute(route: unknown): RailPoint[] {
  return (Array.isArray(route) ? route : []).filter((p: unknown) => {
    if (!p || typeof p !== 'object') return false;
    const point = p as Record<string, unknown>;
    const lat = Number(point.lat), lon = Number(point.lon);
    return Number.isFinite(lat) && Number.isFinite(lon) && lat >= -90 && lat <= 90 && lon >= -180 && lon <= 180 && !point.fallback && !point.synthetic;
  }).map((p: unknown) => {
    const point = p as Record<string, unknown>;
    return {
      ...point,
      lat: Number(point.lat),
      lon: Number(point.lon),
      ...(point.wayId != null ? { wayId: String(point.wayId) } : {}),
    } as RailPoint;
  });
}

export function normalizeRailSection(data: RailSectionLike = {}, defaults: RailSectionDefaults = {}): NormalizedRailSection {
  const route = cleanRailRoute(data.route);
  const dist = Number(data.distanceKm);
  const length = Number(data.length);
  return {
    id: String(data.id || defaults.id || ''),
    name: String(data.name || defaults.name || 'Section').trim() || 'Section',
    startBinding: cleanRailBinding(data.startBinding),
    endBinding: cleanRailBinding(data.endBinding),
    constraints: Array.isArray(data.constraints) ? cloneRailValue(data.constraints) : [],
    route,
    segments: Array.isArray(data.segments) ? cloneRailValue(data.segments) : [],
    distanceKm: Number.isFinite(dist) && dist >= 0 ? dist : 0,
    length: Number.isFinite(length) && length > 0 ? length : (Number.isFinite(dist) && dist > 0 ? Math.round(dist * 1000) : 0),
    direction: normalizeSectionDirection(data.direction ?? defaults.direction),
    manual: !!data.manual,
    cargoType: String(data.cargoType ?? defaults.cargoType ?? ''),
    role: String(data.role ?? defaults.role ?? ''),
  };
}

function approxSqKm(aLat: unknown, aLon: unknown, bLat: unknown, bLon: unknown): number {
  const mid = ((Number(aLat) + Number(bLat)) * 0.5) * Math.PI / 180;
  const x = (Number(aLon) - Number(bLon)) * 111 * Math.cos(mid);
  const y = (Number(aLat) - Number(bLat)) * 111;
  return x*x + y*y;
}

interface LatLonPoint { lat: number; lon: number; }

function bindingPoint(binding: unknown, fallback: unknown): LatLonPoint | null {
  if (binding && typeof binding === 'object') {
    const b = binding as Record<string, unknown>;
    const lat = Number(b.snapLat ?? b.lat), lon = Number(b.snapLon ?? b.lon);
    if (Number.isFinite(lat) && Number.isFinite(lon)) return { lat, lon };
  }
  if (fallback && typeof fallback === 'object') {
    const f = fallback as Record<string, unknown>;
    const lat = Number(f.lat), lon = Number(f.lon);
    if (Number.isFinite(lat) && Number.isFinite(lon)) return { lat, lon };
  }
  return null;
}

function nearestRouteIndex(route: unknown, point: LatLonPoint | null): number {
  if (!Array.isArray(route) || !route.length || !point) return -1;
  let best = -1, bestD = Infinity;
  for (let i = 0; i < route.length; i++) {
    const raw = route[i];
    if (!raw || typeof raw !== 'object') continue;
    const p = raw as Record<string, unknown>;
    if (!Number.isFinite(Number(p.lat)) || !Number.isFinite(Number(p.lon))) continue;
    const d = approxSqKm(p.lat, p.lon, point.lat, point.lon);
    if (d < bestD) { bestD = d; best = i; }
  }
  return best;
}

// Does a train route cross this section in a direction affected by the restriction?
// `forward` is A→B as drawn by the player, `reverse` is B→A. `both` is default.
export function railSectionDirectionMatchesRoute(trainRoute: unknown, section: RailSectionLike | null | undefined): boolean {
  const direction = normalizeSectionDirection(section?.direction);
  if (direction === RAIL_SECTION_DIRECTIONS.BOTH) return true;
  if (!Array.isArray(trainRoute) || trainRoute.length < 2) return true; // fail safe

  const sectionRoute = cleanRailRoute(section?.route);
  const start = bindingPoint(section?.startBinding, sectionRoute[0]);
  const end = bindingPoint(section?.endBinding, sectionRoute[sectionRoute.length - 1]);
  if (!start || !end) return true;

  const iA = nearestRouteIndex(trainRoute, start);
  const iB = nearestRouteIndex(trainRoute, end);
  if (iA < 0 || iB < 0) return true;
  if (iA !== iB) return direction === RAIL_SECTION_DIRECTIONS.FORWARD ? iA < iB : iB < iA;

  // Very short section / coarse route: compare local route vector with A→B vector.
  const i0 = Math.max(0, iA - 1), i1 = Math.min(trainRoute.length - 1, iA + 1);
  const p0 = trainRoute[i0] as Record<string, unknown>, p1 = trainRoute[i1] as Record<string, unknown>;
  const cos = Math.cos(start.lat * Math.PI / 180);
  const tx = (Number(p1.lon) - Number(p0.lon)) * cos, ty = Number(p1.lat) - Number(p0.lat);
  const sx = (end.lon - start.lon) * cos, sy = end.lat - start.lat;
  const dot = tx * sx + ty * sy;
  return direction === RAIL_SECTION_DIRECTIONS.FORWARD ? dot >= 0 : dot <= 0;
}
